// List of tags for which the category is the same
export const sameNameTags = [
  "Aplicativo 156+POA",
  "Asilo Padre Cacique",
  "Avenida Sertório",
  "Banco de Talentos",
  "Brechocão",
  "Cais Mauá",
  "Casa Lar do Idoso",
  "Cecoflor",
  "Colégio Militar de Porto Alegre",
  "Colônia de Pescadores Z5",
  "DermatoNet",
  "Edifício Intendente José Montaury",
  "ETA São João",
  "Farmácia Distrital Modelo",
  "Ilha da Pintada",
  "Instituto Caldeira",
  "Largo Glênio Peres",
  "Liquida Porto Alegre",
  "Lomba do Pinheiro",
  "Reserva Biológica do Lami José Lutzenberger",
  "Maio Vermelho",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Pinacoteca Ruben Berta",
  "Sala Álvaro Moreyra",
  "TelessaúdeRS",
  "Todos Somos Porto Alegre",
  "Teatro Renascença",
  "Usina do Gasômetro",
  "Viaduto Otávio Rocha",
  "Vigidesastres",
  "Vila Jardim",
  "Vila Minuano",
  "Unidade de Saúde Alto Embratel",
  "Unidade de Saúde Orfanotrófio",
  "Unidade de Saúde Osmar Freitas",
  "Unidade de Saúde Santo Alfredo",
  "Unidade Móvel de Saúde",
  "Centro de Saúde IAPI",
  "Centro de Saúde Modelo",
  "Consultório na Rua",
  "Comando Militar do Sul",
  "Unipoa",
  "Grêmio Foot-Ball Porto Alegrense",
  "Sport Club Internacional",
  "Casa de Cultura Mario Quintana",
  "Palácio Piratini",
  "Túnel da Conceição",
  "Plaza São Rafael",
  "Residencial São Guilherme",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro Cultural Usina do Gasômetro",
  "Arroio Dilúvio",
  "Arena do Grêmio",
  "Ação Rua",
  "Trensurb",
  "Companhia Municipal de Dança",
  "Companhia Jovem de Dança",
  "Polícia Rodoviária Federal",
  "Semana de Porto Alegre",
  "Linha Turismo",
  "Anfiteatro Pôr do Sol",
  "Praia de Belas",
  "Pinacoteca Aldo Locatelli",
  "Prometas",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Cinemateca Capitólio",
  "Praça Darcy Azambuja",
  "Fique Sabendo Jovem",
  "Ginásio Tesourinha",
  "Aldeia Kaingang",
  "Parque Natural Municipal Morro do Osso",
  "Fundação Iberê Camargo",
  "Bikepoa",
  "Capester",
  "Rede Calabria",
  "Operação Inverno",
  "Extremo Sul",
  "WhatsApp",
];
