// List of tags for which the category is the same
export const sameNameTags = [
  "A Cara da Obra",
  "Abrigo de Animais da EPTC",
  "Ação Rua",
  "Aldeia Kaingang",
  "Anfiteatro Pôr do Sol",
  "Aplicativo 156+POA",
  "Arena do Grêmio",
  "Arroio Dilúvio",
  "Asilo Padre Cacique",
  "Avenida Assis Brasil",
  "Avenida Coronel Marcos",
  "Avenida Padre Cacique",
  "Avenida Sertório",
  "Avenida Severo Dullius",

  "Banco de Talentos",
  "Bikepoa",
  "Brechocão",
  "Cais Mauá",
  "Capester",
  "Casa de Cultura Mario Quintana",
  "Casa Lar do Idoso",
  "Cecoflor",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural Usina do Gasômetro",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Saúde IAPI",
  "Centro de Saúde Modelo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Cinemateca Capitólio",
  "Colégio Militar de Porto Alegre",
  "Colônia de Pescadores Z5",
  "Comando Militar do Sul",
  "Companhia Jovem de Dança",
  "Companhia Municipal de Dança",
  "Complexo Hospitalar Santa Casa",
  "Consultório na Rua",
  "Cootravipa",

  "DermatoNet",
  "Dia D de Vacinação",
  "Dia do Gari",

  "Edifício Intendente José Montaury",
  "Eixo Baltazar",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "EMEF Vereador Antônio Giúdice",
  "EMEI Dom Luiz de Nadal",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "Estrada das Furnas",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Extremo Sul",

  "Farmácia Distrital Modelo",
  "Farmácia Móvel",
  "Fique Sabendo Jovem",
  "Fórum Social Mundial da População Idosa",
  "Fundação Iberê Camargo",

  "Ginásio Tesourinha",
  "Grêmio Foot-Ball Porto Alegrense",

  "Ilha da Pintada",
  "Instituto Caldeira",
  "Instituto Ling",

  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Lomba do Pinheiro",

  "Maio Vermelho",
  "Morro Ricaldone",
  "Museu de Porto Alegre Joaquim Felizardo",

  "Natal dos Encantos",

  "Operação Inverno",
  "Orla de Ipanema",

  "Palácio Piratini",
  "Parque Chico Mendes",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Parque Natural Municipal Morro do Osso",
  "Pedestre Idoso",
  "Pinacoteca Aldo Locatelli",
  "Pinacoteca Ruben Berta",
  "Plataforma Reconstruir Porto Alegre",
  "Plaza São Rafael",
  "Polícia Rodoviária Federal",
  "Porto Alegre",
  "Praça Darcy Azambuja",
  "Praça Doutor Lopes Trovão",
  "Praia de Belas",
  "Prefeitura nos Bairros",
  "Procuradoria-Geral do Município de Porto Alegre",
  "Projeto Pescar",
  "Prometas",

  "Rede Calabria",
  "Reserva Biológica do Lami José Lutzenberger",
  "Residencial São Guilherme",
  "Rua José Pedro Boessio",

  "Sala Álvaro Moreyra",
  "Semana de Porto Alegre",
  "Shopping Total",
  "Sport Club Internacional",
  "TelessaúdeRS",
  "Todos Somos Porto Alegre",
  "Teatro Renascença",
  "Trensurb",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Túnel da Conceição",

  "Unidade de Saúde Alto Embratel",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Orfanotrófio",
  "Unidade de Saúde Osmar Freitas",
  "Unidade de Saúde Santo Alfredo",
  "Unidade de Saúde São Carlos",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "UPA Moacyr Scliar",
  "Usina do Gasômetro",

  "Viaduto da Conceição",
  "Viaduto Otávio Rocha",
  "Vigidesastres",
  "Vila dos Ferroviários",
  "Vila Jardim",
  "Vila Minuano",
  "WhatsApp",
];
