// List of tags for which the category is the same
export const sameNameTags = [
  "Anfiteatro Pôr do Sol",
  "Aplicativo 156+POA",
  "Arena do Grêmio",
  "Arroio Dilúvio",
  "Avenida Assis Brasil",
  "Avenida Coronel Marcos",
  "Asilo Padre Cacique",
  "Avenida Padre Cacique",
  "Avenida Sertório",
  "Banco de Talentos",
  "Bikepoa",
  "Brechocão",
  "Cais Mauá",
  "Capester",
  "Casa de Cultura Mario Quintana",
  "Casa Lar do Idoso",
  "Cecoflor",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural Usina do Gasômetro",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Saúde IAPI",
  "Centro de Saúde Modelo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Cinemateca Capitólio",
  "Colégio Militar de Porto Alegre",
  "Colônia de Pescadores Z5",
  "Comando Militar do Sul",
  "Companhia Jovem de Dança",
  "Companhia Municipal de Dança",
  "Consultório na Rua",
  "Cootravipa",
  "DermatoNet",
  "Dia do Gari",
  "Edifício Intendente José Montaury",
  "Eixo Baltazar",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "EMEF Vereador Antônio Giúdice",
  "EMEI Miguel Granato Velasquez",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Extremo Sul",
  "Farmácia Distrital Modelo",
  "Fundação Iberê Camargo",
  "Grêmio Foot-Ball Porto Alegrense",
  "Ilha da Pintada",
  "Instituto Caldeira",
  "Instituto Ling",
  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Lomba do Pinheiro",
  "Maio Vermelho",
  "Morro Ricaldone",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Operação Inverno",
  "Orla de Ipanema",
  "Palácio Piratini",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Parque Natural Municipal Morro do Osso",
  "Pinacoteca Aldo Locatelli",
  "Pinacoteca Ruben Berta",
  "Plataforma Reconstruir Porto Alegre",
  "Plaza São Rafael",
  "Polícia Rodoviária Federal",
  "Porto Alegre",
  "Praça Darcy Azambuja",
  "Praia de Belas",
  "Procuradoria-Geral do Município de Porto Alegre",
  "Prometas",
  "Rede Calabria",
  "Reserva Biológica do Lami José Lutzenberger",
  "Residencial São Guilherme",
  "Sala Álvaro Moreyra",
  "Semana de Porto Alegre",
  "Shopping Total",
  "Sport Club Internacional",
  "TelessaúdeRS",
  "Todos Somos Porto Alegre",
  "Teatro Renascença",
  "Trensurb",
  "Túnel da Conceição",
  "Unidade de Saúde Alto Embratel",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Orfanotrófio",
  "Unidade de Saúde Osmar Freitas",
  "Unidade de Saúde Santo Alfredo",
  "Unidade Móvel de Saúde",
  "UPA Moacyr Scliar",
  "Usina do Gasômetro",
  "Viaduto da Conceição",
  "Viaduto Otávio Rocha",
  "Vigidesastres",
  "Vila Jardim",
  "Vila Minuano",
  "Unipoa",
  "Ação Rua",
  "Fique Sabendo Jovem",
  "Ginásio Tesourinha",
  "Aldeia Kaingang",
  "WhatsApp",
];
