import { getYear } from "../../Utils/DateUtils";

// Define a mapping of tags to categories
export const tagToCategoryMap = {
  Segurança: "Secretaria Municipal de Segurança (Porto Alegre)",
  Smseg: "Secretaria Municipal de Segurança (Porto Alegre)",
  "Secretaria Municipal de Segurança (SMSEG)":
    "Secretaria Municipal de Segurança (Porto Alegre)",
  "SMSEG - Segurança": "Secretaria Municipal de Segurança (Porto Alegre)",
  "Desenvolvimento Social":
    "Secretaria Municipal de Desenvolvimento Social (Porto Alegre)",
  Smdse: "Secretaria Municipal de Desenvolvimento Social (Porto Alegre)",
  "Secretaria Municipal de Desenvolvimento Social (SMDS)":
    "Secretaria Municipal de Desenvolvimento Social (Porto Alegre)",
  "Secretaria Municipal de Desenvolvimento Econômico e Turismo (SMDET)":
    "Secretaria Municipal de Desenvolvimento Econômico e Turismo (Porto Alegre)",
  "Meio Ambiente":
    "Secretaria Municipal do Meio Ambiente e Sustentabilidade (Porto Alegre)",
  "Meio Ambiente e Sustentabilidade":
    "Secretaria Municipal do Meio Ambiente e Sustentabilidade (Porto Alegre)",
  Smams:
    "Secretaria Municipal do Meio Ambiente e Sustentabilidade (Porto Alegre)",
  "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (SMAMUS)":
    "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (Porto Alegre)",
  "Meio Ambiente, Urbanismo e Sustentabilidade":
    "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (Porto Alegre)",
  "Planejamento e Gestão":
    "Secretaria Municipal de Planejamento e Gestão (Porto Alegre)",
  "Infraestrutura e Mobilidade":
    "Secretaria Municipal de Infraestrutura e Mobilidade (Porto Alegre)",
  "Infraestrutura e Mobilidade Urbana":
    "Secretaria Municipal de Infraestrutura e Mobilidade (Porto Alegre)",
  "Secretaria Municipal de Mobilidade Urbana (SMMU)":
    "Secretaria Municipal de Mobilidade Urbana (Porto Alegre)",
  "Mobilidade Urbana":
    "Secretaria Municipal de Mobilidade Urbana (Porto Alegre)",
  "Secretaria Municipal de Obras e Infraestrutura (SMOI)":
    "Secretaria Municipal de Obras e Infraestrutura (Porto Alegre)",
  "Obras e Infraestrutura":
    "Secretaria Municipal de Obras e Infraestrutura (Porto Alegre)",
  "Relações Institucionais":
    "Secretaria Municipal de Relações Institucionais (Porto Alegre)",
  "Esportes, Recreação e Lazer":
    "Secretaria Municipal de Esportes, Recreação e Lazer",
  Seda: "Secretaria Municipal dos Direitos Animais (Porto Alegre)",
  "Secretaria Municipal de Cultura e Economia Criativa (SMCEC)":
    "Secretaria Municipal de Cultura e Economia Criativa (Porto Alegre)",
  "Cultura e Economia Criativa":
    "Secretaria Municipal de Cultura e Economia Criativa (Porto Alegre)",
  "Direitos dos Animais":
    "Secretaria Municipal dos Direitos Animais (Porto Alegre)",
  "Direitos Animais":
    "Secretaria Municipal dos Direitos Animais (Porto Alegre)",
  "Secretaria Municipal de Esporte, Lazer e Juventude (SMELJ)":
    "Secretaria Municipal de Esporte, Lazer e Juventude (Porto Alegre)",
  "Esporte, Lazer e Juventude":
    "Secretaria Municipal de Esporte, Lazer e Juventude (Porto Alegre)",
  "Esporte Lazer e Juventude":
    "Secretaria Municipal de Esporte, Lazer e Juventude (Porto Alegre)",
  "Secretaria Municipal de Transparência e Controladoria (SMTC)":
    "Secretaria Municipal de Transparência e Controladoria (Porto Alegre)",
  "Secretaria Municipal de Governança Local e Coordenação Política (SMGOV)":
    "Secretaria Municipal de Governança Local e Coordenação Política (Porto Alegre)",
  "Governança Local e Coordenação Política":
    "Secretaria Municipal de Governança Local e Coordenação Política (Porto Alegre)",
  "Secretaria Municipal de Habitação e Regularização Fundiária (SMHARF)":
    "Secretaria Municipal de Habitação e Regularização Fundiária (Porto Alegre)",
  "Habitação Regularização Fundiária":
    "Secretaria Municipal de Habitação e Regularização Fundiária (Porto Alegre)",
  "Habitação e Regularização Fundiária":
    "Secretaria Municipal de Habitação e Regularização Fundiária (Porto Alegre)",
  Parcerias: "Secretaria Municipal de Parcerias (Porto Alegre)",
  "Secretaria Municipal de Parcerias (SMP)":
    "Secretaria Municipal de Parcerias (Porto Alegre)",
  "Secretaria Municipal de Administração e Patrimônio (SMAP)":
    "Secretaria Municipal de Administração e Patrimônio (Porto Alegre)",
  "Administração e Patrimônio":
    "Secretaria Municipal de Administração e Patrimônio (Porto Alegre)",
  "Administração É Patrimônio":
    "Secretaria Municipal de Administração e Patrimônio (Porto Alegre)",
  "Secretário Municipal de Administração e Patrimônio (SMAP)":
    "Secretaria Municipal de Administração e Patrimônio (Porto Alegre)",
  "Secretaria Municipal de Planejamento e Assuntos Estratégicos (SMPAE)":
    "Secretaria Municipal de Planejamento e Assuntos Estratégicos (Porto Alegre)",
  "Planejamento e Assuntos Estratégicos":
    "Secretaria Municipal de Planejamento e Assuntos Estratégicos (Porto Alegre)",
  "Gabinete de Inovação (GI)": "Gabinete da Inovação (Porto Alegre)",
  "Comunicação Social": "Gabinete de Comunicação Social (Porto Alegre)",
  "Gabinete da Causa Animal (GCA)": "Gabinete da Causa Animal (Porto Alegre)",
  "Causa Animal": "Gabinete da Causa Animal (Porto Alegre)",
  Procuradoria: "Procuradoria-Geral do Município de Porto Alegre",
  Secretariado: "Municipal secretariats of Porto Alegre",
  "Secretaria Extraordinária do Trabalho e da Qualificação Profissional (SMTQ)":
    "Secretaria Extraordinária do Trabalho e da Qualificação Profissional (Porto Alegre)",
  "Trabalho e Qualificação":
    "Secretaria Extraordinária do Trabalho e da Qualificação Profissional (Porto Alegre)",
  Procempa: "Companhia de Processamento de Dados do Município de Porto Alegre",
  "Companhia de Processamento de Dados do Município (Procempa)":
    "Companhia de Processamento de Dados do Município de Porto Alegre",
  DMLU: "Departamento Municipal de Limpeza Urbana (Porto Alegre)",
  Dmlu: "Departamento Municipal de Limpeza Urbana (Porto Alegre)",
  "Limpeza Urbana": "Departamento Municipal de Limpeza Urbana (Porto Alegre)",
  "Departamento Municipal de Habitação (Demhab)":
    "Departamento Municipal de Habitação (Porto Alegre)",
  "Departamento Municipal de Limpeza Urbana (DMLU)":
    "Departamento Municipal de Limpeza Urbana (Porto Alegre)",
  "Centro Integrado de Comando":
    "Centro Integrado de Comando da Cidade de Porto Alegre",
  "Centro Integrado de Comando da Cidade de Porto Alegre (CEIC)":
    "Centro Integrado de Comando da Cidade de Porto Alegre",
  "Comissão Permanente de Atuação em Emergências (Copae)":
    "Comissão Permanente de Atuação em Emergências",
  "Defesa Civil": "Diretoria-Geral de Defesa Civil de Porto Alegre",
  "Defesa Cívil": "Diretoria-Geral de Defesa Civil de Porto Alegre",
  "Equipe de Manejo Arbóreo (EMA)": "Equipe de Manejo Arbóreo (Porto Alegre)",
  "Equipe de Vigilância em Saúde Ambiental e Águas (EVSAA)":
    "Equipe de Vigilância em Saúde Ambiental e Águas (Porto Alegre)",
  DMAP: "DMAP (Porto Alegre)",
  CGVS: "CGVS (Porto Alegre)",
  DMAE: "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  Dmae: "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  Água: "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  "Água e Esgotos": "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  "Água e Esgoto": "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  "Departamento Municipal de Água e Esgotos (DMAE)":
    "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  "Rede de abastecimento de água":
    "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  "redes de água": "Departamento Municipal de Água e Esgotos (Porto Alegre)",
  "Sine Municipal": "Sine Municipal (Porto Alegre)",
  EPTC: "Empresa Pública de Transporte e Circulação de Porto Alegre",
  "Empresa Pública de Transporte e Circulação (EPTC)":
    "Empresa Pública de Transporte e Circulação de Porto Alegre",
  "Coordenação de Operações Especiais (COE)":
    "Empresa Pública de Transporte e Circulação de Porto Alegre",
  Fasc: "Fundação de Assistência Social e Cidadania",
  "Fundação de Assistência Social e Cidadania – Fasc":
    "Fundação de Assistência Social e Cidadania",
  Legislativo: "Câmara Municipal de Porto Alegre",
  "Câmara Municipal de Porto Alegre (CMPA)": "Câmara Municipal de Porto Alegre",
  vereador: "City councillors of Porto Alegre",
  Pisa: "Programa Integrado Socioambiental",
  "Unidade de Saúde Orfanotrófrio": "Unidade de Saúde Orfanotrófio",
  "Unidade de Saúde Animal Victória (Usav)": "Unidade de Saúde Animal Victória",
  "Primeira Infância Melhor (PIM)": "Primeira Infância Melhor",
  "Salão Nobre": "Salão Nobre (Paço Municipal de Porto Alegre)",
  "Salão Nobre do Paço Municipal":
    "Salão Nobre (Paço Municipal de Porto Alegre)",
  "Sala dos Embaixadores":
    "Sala dos Embaixadores (Paço Municipal de Porto Alegre)",
  "Restaurante Popular": "Restaurantes Populares",
  Capacitação: "Trainings by the Municipality of Porto Alegre",
  Curso: "Courses (education) by the Municipality of Porto Alegre",
  "Curso de Formação": "Training courses by the Municipality of Porto Alegre",
  Visita: "Official visits involving the Municipality of Porto Alegre",
  "Visita de Cortesia":
    "Official visits involving the Municipality of Porto Alegre",
  "Viagem à Brasília":
    "Official visits involving the Municipality of Porto Alegre",
  Convênio: "Partnerships involving the Municipality of Porto Alegre",
  "Coletiva de Imprensa":
    "Press conferences by the Municipality of Porto Alegre",
  "Entrevista Coletiva":
    "Press conferences by the Municipality of Porto Alegre",
  "Guarda Municipal": "Guarda Municipal (Porto Alegre)",
  "Rede Municipal de Ensino": "Rede Municipal de Ensino (Porto Alegre)",
  "Núcleo de Imunizações DVS (NI)": "Núcleo de Imunizações DVS (Porto Alegre)",
  "Diretoria de Vigilância em Saúde (DVS)":
    "Diretoria de Vigilância em Saúde de Porto Alegre",
  "Vigilância em Saúde": "Diretoria de Vigilância em Saúde de Porto Alegre",
  "Vigilância Sanitária": "Diretoria de Vigilância em Saúde de Porto Alegre",
  "Serviço de Atendimento Móvel de Urgência (SAMU)":
    "Serviço de Atendimento Móvel de Urgência",
  "Estação de Bombeamento de Águas Pluviais (Ebap)":
    "Estações de Bombeamento de Águas Pluviais",
  "Casa de Bombas": "Estações de Bombeamento de Águas Pluviais",
  "Estações de Bombeamento de Águas Pluviais (Ebaps)":
    "Estações de Bombeamento de Águas Pluviais",
  "(EBAB) Moinhos de Vento": "EBAB Moinhos de Vento",
  "Aplicativo (app)": "Mobile apps of the Municipality of Porto Alegre",
  Carris: "Companhia Carris Porto-Alegrense",
  "Companhia Carris Porto Alegrense": "Companhia Carris Porto-Alegrense",
  "Assistência Farmacêutica": "Assistência Farmacêutica (Porto Alegre)",
  "Centro Humanístico Vida": "Vida Centro Humanístico",
  "Coordenação Municipal de Urgências (CMU)":
    "Coordenação Municipal de Urgências (Porto Alegre)",
  "(Emei JP) Cantinho Amigo": "EMEI JP Cantinho Amigo",
  "Emeb Liberato Salzano Vieira da Cunha":
    "EMEB Liberato Salzano Vieira da Cunha",
  "#eufaçopoa": "EuFaçoPOA",
  "Plano de ação Porto Alegre Forte": "Porto Alegre Forte",
  "Programa de Residência Técnico-Superior (PRTS)":
    "Programa de Residência Técnico-Superior",
  "Lei Orçamentária Anual (LOA)": "Lei Orçamentária Anual",

  Senac: "Serviço Nacional de Aprendizagem Comercial",
  Famurs: "Federação das Associações de Municípios do Rio Grande do Sul",
  Granpal: "Associação dos Municípios da Região Metropolitana de Porto Alegre",
  "Associação dos Auditores Fiscais da Receita Municipal de Porto Alegre (Aiamu)":
    "Associação dos Auditores Fiscais da Receita Municipal de Porto Alegre",

  "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)":
    "Universidade Federal de Ciências da Saúde de Porto Alegre",
  "Universidade Federal do Rio Grande do Sul (UFRGS)":
    "Universidade Federal do Rio Grande do Sul",
  PUCRS: "Pontifícia Universidade Católica do Rio Grande do Sul",
  "Pontifícia Universidade Católica do RS (PUCRS)":
    "Pontifícia Universidade Católica do Rio Grande do Sul",
  "Escola de Gestão Pública (EGP)": "Escola de Gestão Pública (Porto Alegre)",

  "Sindicato dos Municipários de Porto Alegre (Simpa)":
    "Sindicato dos Municipários de Porto Alegre",
  "Igreja Nossa Senhora das Dores":
    "Igreja Nossa Senhora das Dores (Porto Alegre)",
  "Assembléia Legislativa": "Legislative Assembly of Rio Grande do Sul",
  "Fonte Talavera": "Fonte Talavera de La Reina",
  "Mercado Público Central": "Mercado Público de Porto Alegre",

  HMIPV: "Hospital Materno-Infantil Presidente Vargas",
  "Hospital de Pronto Socorro (HPS)":
    "Hospital de Pronto Socorro (Porto Alegre)",
  "Unidade de Coleta e Transfusão (UCT) do HPS":
    "Hospital de Pronto Socorro (Porto Alegre)",
  "Hospital Materno-Infantil Presidente Vargas (HMIPV)":
    "Hospital Materno-Infantil Presidente Vargas",
  "Unidade de Saúde Modelo": "Centro de Saúde Modelo",
  "Unidade de Saúde Santa Marta": "Centro de Saúde Santa Marta",
  "Centro de Atenção Psicossocial Álcool e Drogas (CAPS AD)":
    "Centros de Atenção Psicossocial Álcool e Drogas",

  "Tribunal de Contas do Estado do Rio Grande do Sul (TCE-RS)":
    "Tribunal de Contas do Estado do Rio Grande do Sul",
  "Sede do Tribunal de Contas do Estado (TCE)":
    "Tribunal de Contas do Estado do Rio Grande do Sul",
  "Teatro da Santa Casa": "Teatro da Santa Casa (Porto Alegre)",
  "Catedral Metropolitana de Porto Alegre (Matriz)":
    "Catedral Metropolitana de Porto Alegre",
  "Teatro do Sesc": "Teatro do Sesc (Porto Alegre)",
  "Palácio do Comércio": "Palácio do Comércio (Porto Alegre)",
  "Estação Rodoviária de Porto Alegre": "Rodoviária (Trensurb)",
  "Grêmio Sargento Expedicionário Geraldo Santana": "Grêmio Geraldo Santana",
  "Estádio Beira-rio": "Estádio Beira-Rio",
  "Ministério da Saúde": "Ministry of Health of Brazil",
  "Força Nacional do SUS": "Força Nacional do Sistema Único de Saúde",
  "Grupo Hospitalar Conceição (GHC)": "Grupo Hospitalar Conceição",
  "Casa dos Conselhos": "Casa dos Conselhos (Porto Alegre)",
  "Complexo Cultural Porto Seco": "Complexo Cultural do Porto Seco",
  "comportas do Muro da Mauá": "Mauá Wall floodgates",
  "Aeroporto Internacional Salgado Filho":
    "Salgado Filho International Airport",
  "Aeroporto Salgado Filho": "Salgado Filho International Airport",
  "Centro Popular de Compras (CPC)": "Centro Popular de Compras (Porto Alegre)",
  "Biblioteca Pública Josué Guimarães":
    "Biblioteca Pública Municipal Josué Guimarães",
  "CEEE Equatorial": "CEEE Grupo Equatorial",

  "Região Metropolitana": "Região Metropolitana de Porto Alegre",
  "4º Distrito": "4º Distrito (Porto Alegre)",
  "Quarto Distrito": "4º Distrito (Porto Alegre)",
  "Zona Norte": "Zona Norte (Porto Alegre)",
  "Zona Sul": "Zona Sul (Porto Alegre)",
  "Zona Leste": "Zona Leste (Porto Alegre)",
  "Arquipélago (Ilhas)": "Islands of Porto Alegre",
  "Bairro Auxiliadora": "Auxiliadora",
  "Bairro Azenha": "Azenha",
  "Bairro Bela Vista": "Bela Vista (Porto Alegre)",
  "Bairro Belém Novo": "Belém Novo",
  "Bairro Bom Fim": "Bom Fim",
  "Bairro Bom Jesus": "Bom Jesus (Porto Alegre)",
  "Bairro Camaquã": "Camaquã (Porto Alegre)",
  "Bairro Cavalhada": "Cavalhada (Porto Alegre)",
  "Bairro Centro Histórico": "Centro (Porto Alegre)",
  "Bairro Chapéu do Sol": "Chapéu do Sol",
  "Bairro Cidade Baixa": "Cidade Baixa (Porto Alegre)",
  "Bairro Cristal": "Cristal (Porto Alegre)",
  "Bairro Cruzeiro": "Cruzeiro (Porto Alegre)",
  "Bairro Glória": "Glória (Porto Alegre)",
  "Bairro Higienópolis": "Higienópolis (Porto Alegre)",
  "Bairro Hípica": "Hípica",
  "Bairro Humaitá": "Humaitá (Porto Alegre)",
  "Bairro Ipanema": "Ipanema (Porto Alegre)",
  "Bairro Jardim Itu-Sabará": "Jardim Itu-Sabará",
  "Bairro Lami": "Lami (Porto Alegre)",
  "Bairro Lomba do Pinheiro": "Lomba do Pinheiro",
  "Bairro Menino Deus": "Menino Deus (Porto Alegre)",
  "Bairro Moinhos de Vento": "Moinhos de Vento",
  "Bairro Navegantes": "Navegantes (Porto Alegre)",
  "Bairro Partenon": "Partenon (Porto Alegre)",
  "Bairro Petrópolis": "Petrópolis (Porto Alegre)",
  "Bairro Ponta Grossa": "Ponta Grossa (Porto Alegre)",
  "Bairro Praia de Belas": "Praia de Belas",
  "bairro Restinga": "Restinga (Porto Alegre)",
  "Bairro Restinga": "Restinga (Porto Alegre)",
  "Bairro São Geraldo": "São Geraldo (Porto Alegre)",
  "Bairro Santa Tereza": "Santa Tereza (Porto Alegre)",
  "Bairro Santo Antônio": "Santo Antônio (Porto Alegre)",
  "Bairro São João": "São João (Porto Alegre)",
  "Bairro Sarandi": "Sarandi (Porto Alegre)",
  "Bairro Teresópolis": "Teresópolis (Porto Alegre)",
  "Bairro Tristeza": "Tristeza (Porto Alegre)",
  "Bairro Vila Conceição": "Vila Conceição",
  "Bairro Vila Farrapos": "Vila Farrapos",
  Petrópolis: "Petrópolis (Porto Alegre)",
  Partenon: "Partenon (Porto Alegre)",
  Navegantes: "Navegantes (Porto Alegre)",
  Nonoai: "Nonoai (Porto Alegre)",
  "Vila Nova": "Vila Nova (Porto Alegre)",
  "Capital Gaúcha": "Porto Alegre",

  "Orla Moacyr Scliar": "Parque Moacyr Scliar",
  "Parque Urbano da Orla Moacyr Scliar": "Parque Moacyr Scliar",
  "Orla do Guaíba": "Parque da Orla do Guaíba",
  "Parque Farroupilha (Redenção)": "Parque da Redenção",
  "Pontal do Estaleiro": "Parque Pontal do Estaleiro",
  Guaíba: "Rio Guaíba in Porto Alegre",
  "Lago Guaíba": "Rio Guaíba in Porto Alegre",
  "Avenida Ipiranga": "Avenida Ipiranga (Porto Alegre)",
  "Avenida Castello Branco": "Avenida Presidente Castello Branco",
  "Av. Mauá": "Avenida Mauá",
  "Moab Caldas": "Avenida Moab Caldas",
  "Avenida Voluntários da Pátria": "Rua Voluntários da Pátria (Porto Alegre)",
  "Praça Revolução Farroupilha (Trensurb)": "Praça Revolução Farroupilha",
  "Praça Montevideo": "Praça Montevidéu",
  "Praça Marechal Deodoro (Matriz)": "Praça da Matriz (Porto Alegre)",
  "Praça da Alfândega": "Praça da Alfândega (Porto Alegre)",
  "Terminal Parobé": "Praça Pereira Parobé",
  "Viaduto Conceição": "Viaduto da Conceição",
  "Baronesa do Gravataí": "Rua Baronesa do Gravataí",
  "Trincheira da Ceará": "Trincheira da Avenida Ceará",

  "Exército Brasileiro": "Army of Brazil",
  "Forças Armadas": "Army of Brazil",
  "Marinha do Brasil": "Brazilian Navy",
  "Ministerio Público - RS": "Ministério Público do Rio Grande do Sul",
  "Governo Federal": "Federal government of Brazil",
  SESI: "Serviço Social da Indústria",
  Fecomércio: "Fecomércio-RS",
  "Comissão de Combate à Informalidade": "Fecomércio-RS",

  "Festival de Inverno": "Festival de Inverno (Porto Alegre)",

  "Brigada Militar": "Brigada Militar do Rio Grande do Sul",
  Trabalho: "Festa de Nossa Senhora do Trabalho",
  Metas: "Prometas",
  Unisinos: "Universidade do Vale do Rio dos Sinos (Porto Alegre campus)",
  "Caminhos Rurais": "Caminhos Rurais de Porto Alegre",
  "Parque Moinhos de Vento (Parcão)": "Parque Moinhos de Vento",
  "Cais do Porto": "Cais Mauá",
  Unesco: "UNESCO",
  "Fórum da Liberdade": "30º Fórum da Liberdade (2017)",
  Fiergs: "Federação das Indústrias do Estado do Rio Grande do Sul",
  "Jogos Abertos": "Jogos Abertos de Porto Alegre",
  "Jockey Club": "Jockey Club do Rio Grande do Sul",
  "Nivel do Guaíba": "Water level recorders",
  "Paróquia de São Jorge": "Procissão de São Jorge (Porto Alegre)",
  "Programa Nacional de Apoio à Gestão Administrativa e Fiscal dos Municípios Brasileiros (PNAFM).":
    "Programa Nacional de Apoio à Gestão Administrativa e Fiscal dos Municípios Brasileiros",
  "CETE - Centro Estadual de Treinamento Esportivo":
    "Centro Estadual de Treinamento Esportivo",
  "Cidades Educadoras": "Educating Cities",
  "Junta de Serviço Militar": "Juntas de Serviço Militar",
  "Polícia Rodoviária Federal (PRF)": "Polícia Rodoviária Federal",
  "Polícia Rodoviária Federal - PRF": "Polícia Rodoviária Federal",
  "Enchente Porto Alegre Maio de 2024": "2024 Porto Alegre floods",
  "Enchente Porto Alegre": "2024 Porto Alegre floods",
  "Corredor Humanitário":
    "Humanitarian aid for the 2024 Rio Grande do Sul floods",
  "Cadastro Único": "Cadastro Único para Programas Sociais",
  "Campanha Nacional de Vacinação contra Gripe (influenza)":
    "Campanha Nacional de Vacinação contra Gripe (Brazil)",
  "Agente de Combate às Endemias (ACE)": "Agentes de Combate às Endemias",

  Lazer: "Recreation in Porto Alegre",
  Teatro: "Theatre of Porto Alegre",
  Farmácia: "Farmácias Distritais (Porto Alegre)",
  Árvore: "Trees in Porto Alegre",
  Futebol: "Association football in Porto Alegre",
  roubo: "Crime in Porto Alegre",
  Habitação: "Housing in Porto Alegre",
  Ambulância: "Ambulances in Porto Alegre",
  Procissão: "Processions in Porto Alegre",
  Aéreas: "Aerial photographs of Porto Alegre",
  "Imagem Aérea": "Aerial photographs of Porto Alegre",
  Reciclagem: "Recycling in Porto Alegre",
  Táxi: "Taxis in Porto Alegre",
  Comércio: "Commerce in Porto Alegre",
  Infraestrutura: "Infrastructure in Porto Alegre",
  Dança: "Dance in Porto Alegre",
  Artesanato: "Handicrafts of Porto Alegre",
  exposição: "Exhibitions in Porto Alegre",
  Lixo: "Waste management in Porto Alegre",
  Escultura: "Sculptures in Porto Alegre",
  Alimentação: "Food of Porto Alegre",
  Alimento: "Food of Porto Alegre",
  Motocicleta: "Motorcycles in Porto Alegre",
  Bombeiros: "Firefighters of Porto Alegre",
  Cinema: "Cinema of Porto Alegre",
  Vandalismo: "Vandalism in Porto Alegre",
  Cavalo: "Horses of Porto Alegre",
  Chuva: "Rain in Porto Alegre",
  Coleta: "Waste collection in Porto Alegre",
  "remoção de lixo": "Waste collection in Porto Alegre",
  Desastres: "Disasters and accidents in Porto Alegre",
  eleições: "Elections in Porto Alegre",
  Incêndio: "Fires in Porto Alegre",
  Subprefeituras: "Subprefeituras of Porto Alegre",
  Dique: "Dams in Porto Alegre",
  Cachorro: "Dogs of Porto Alegre",
  CÃES: "Dogs of Porto Alegre",
  Coronavírus: "COVID-19 pandemic in Porto Alegre",
  "Covid-19": "COVID-19 pandemic in Porto Alegre",
  Mapa: "Maps of Porto Alegre",
  Ônibus: "Buses in Porto Alegre",
  Quilombos: "Quilombos in Porto Alegre",
  "Artes Cênicas": "Performing arts in Porto Alegre",
  "Transporte Público": "Public transport in Porto Alegre",
  "Assistência Social": "Social services in Porto Alegre",
  "Serviço Social": "Social services in Porto Alegre",
  "População de Rua": "Homelessness in Porto Alegre",
  "Situação de rua": "Homelessness in Porto Alegre",
  "Ruas e avenidas": "Streets in Porto Alegre",
  "Livro e Literatura": "Literature of Porto Alegre",
  "Artes Visuais": "Art of Porto Alegre",
  "Indústria e Comércio": "Industry in Porto Alegre",
  "Fios Soltos": "Overhead power lines in Porto Alegre",
  "Unidade de Saúde": "Unidades de Saúde in Porto Alegre",
  "foco de lixo": "Waste management in Porto Alegre",
  "Terminais de ônibus": "Bus stations in Porto Alegre",

  Infográfico: "Information graphics of Brazil",
  Dengue: "Dengue in Brazil",
  Vôlei: "Volleyball in Brazil",
  Handebol: "Handball in Brazil",
  Campeonato: "Competitions in Brazil",
  Concurso: "Competitions in Brazil",
  Posse: "Oaths of office in Brazil",
  Servidor: "Civil servants of Brazil",
  Espetáculo: "Shows in Rio Grande do Sul",
  Aluno: "Students in Brazil",
  Alunos: "Students in Brazil",
  Abertura: "Opening ceremonies in Brazil",
  Inauguração: "Inaugurations in Brazil",
  Licitações: "Auctions in Brazil",
  Abrigos: "Shelters in Brazil",
  Albergues: "Shelters in Brazil",
  Acolhimento: "Shelters in Brazil",
  Transparência: "Open government in Brazil",
  Acessibilidade: "Accessibility in Brazil",
  Empreendedorismo: "Entrepreneurship in Brazil",
  Adolescente: "Teenagers of Brazil",
  Poda: "Pruning in Brazil",
  Embaixada: "Embassies in Brazil",
  Consulado: "Diplomatic missions to Brazil",
  "Consul Honorária dos Países Baixos em Porto Alegre":
    "Diplomatic missions to Brazil",
  Juventude: "Youth in Brazil",
  Eclipse: "Solar eclipses in Brazil",
  Gato: "Cats of Brazil",
  Ambulantes: "Street vendors in Brazil",
  Gripe: "Influenza vaccination in Brazil",
  Ginástica: "Gymnastics in Brazil",
  Tecnologia: "Technology in Brazil",
  Páscoa: "Easter in Brazil",
  Pedestre: "Pedestrians in Brazil",
  Resgate: "Search and rescue in Brazil",
  Trilha: "Trails in Brazil",
  Medicina: "Medicine in Brazil",
  Voluntariado: "Volunteering in Brazil",
  Drone: "Unmanned aerial vehicles in Brazil",
  gari: "Street sweepers from Brazil",
  Abastecimento: "Logistics in Brazil",
  Limpeza: "Cleaning in Brazil",
  Escolta: "Police escorts in Brazil",
  "febre amarela": "Yellow fever in Brazil",
  "Comissão da Pessoa com Deficiência": "Disability in Brazil",
  "Bloqueio químico": "Fogging against Aedes aegypti in Brazil",
  "Vigilância de Alimentos": "Food security in Brazil",
  "Direitos Humanos": "Human rights in Brazil",
  "Artes Plásticas": "Visual arts of Brazil",
  "Educação Ambiental": "Environmental education in Brazil",
  "Ação Social": "Social work in Brazil",
  "Plano Diretor": "Urban planning in Brazil",
  "Medicina Veterinária": "Veterinary medicine in Brazil",
  "Iluminação Pública": "Street lights in Brazil",
  "vacina contra a Dengue": "Dengue vaccine in Brazil",
  "troféu Prefeito Inovador": "Awards of Brazil",
  "Profissionais de Saúde": "People of Brazil in health professions",
  "Saúde Mental": "Mental health in Brazil",
  "Placa de veículos": "License plates of Brazil",
  "Tratamento de água": "Water treatment in Brazil",
  "lavagem de vias e pontos": "Street cleaning in Brazil",
  "caminhões-pipa": "Tank trucks in Brazil",
  "Porão do Paço": "Basements in Brazil",
  "doação de sangue": "Blood donation in Brazil",
  "Ambulatório Odontológico": "Dental clinics in Brazil",

  "Dia da Mulher": metadata =>
    `International Women's Day in ${getYear(
      metadata.humanReadableDate
    )} in Brazil`,
  Criança: metadata =>
    `Children of Brazil in ${getYear(metadata.humanReadableDate)}`,
  "Programação do Reveillon": metadata =>
    `New Year ${getYear(metadata.humanReadableDate)} in Brazil`,
  "Concerto Musical": metadata =>
    `${getYear(metadata.humanReadableDate)} concerts in Brazil`,

  Transexualidade: "Transgender in South America",

  Palestra: "Presentations",
  Oficina: "Workshops (meetings)",
  "síndrome de down": "Down syndrome",
  Investigação: "Inquiry",
  Microcefalia: "Microcephaly",
  Consultório: "Medical offices",
  "Educação Infantil": "Educating children",
  "Doenças da Pele": "Dermatitis",
  "Educação no Trânsito": "Road safety education",
  "Educação Fundamental": "Primary education",
  "Educação Básica": "Primary education",
  "Alteração de vias": "Road traffic management",
  "Transtornos no trânsito": "Road traffic management",
  "desvio de trânsito": "Road traffic management",
  "Consulta Pública": "Public consultation",
  Seminário: "Seminars",
  Capina: "Weed control",
  Campanha: "Campaigns",
  Mutirão: "Task forces",
  "Força-Tarefa": "Task forces",
  "Adoção de animais": "Animal adoption",
  "Educação Especial": "Special education",
  "Carnaval de Rua": "Street carnival",
  Cidadania: "Civil society",
  Debate: "Debating",
  Interdição: "Forced business closures",
  "Material Escolar": "School supplies",
  "Inclusão Social": "Social inclusion",
  Urbanismo: "Urbanism",
  Mulher: "Gender equality",
  Audiência: "Audiences (meeting)",
  Medicamentos: "Pharmaceutical drugs",
  Sangue: "Blood collection",
  Caminhada: "Walks (event)",
  "Resíduos Sólidos": "Solid waste management",
  "Bloqueio no trânsito": "Closed roads",
  Apreensão: "Confiscation",
  "Ação Integrada": "Community-driven programs",
  "Educação Técnica": "Career and technical education",
  "Saúde Bucal": "Oral health",
  Apresentação: "Presentations",
  Convite: "Invitations",
  Lançamento: "Product launches",
  Pavimentação: "Road paving",
  Flashmob: "Flash mobs",
  CMDUA: "Urban development",
  "Trabalho e Emprego": "Employment",
  "Vagas de Emprego": "Employment",
  "Centro de triagem": "Screening centers",
  Monitoramento: "Monitoring",
  Premiação: "Prizes",
  "Cidades Inteligentes": "Smart cities",
  "Câncer Bucal": "Oral cancer",
  Nutrição: "Nutrition",
  "Saúde Nutricional e Amamentação": "Breastfeeding",
  Live: "Video streaming",
  "Atenção Primária à Saúde (APS)": "Primary health care",
  Mãe: "Maternal health",
  Desabrigados: "Displaced persons",
  "Primeiros Socorros": "First aid",
  "Clínica da Família": "Family medicine",
  "Agentes Comunitários de Saúde (ACS)": "Community health agents",
  "Saúde do Idoso": "Elderlycare",
  "Banco de Sangue": "Blood banks",
  "Declaração de Edimburgo": "Collective agreements",
  "Novo Marco Global": "Biodiversity",
  Assinatura: "Signing ceremonies",
  Certificado: "School certificates",
  Homenagem: "Homages to people",
  "doação e transplante de órgãos": "Organ donation",
  "Inspeção veicular": "Vehicle inspection",
  "Educação Permanente": "Professional development and training",
  "Agentes de Fiscalização": "Inspectors",
  Conscientização: "Awareness activism",
};
