export const validTags = [
  "(EBAB) Moinhos de Vento",
  "(Emei JP) Cantinho Amigo",
  "#eufaçopoa",
  "4º Distrito",

  "A Cara da Obra",
  "Abastecimento",
  "Abertura",
  "ABRH",
  "Abrigo de Animais da EPTC",
  "Abrigos",
  "Ação Integrada",
  "Ação Rua",
  "Ação Social",
  "Acessibilidade",
  "Acidente",
  "Acolhimento",
  "Administração",
  "Administração e Patrimônio",
  "Administração É Patrimônio",
  "Adoção de animais",
  "Adolescente",
  "Aeronáutica",
  "Aeroporto Internacional Salgado Filho",
  "Aeroporto Salgado Filho",
  "Agente de Combate às Endemias (ACE)",
  "Agentes Comunitários de Saúde (ACS)",
  "Agentes de Fiscalização",
  "Agentes de Trânsito",
  "Água",
  "Água e Esgoto",
  "Água e Esgotos",
  "Aids",
  "Alagamento",
  "Albergues",
  "Álcool  e Outras Drogas",
  "Aldeia Indígena",
  "Aleitamento materno",
  "Alimentação",
  "Alimento",
  "Aluno",
  "Alunos",
  "Alvará",
  "Amamentação",
  "Ambulância",
  "Ambulantes",
  "Ambulatório Odontológico",
  "Aniversário",
  "Aplicativo 156+POA",
  "Aplicativo (app)",
  "Apreensão",
  "Apresentação",
  "Arena do Grêmio",
  "Arquipélago (Ilhas)",
  "Arquivo",
  "Arquivo Histórico Moysés Vellinho",
  "Arroio Dilúvio",
  "Arroio Sarandi",
  "Arte Urbana",
  "Artes Cênicas",
  "Artes Plásticas",
  "Artes Visuais",
  "Árvore",
  "Asfalto",
  "Asilo Padre Cacique",
  "Assinatura",
  "Assistência Farmacêutica",
  "Assistência Hospitalar",
  "Assistência Social",
  "Associação dos Auditores Fiscais da Receita Municipal de Porto Alegre (Aiamu)",
  "Atenção Primária à Saúde (APS)",
  "Atendimento Improvisado",
  "Atendimento",
  "Atletismo",
  "Audiência",
  "Auditório Araújo Vianna",
  "Aula aberta",
  "Av. Mauá",
  "Avenida Assis Brasil",
  "Avenida Castello Branco",
  "Avenida Coronel Marcos",
  "Avenida Ipiranga",
  "Avenida Padre Cacique",
  "Avenida Severo Dullius",
  "Avenida Voluntários da Pátria",

  "Bairro Anchieta",
  "Bairro Azenha",
  "Bairro Belém Novo",
  "Bairro Bom Jesus",
  "Bairro Campo Novo",
  "Bairro Cavalhada",
  "Bairro Centro Histórico",
  "Bairro Cidade Baixa",
  "Bairro Cristal",
  "Bairro Cruzeiro",
  "Bairro Farrapos",
  "Bairro Floresta",
  "Bairro Glória",
  "Bairro Hípica",
  "Bairro Humaitá",
  "Bairro Ipanema",
  "Bairro Jardim Carvalho",
  "Bairro Lami",
  "Bairro Lomba do Pinheiro",
  "Bairro Mário Quintana",
  "Bairro Medianeira",
  "Bairro Menino Deus",
  "Bairro Moinhos de Vento",
  "Bairro Navegantes",
  "Bairro Partenon",
  "Bairro Ponta Grossa",
  "Bairro Praia de Belas",
  "bairro Restinga",
  "Bairro Restinga",
  "Bairro Rubem Berta",
  "Bairro São Geraldo",
  "Bairro São José",
  "Bairro Santa Tereza",
  "Bairro Santo Antônio",
  "Bairro Sarandi",
  "Bairro Vila Farrapos",
  "Banco de Leite Humano",
  "Banco de Sangue",
  "Banda Municipal",
  "Baronesa do Gravataí",
  "Bicicleta",
  "Blitz",
  "Bocha",
  "Bombeiros",
  "Brechó",
  "Brechocão",
  "Brigada Militar",
  "Brique da Redenção",

  "Cachorro",
  "Cadastro Único",
  "CÃES",
  "Cais Mauá",
  "Câmara Municipal de Porto Alegre (CMPA)",
  "Caminhada",
  "caminhões-pipa",
  "Campanha",
  "Campanha do Agasalho",
  "Campanha Nacional de Vacinação contra Gripe (influenza)",
  "Campeonato",
  "Câncer",
  "Câncer Bucal",
  "Câncer de Mama",
  "Capacitação",
  "Capester",
  "Capina",
  "Capital Gaúcha",
  "Carnaval",
  "Carnaval 2017",
  "Carris",
  "Carro",
  "Casa de Bombas",
  "Casa dos Conselhos",
  "Catamarã",
  "Catedral Metropolitana de Porto Alegre (Matriz)",
  "Causa Animal",
  "Cavalo",
  "CEEE Equatorial",
  "CEIC",
  "Cel QOEM Mário Yukio Ikeda",
  "Cel. Evaldo Rodrigues Oliveira",
  "Centro Administrativo Municipal (CAM)",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural Usina do Gasômetro",
  "Centro de Atenção Psicossocial Álcool e Drogas (CAPS AD)",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Referência em Saúde do Trabalhador (Cerest)",
  "Centro de Saúde Modelo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro de triagem",
  "Centro Histórico",
  "Centro Humanístico Vida",
  "Centro Integrado de Comando",
  "Centro Integrado de Comando da Cidade de Porto Alegre (CEIC)",
  "Centro Popular de Compras (CPC)",
  "Cerimônia",
  "Certificado",
  "CETE - Centro Estadual de Treinamento Esportivo",
  "CGVS",
  "Chuva",
  "Ciclovia",
  "Cidadania",
  "Cidades Educadoras",
  "Cinemateca Capitólio",
  "Circulação",
  "Circulação e Transporte",
  "Clínica da Família",
  "CMDUA",
  "Colégio Militar de Porto Alegre",
  "Coleta",
  "Coleta Seletiva",
  "Coletiva de Imprensa",
  "Colônia de Pescadores Z5",
  "Comandante da Guarda Municipal, Marcelo Nascimento",
  "Comando Militar do Sul",
  "Comércio",
  "Comissão Permanente de Atuação em Emergências (Copae)",
  "Companhia Carris Porto Alegrense",
  "Companhia de Processamento de Dados do Município (Procempa)",
  "Companhia Municipal de Dança",
  "Complexo Cultural Porto Seco",
  "Complexo Hospitalar Santa Casa",
  "comportas do Muro da Mauá",
  "Compostagem",
  "Computador",
  "COMTU",
  "Comunicação Social",
  "Conaf",
  "Concerto Musical",
  "Conferência",
  "Conscientização",
  "Conselho do OP",
  "Conselho Municipal de Saúde",
  "Conselhos Municipais",
  "Consul Honorária dos Países Baixos em Porto Alegre",
  "Consulado",
  "Consultório na Rua",
  "Consumidor",
  "Controladoria",
  "Convênio",
  "Coordenação de Operações Especiais (COE)",
  "Coordenação Municipal de Urgências (CMU)",
  "Coordenações",
  "Cootravipa",
  "Coronavírus",
  "Corredor Humanitário",
  "Corrida",
  "Covid-19",
  "Criança",
  "Cruz Vermelha do Brasil",
  "Cultura",
  "Cultura e Economia Criativa",
  "Curso",
  "Curso de Formação",

  "Dança",
  "Debate",
  "Declaração de Edimburgo",
  "Defesa Civil",
  "Dengue",
  "Departamento Municipal de Água e Esgotos (DMAE)",
  "Departamento Municipal de Habitação (Demhab)",
  "Departamento Municipal de Limpeza Urbana (DMLU)",
  "Desabrigados",
  "Desastres",
  "Desenvolvimento Econômico",
  "Desenvolvimento Social",
  "Deslizamento",
  "desvio de trânsito",
  "Dia D de Vacinação",
  "Dia do Gari",
  "Dique",
  "Direito do Consumidor",
  "Direitos Animais",
  "Direitos dos Animais",
  "Direitos Humanos",
  "diretor-presidente do DMAE, Maurício Loss",
  "Diretoria de Vigilância em Saúde (DVS)",
  "Diversidade sexual",
  "Dmae",
  "DMAE",
  "DMAP",
  "Dmlu",
  "DMLU",
  "Doação",
  "doação de sangue",
  "doação e transplante de órgãos",
  "doações de cestas básicas",
  "Doença Respiratória",
  "Dragagem",
  "Drone",

  "Ecobarreira",
  "Edifício Intendente José Montaury",
  "Educação",
  "Educação Ambiental",
  "Educação Básica",
  "Educação Fundamental",
  "Educação Infantil",
  "Educação no Trânsito",
  "Educação Permanente",
  "Eixo Baltazar",
  "eleições",
  "Embratel",
  "Emeb Liberato Salzano Vieira da Cunha",
  "EMEF",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "EMEF Vereador Antônio Giúdice",
  "EMEI",
  "EMEI Dom Luiz de Nadal",
  "Emei Ilha da Pintada",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "EMEM",
  "Empreendedorismo",
  "Empresa Pública de Transporte e Circulação (EPTC)",
  "Encerramento",
  "Enchente",
  "Enchente Porto Alegre",
  "Enchente Porto Alegre Maio de 2024",
  "Ensino",
  "Entrega de Doações",
  "Entrevista Coletiva",
  "Eptc",
  "EPTC",
  "Equipe de Manejo Arbóreo (EMA)",
  "Equipe de Vigilância de Alimentos da SMS",
  "Equipe de Vigilância em Saúde Ambiental e Águas (EVSAA)",
  "Escola",
  "Escola de Gestão Pública (EGP)",
  "Escolas Municipais de Educação Infantil",
  "Escolta",
  "Escultura",
  "Esgoto",
  "Espetáculo",
  "Esporte",
  "Esporte, Lazer e Juventude",
  "Esporte Lazer e Juventude",
  "Estação de Bombeamento de Águas Pluviais (Ebap)",
  "Estação Rodoviária de Porto Alegre",
  "Estações de Bombeamento de Águas Pluviais (Ebaps)",
  "Estádio Beira-rio",
  "Estrada das Furnas",
  "Estudantes",
  "ETA",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Exame médico",
  "Executivo",
  "Exército Brasileiro",
  "exposição",
  "Extremo Sul",

  "Famurs",
  "Farmácia Distrital Modelo",
  "Farmácia Móvel",
  "Fasc",
  "Fazenda",
  "Fecomércio",
  "Festejos",
  "Festival",
  "Festival de Inverno",
  "Fiergs",
  "Finanças",
  "Finanças Públicas",
  "Fios Soltos",
  "Fique Sabendo Jovem",
  "Fiscalização",
  "Flagrante",
  "foco de lixo",
  "Força Nacional do SUS",
  "Força-Tarefa",
  "Forças Armadas",
  "Fórum",
  "Fórum Social Mundial da População Idosa",
  "Fotografia",
  "Fundação de Assistência Social e Cidadania – Fasc",
  "Fundação Iberê Camargo",
  "Futebol",
  "Futebol Feminino",

  "Gabinete",
  "Gabinete da Causa Animal (GCA)",
  "Gabinete de Inovação (GI)",
  "Gabinete do Prefeito",
  "Gabinete Prefeito",
  "gari",
  "Gato",
  "GeraçãoPoa",
  "GeraEncontro",
  "Ginástica",
  "Governador",
  "Governador Eduardo Leite",
  "Governacia Local e Coordenação Politica",
  "Governança",
  "Governança Local e Coordenação Política",
  "Governança Local e Coordenação Política.",
  "Governo Federal",
  "Gp",
  "Grêmio Foot-Ball Porto Alegrense",
  "Grêmio Sargento Expedicionário Geraldo Santana",
  "Greve",
  "Gripe",
  "Grupo Hospitalar Conceição (GHC)",
  "Guaíba",
  "Guarda Municipal",

  "Habitação",
  "Habitação Regularização Fundiária",
  "Habitação e Regularização Fundiária",
  "Hamilton Sossmeier",
  "Homenagem",
  "Hospital de campanha",
  "Hospital de Pronto Socorro (HPS)",
  "Hospital Materno-Infantil Presidente Vargas (HMIPV)",

  "Idosos",
  "Igreja Nossa Senhora das Dores",
  "Ilha da Pintada",
  "Ilha dos Marinheiros",
  "Iluminação Pública",
  "Imagem Aérea",
  "Imposto",
  "Inauguração",
  "Incêndio",
  "Inclusão Social",
  "Indústria",
  "Infecções Sexualmente Transmissíveis (IST)",
  "Infraestrutura e Mobilidade",
  "Infraestrutura e Mobilidade Urbana",
  "Inovação",
  "Inspeção veicular",
  "Instituto Caldeira",
  "Instituto Ling",
  "Interdição",
  "Internet",

  "Jockey Club",
  "Jogos Abertos",
  "Junta de Serviço Militar",
  "Justiça",
  "Juventude",

  "Lago Guaíba",
  "Lançamento",
  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "lavagem de vias e pontos",
  "Lei Orçamentária Anual (LOA)",
  "Leishmaniose",
  "LGBT",
  "Limpeza",
  "Limpeza Urbana",
  "Linha Turismo",
  "Live",
  "Livro e Literatura",
  "Lixo",
  "Lomba do Pinheiro",

  "Mãe",
  "Maio Vermelho",
  "Manutenção",
  "Mapa",
  "Maratona",
  "Maria de Fátima Záchia Paludo",
  "Marinha do Brasil",
  "Mauro Pinheiro",
  "MEC",
  "Medicamentos",
  "Medicina",
  "Medicina Veterinária",
  "Meio Ambiente",
  "Meio Ambiente e Sustentabilidade",
  "Meio Ambiente, Urbanismo e Sustentabilidade",
  "Memória",
  "Menino Deus",
  "Mercado Público",
  "Mercado Público Central",
  "Metas",
  "Ministério da Saúde",
  "Ministerio Público - RS",
  "Mobilidade Urbana",
  "Moinhos de Vento",
  "Monitoramento",
  "Morro Ricaldone",
  "Motocicleta",
  "Mulher",
  "multivacinação",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Música",
  "Mutirão",

  "Natal dos Encantos",
  "Nivel do Guaíba",
  "Novo Marco Global",
  "Núcleo de Imunizações DVS (NI)",
  "Nutrição",

  "Obras",
  "Obras e Infraestrutura",
  "OdontoSesc",
  "Oficina",
  "Ônibus",
  "OP",
  "Operação Inverno",
  "Orçamento Participativo",
  "Orla de Ipanema",
  "Orla do Guaíba",
  "Orla Moacyr Scliar",

  "Paço dos Açorianos",
  "Paço Municipal de Porto Alegre",
  "Palácio do Comércio",
  "Palestra",
  "Parcerias",
  "Parcerias Estratégicas",
  "Paróquia de São Jorge",
  "Parque Chico Mendes",
  "Parque Farroupilha (Redenção)",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Natural Municipal Morro do Osso",
  "Parque Urbano da Orla Moacyr Scliar",
  "Pavimentação",
  "Pedestre",
  "Pedestre Idoso",
  "Petrópolis",
  "PGM",
  "Pinacoteca Aldo Locatelli",
  "Pinacoteca Ruben Berta",
  "Placa de veículos",
  "Planejamento e Assuntos Estratégicos",
  "Planejamento e Gestão",
  "Plataforma Reconstruir Porto Alegre",
  "Plano de ação Porto Alegre Forte",
  "Plano Diretor",
  "Plaza São Rafael",
  "PoaHub",
  "Poda",
  "Polícia Rodoviária Federal",
  "Polícia Rodoviária Federal (PRF)",
  "Polícia Rodoviária Federal - PRF",
  "Pontal do Estaleiro",
  "Pontifícia Universidade Católica do RS (PUCRS)",
  "População de Rua",
  "Porão do Paço",
  "Porto Alegre",
  "Posse",
  "PPA",
  "Praça da Alfândega",
  "Praça Doutor Lopes Trovão",
  "Praça Marechal Deodoro (Matriz)",
  "Praça Montevideo",
  "Praças e Parques",
  "Praia de Belas",
  "Prédio público",
  "Prédios e Edificações",
  "Prefeito",
  "Prefeito de Porto Alegre, Sebastião Melo",
  "Prefeitura de Porto Alegre",
  "Prefeitura nos Bairros",
  "Prefeitura Nos Bairros",
  "Premiação",
  "Presidente",
  "Presidente da Câmara Municipal de Vereadores,  Idenir Cecchim",
  "Presidente da Companhia de Processamentos de Dados do Município de Porto Alegre, Leticia Batistela",
  "presidente da Fundação de Assistência Social e Cidadania (FASC), Cristiano Roratto",
  "Presidente da República Luiz Inácio Lula da Silva",
  "Prevenção",
  "Previdência",
  "Previsão do Tempo",
  "Primeiros Socorros",
  "Procempa",
  "Procissão",
  "Procon",
  "Procon Móvel",
  "Procon Municipal",
  "Procurador geral do município de Porto Alegre, Roberto Silva da Rocha",
  "Procuradoria",
  "Procuradoria-Geral do Município de Porto Alegre",
  "Profissionais de Saúde",
  "Programa de Residência Técnico-Superior (PRTS)",
  "Programação do Reveillon",
  "Projeto de Lei",
  "Projeto Pescar",
  "Prometas",
  "PUCRS",

  "Quadras de Beach Tennis",
  "Quarto Distrito",
  "Quilombos",

  "Ramiro Rosário",
  "Reciclagem",
  "Rede Calabria",
  "Rede de abastecimento de água",
  "Rede Municipal de Ensino",
  "redes de água",
  "Região Metropolitana",
  "Relações Institucionais",
  "remoção de lixo",
  "Resgate",
  "Resíduos Sólidos",
  "Resiliência",
  "Restauração",
  "Restaurante Popular",
  "Retirada de Passarela",
  "Reunião",
  "Revitalização",
  "ROMU",
  "roubo",
  "Rua José Pedro Boessio",
  "Ruas e avenidas",

  "Sala Álvaro Moreyra",
  "Sala dos Embaixadores",
  "Sala P. F. Gastal",
  "Salão Nobre",
  "Salão Nobre do Paço Municipal",
  "sanção de Projeto de Lei",
  "Sangue",
  "Santander",
  "Saúde",
  "Saúde Bucal",
  "Saúde do Idoso",
  "Saúde do Trabalhador",
  "Saúde Mental",
  "Saúde Nutricional e Amamentação",
  "Sebrae",
  "Secretaria Extraordinária do Trabalho e da Qualificação Profissional (SMTQ)",
  "Secretaria Municipal de Administração e Patrimônio (SMAP)",
  "Secretaria Municipal de Cultura e Economia Criativa (SMCEC)",
  "Secretaria Municipal de Desenvolvimento Econômico e Turismo (SMDET)",
  "Secretaria Municipal de Desenvolvimento Social (SMDS)",
  "Secretária municipal da Educação (SMED)",
  "Secretaria Municipal de Educação (SMED)",
  "Secretaria Municipal de Esporte, Lazer e Juventude (SMELJ)",
  "Secretaria Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretaria Municipal de Habitação e Regularização Fundiária (SMHARF)",
  "Secretária municipal de Habitação e Regularização Fundiária, Simone Somensi",
  "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (SMAMUS)",
  "Secretaria Municipal de Mobilidade Urbana (SMMU)",
  "Secretaria Municipal de Obras e Infraestrutura (SMOI)",
  "Secretaria Municipal de Parcerias (SMP)",
  "Secretaria Municipal de Planejamento e Assuntos Estratégicos (SMPAE)",
  "Secretaria Municipal de Saúde (SMS)",
  "Secretaria Municipal de Segurança (SMSEG)",
  "Secretaria Municipal de Serviços Urbanos (SMSURB)",
  "Secretaria Municipal de Transparência e Controladoria (SMTC)",
  "Secretariado",
  "Secretário Municipal da Educação (SMED)",
  "Secretário municipal da Fazenda, Rodrigo Fantinel",
  "Secretário Municipal da Saúde (SMS)",
  "Secretário Municipal da Saúde (SMS), Fernando Ritter",
  "Secretário Municipal de Administração e Patrimônio (SMAP)",
  "Secretário municipal de Administração e Patrimônio, André Barbosa",
  "Secretário municipal de Desenvolvimento Social, Leo Voigt",
  "Secretário Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretário municipal de Obras e Infraestrutura, André Flores",
  "Secretário municipal de Planejamento e Assuntos Estratégicos, Cezar Schirmer",
  "Secretário municipal do Gabinete de Inovação, Luiz Carlos Pinto da Silva Filho",
  "Secretário municipal do Meio Ambiente, Urbanismo e Sustentabilidade, Germano Bremm",
  "Sede do Tribunal de Contas do Estado (TCE)",
  "Segurança",
  "Segurança Publica",
  "Segurança Pública",
  "Semana de Porto Alegre",
  "Semana Farroupilha",
  "Seminário",
  "Senac",
  "Serviço de Atendimento Móvel de Urgência (SAMU)",
  "Serviço Social",
  "Serviços Urbanos",
  "Servidor",
  "Sesc",
  "SESI",
  "Shopping Total",
  "Sinalização de trânsito",
  "Sindicato dos Municipários de Porto Alegre (Simpa)",
  "Sindilojas",
  "Sine Municipal",
  "Sistema Único de Saúde (SUS)",
  "Situação de rua",
  "SMED",
  "Smpg",
  "SMSEG - Segurança",
  "Smic",
  "Smim",
  "Sms",
  "Sol",
  "Solidariedade",
  "Sport Club Internacional",
  "Subprefeituras",
  "Sustentabilidade",

  "Tapa Buracos",
  "Tarifa",
  "Táxi",
  "Teatro",
  "Teatro Renascença",
  "Tecnologia",
  "Tempo",
  "Temporal",
  "Tenda",
  "Terminais de ônibus",
  "Terminal Parobé",
  "Terreno",
  "Teste do Pezinho",
  "TJ-RS",
  "Trabalho e Emprego",
  "Trabalho e Qualificação",
  "Transexualidade",
  "trânsito",
  "Trânsito e Circulação",
  "Transparência",
  "Transparência e Controladoria",
  "Transporte",
  "Transporte e Circulação",
  "Transporte Público",
  "Transtornos no trânsito",
  "Tratamento de água",
  "Trensurb",
  "Tribunal de Contas do Estado do Rio Grande do Sul (TCE-RS)",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Trilha",
  "Trincheira da Ceará",
  "Tristeza",
  "troféu Prefeito Inovador",
  "Túnel da Conceição",
  "Turismo",

  "Unidade de Coleta e Transfusão (UCT) do HPS",
  "Unidade de Pronto Atendimento (UPA)",
  "Unidade de Saúde",
  "Unidade de Saúde Animal Victória (Usav)",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Modelo",
  "Unidade de Saúde Santa Marta",
  "Unidade de Saúde São Carlos",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "Unisinos",
  "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)",
  "Universidade Federal do Rio Grande do Sul (UFRGS)",
  "UPA Moacyr Scliar",
  "Urbanismo",
  "Usina do Gasômetro",

  "Vacina",
  "vacina contra a Dengue",
  "Vacinação",
  "Vagas de Emprego",
  "Vandalismo",
  "Varejo",
  "veículo",
  "Veículos",
  "vereador",
  "Viaduto Conceição",
  "Viaduto da Conceição",
  "Viagem à Brasília",
  "Vice-governador Gabriel Souza",
  "Vice-prefeito",
  "Vice-prefeito de Porto Alegre, Ricardo Gomes",
  "vice-prefeito Ricardo Gomes",
  "Vigidesastres",
  "Vigilância de Alimentos",
  "Vigilância em Saúde",
  "Vila dos Ferroviários",
  "Vila Ipiranga",
  "Vila Nova",
  "Visita",
  "Visita de Cortesia",
  "Vistoria",
  "Vítimas",
  "Vôlei",
  "Voluntariado",

  "WhatsApp",

  "Zona Leste",
  "Zona Norte",
  "Zona Sul",
];
