export const validTags = [
  "(EBAB) Moinhos de Vento",
  "(Emei JP) Cantinho Amigo",
  "4º Distrito",
  "Abastecimento",
  "Abrigos",
  "Acolhimento",
  "Adoção de animais",
  "Aeroporto Internacional Salgado Filho",
  "Aeroporto Salgado Filho",
  "Administração e Patrimônio",
  "Agente de Combate às Endemias (ACE)",
  "Agentes Comunitários de Saúde (ACS)",
  "Agentes de Trânsito",
  "Água",
  "Alagamento",
  "Alimentação",
  "Alimento",
  "Aplicativo 156+POA",
  "Aplicativo (app)",
  "Arena do Grêmio",
  "Arquipélago (Ilhas)",
  "Asilo Padre Cacique",
  "Assistência Farmacêutica",
  "Assistência Hospitalar",
  "Associação dos Auditores Fiscais da Receita Municipal de Porto Alegre (Aiamu)",
  "Atenção Primária à Saúde (APS)",
  "Atendimento Improvisado",
  "Atendimento",
  "Av. Mauá",
  "Avenida Assis Brasil",
  "Avenida Castello Branco",
  "Avenida Coronel Marcos",
  "Avenida Ipiranga",
  "Avenida Padre Cacique",

  "Bairro Azenha",
  "Bairro Cavalhada",
  "Bairro Centro Histórico",
  "Bairro Cidade Baixa",
  "Bairro Cristal",
  "Bairro Cruzeiro",
  "Bairro Glória",
  "Bairro Humaitá",
  "Bairro Ipanema",
  "Bairro Lami",
  "Bairro Lomba do Pinheiro",
  "Bairro Menino Deus",
  "Bairro Moinhos de Vento",
  "Bairro Partenon",
  "Bairro Ponta Grossa",
  "Bairro Praia de Belas",
  "bairro Restinga",
  "Bairro São Geraldo",
  "Bairro Santa Tereza",
  "Bairro Santo Antônio",
  "Bairro Sarandi",
  "Baronesa do Gravataí",
  "Brigada Militar",

  "Cachorro",
  "Cadastro Único",
  "CÃES",
  "Cais Mauá",
  "caminhões-pipa",
  "Campanha Nacional de Vacinação contra Gripe (influenza)",
  "Câncer Bucal",
  "Capacitação",
  "Capital Gaúcha",
  "Casa de Bombas",
  "Casa dos Conselhos",
  "Causa Animal",
  "Cavalo",
  "Cel QOEM Mário Yukio Ikeda",
  "Cel. Evaldo Rodrigues Oliveira",
  "Centro Administrativo Municipal (CAM)",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro Humanístico Vida",
  "Centro Integrado de Comando da Cidade de Porto Alegre (CEIC)",
  "Centro Popular de Compras (CPC)",
  "CETE - Centro Estadual de Treinamento Esportivo",
  "Chuva",
  "Cidades Educadoras",
  "Clínica da Família",
  "Coleta",
  "Coletiva de Imprensa",
  "Colônia de Pescadores Z5",
  "Comandante da Guarda Municipal, Marcelo Nascimento",
  "Comando Militar do Sul",
  "Companhia de Processamento de Dados do Município (Procempa)",
  "Complexo Cultural Porto Seco",
  "comportas do Muro da Mauá",
  "Comunicação Social",
  "Conselho do OP",
  "Consultório na Rua",
  "Coordenação de Operações Especiais (COE)",
  "Cootravipa",
  "Coordenação Municipal de Urgências (CMU)",
  "Coronavírus",
  "Corredor Humanitário",
  "Covid-19",
  "Cultura e Economia Criativa",
  "Curso de Formação",

  "Defesa Civil",
  "Dengue",
  "Departamento Municipal de Água e Esgotos (DMAE)",
  "Departamento Municipal de Habitação (Demhab)",
  "Departamento Municipal de Limpeza Urbana (DMLU)",
  "Desabrigados",
  "Desastres",
  "Desenvolvimento Social",
  "desvio de trânsito",
  "Dia do Gari",
  "Dique",
  "diretor-presidente do DMAE, Maurício Loss",
  "Diretoria de Vigilância em Saúde (DVS)",
  "Dmae",
  "DMAE",
  "DMLU",
  "doações de cestas básicas",
  "Drone",

  "Educação",
  "Eixo Baltazar",
  "eleições",
  "Emeb Liberato Salzano Vieira da Cunha",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "EMEF Vereador Antônio Giúdice",
  "EMEI",
  "EMEI Miguel Granato Velasquez",
  "Empresa Pública de Transporte e Circulação (EPTC)",
  "Enchente",
  "Enchente Porto Alegre",
  "Enchente Porto Alegre Maio de 2024",
  "Entrega de Doações",
  "Entrevista Coletiva",
  "Eptc",
  "EPTC",
  "Equipe de Manejo Arbóreo (EMA)",
  "Equipe de Vigilância em Saúde Ambiental e Águas (EVSAA)",
  "Escola",
  "Escolas Municipais de Educação Infantil",
  "Escolta",
  "Esporte, Lazer e Juventude",
  "Estação de Bombeamento de Águas Pluviais (Ebap)",
  "Estação Rodoviária de Porto Alegre",
  "Estádio Beira-rio",
  "ETA",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Executivo",
  "Exército Brasileiro",
  "Extremo Sul",

  "Farmácia Distrital Modelo",
  "Fios Soltos",
  "Fiscalização",
  "foco de lixo",
  "Força Nacional do SUS",
  "Fundação de Assistência Social e Cidadania – Fasc",

  "Gabinete da Causa Animal (GCA)",
  "Gabinete de Inovação (GI)",
  "Gabinete do Prefeito",
  "Gabinete Prefeito",
  "gari",
  "Governador Eduardo Leite",
  "Governacia Local e Coordenação Politica",
  "Governança Local e Coordenação Política",
  "Governança Local e Coordenação Política.",
  "Governo Federal",
  "Gp",
  "Grêmio Sargento Expedicionário Geraldo Santana",
  "Grupo Hospitalar Conceição (GHC)",
  "Guarda Municipal",

  "Habitação Regularização Fundiária",
  "Hospital de campanha",

  "Idosos",
  "Ilha da Pintada",
  "Imagem Aérea",
  "Incêndio",
  "Inovação",
  "Instituto Caldeira",
  "Instituto Ling",

  "Junta de Serviço Militar",

  "Lago Guaíba",
  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "lavagem de vias e pontos",
  "Limpeza",
  "Limpeza Urbana",
  "Live",

  "Mãe",
  "Maio Vermelho",
  "Mapa",
  "Marinha do Brasil",
  "Medicamentos",
  "Medicina",
  "Meio Ambiente, Urbanismo e Sustentabilidade",
  "Mercado Público Central",
  "Ministério da Saúde",
  "Ministerio Público - RS",
  "Mobilidade Urbana",
  "Morro Ricaldone",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Mutirão",

  "Núcleo de Imunizações DVS (NI)",
  "Nutrição",

  "Obras",
  "Obras e Infraestrutura",
  "Orçamento Participativo",
  "OP",
  "Orla de Ipanema",

  "Palestra",
  "Paróquia de São Jorge",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Natural Municipal Morro do Osso",
  "Placa de veículos",
  "Planejamento e Assuntos Estratégicos",
  "Plataforma Reconstruir Porto Alegre",
  "Plano de ação Porto Alegre Forte",
  "Polícia Rodoviária Federal",
  "Polícia Rodoviária Federal (PRF)",
  "Polícia Rodoviária Federal - PRF",
  "Pontal do Estaleiro",
  "Pontifícia Universidade Católica do RS (PUCRS)",
  "População de Rua",
  "Porão do Paço",
  "Porto Alegre",
  "Praia de Belas",
  "Prefeito de Porto Alegre, Sebastião Melo",
  "Prefeitura de Porto Alegre",
  "Presidente da Companhia de Processamentos de Dados do Município de Porto Alegre, Leticia Batistela",
  "presidente da Fundação de Assistência Social e Cidadania (FASC), Cristiano Roratto",
  "Presidente da República Luiz Inácio Lula da Silva",
  "Primeiros Socorros",
  "Procempa",
  "Procon Municipal",
  "Procurador geral do município de Porto Alegre, Roberto Silva da Rocha",
  "Procuradoria-Geral do Município de Porto Alegre",
  "Profissionais de Saúde",

  "Quadras de Beach Tennis",
  "Quarto Distrito",

  "Rede Calabria",
  "Rede de abastecimento de água",
  "Rede Municipal de Ensino",
  "remoção de lixo",
  "Resgate",
  "Retirada de Passarela",
  "Reunião",

  "Saúde",
  "Saúde Bucal",
  "Saúde do Idoso",
  "Saúde Mental",
  "Saúde Nutricional e Amamentação",
  "Secretaria Municipal de Administração e Patrimônio (SMAP)",
  "Secretaria Municipal de Cultura e Economia Criativa (SMCEC)",
  "Secretaria Municipal de Desenvolvimento Social (SMDS)",
  "Secretária municipal da Educação (SMED)",
  "Secretaria Municipal de Educação (SMED)",
  "Secretaria Municipal de Esporte, Lazer e Juventude (SMELJ)",
  "Secretaria Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretaria Municipal de Habitação e Regularização Fundiária (SMHARF)",
  "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (SMAMUS)",
  "Secretaria Municipal de Mobilidade Urbana (SMMU)",
  "Secretaria Municipal de Obras e Infraestrutura (SMOI)",
  "Secretaria Municipal de Planejamento e Assuntos Estratégicos (SMPAE)",
  "Secretaria Municipal de Saúde (SMS)",
  "Secretaria Municipal de Segurança (SMSEG)",
  "Secretaria Municipal de Serviços Urbanos (SMSURB)",
  "Secretaria Municipal de Transparência e Controladoria (SMTC)",
  "Secretária municipal de Habitação e Regularização Fundiária, Simone Somensi",
  "Secretário municipal da Fazenda, Rodrigo Fantinel",
  "Secretário Municipal da Saúde (SMS)",
  "Secretário Municipal da Saúde (SMS), Fernando Ritter",
  "Secretário municipal de Desenvolvimento Social, Leo Voigt",
  "Secretário municipal do Gabinete de Inovação, Luiz Carlos Pinto da Silva Filho",
  "Secretário Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretário municipal de Obras e Infraestrutura, André Flores",
  "Segurança",
  "Segurança Pública",
  "Senac",
  "Serviço de Atendimento Móvel de Urgência (SAMU)",
  "Serviço Social",
  "Serviços Urbanos",
  "Servidor",
  "Shopping Total",
  "Sistema Único de Saúde (SUS)",
  "SMED",
  "SMSEG - Segurança",
  "Sms",
  "Subprefeituras",

  "Teatro Renascença",
  "trânsito",
  "Trânsito e Circulação",
  "Transparência e Controladoria",
  "Transporte",
  "Transporte e Circulação",
  "Tratamento de água",
  "Trilha",
  "Trincheira da Ceará",
  "troféu Prefeito Inovador",

  "Unidade de Pronto Atendimento (UPA)",
  "Unidade de Saúde",
  "Unidade de Saúde Animal Victória (Usav)",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Modelo",
  "Unidade de Saúde Santa Marta",
  "Unidade Móvel de Saúde",
  "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)",
  "Universidade Federal do Rio Grande do Sul (UFRGS)",
  "UPA Moacyr Scliar",
  "Usina do Gasômetro",

  "Vacina",
  "vacina contra a Dengue",
  "Vacinação",
  "Veículos",
  "Viaduto Conceição",
  "Viaduto da Conceição",
  "Viagem à Brasília",
  "Vice-governador Gabriel Souza",
  "Vice-prefeito de Porto Alegre, Ricardo Gomes",
  "vice-prefeito Ricardo Gomes",
  "Vigidesastres",
  "Visita",
  "Vistoria",
  "Voluntariado",
  "WhatsApp",
  "Zona Norte",
  "Zona Sul",
];
