export const validTags = [
  "relações Institucionais",
  "(EBAB) Moinhos de Vento",
  "(Emei JP) Cantinho Amigo",
  "#eufaçopoa",
  "4º Distrito",

  "A Cara da Obra",
  "Abastecimento",
  "Abertura",
  "ABRH",
  "Abrigo de Animais da EPTC",
  "Abrigos",
  "Acampamento Farroupilha",
  "Ação Integrada",
  "Ação Rua",
  "Ação Social",
  "Acessibilidade",
  "Acidente",
  "Acidentalidade",
  "Acolhimento",
  "Administração",
  "Administração e Patrimônio",
  "Administração É Patrimônio",
  "Adoção de animais",
  "Adolescente",
  "Adote um Escritor",
  "Adutora",
  "Aedes aegypti",
  "Aéreas",
  "Aeronáutica",
  "Aeroporto Internacional Salgado Filho",
  "Aeroporto Salgado Filho",
  "Agente de Combate às Endemias (ACE)",
  "Agentes Comunitários de Saúde (ACS)",
  "Agentes de Fiscalização",
  "Agentes de Trânsito",
  "Água",
  "Água e Esgoto",
  "Água e Esgotos",
  "Aids",
  "Alagamento",
  "Albergue Felipe Diehl",
  "Albergue Municipal",
  "Albergues",
  "Álcool  e Outras Drogas",
  "Aldeia Indígena",
  "Aleitamento materno",
  "Alimentação",
  "Alimento",
  "Aluno",
  "Alunos",
  "Alvará",
  "Amamentação",
  "Ambulância",
  "Ambulantes",
  "Ambulatório Odontológico",
  "Aniversário",
  "Apae",
  "Aplicativo 156+POA",
  "Aplicativo (app)",
  "Apreensão",
  "Apresentação",
  "Área Azul",
  "Área de risco",
  "Arena do Grêmio",
  "Arquipélago (Ilhas)",
  "Arquivo",
  "Arquivo Histórico Moysés Vellinho",
  "Arrecadação Fiscal",
  "Arroio Cavalhada",
  "Arroio Dilúvio",
  "Arroio Sarandi",
  "Arte Cemiterial",
  "Arte Urbana",
  "Artes Cênicas",
  "Artes Plásticas",
  "Artes Visuais",
  "Artesanato",
  "Árvore",
  "Asfalto",
  "Asilo Padre Cacique",
  "Assembléia Legislativa",
  "Assinatura",
  "Assistência Farmacêutica",
  "Assistência Hospitalar",
  "Assistência Social",
  "Associação Comercial de Porto Alegre (ACPA)",
  "Associação dos Auditores Fiscais da Receita Municipal de Porto Alegre (Aiamu)",
  "Associação Hospitalar Vila Nova",
  "Atelier Livre Xico Stockinger",
  "Atenção Ambulatorial, Hospitalar e Urgências",
  "Atenção Básica",
  "Atenção Primária à Saúde (APS)",
  "Atendimento em Casa",
  "Atendimento Improvisado",
  "Atendimento",
  "Atendimento de Urgência",
  "Atletismo",
  "Audiência",
  "Auditório Araújo Vianna",
  "Auditório da SMPG",
  "Aula aberta",
  "Aula Inaugural",
  "Av. Mauá",
  "Av. Tronco",
  "Ave",
  "Avenida Assis Brasil",
  "Avenida Castello Branco",
  "Avenida Coronel Marcos",
  "Avenida Ipiranga",
  "Avenida Padre Cacique",
  "Avenida Severo Dullius",
  "Avenida Voluntários da Pátria",

  "Bairro Anchieta",
  "Bairro Azenha",
  "Bairro Belém Novo",
  "Bairro Bom Jesus",
  "Bairro Campo Novo",
  "Bairro Cavalhada",
  "Bairro Centro Histórico",
  "Bairro Cidade Baixa",
  "Bairro Cristal",
  "Bairro Cruzeiro",
  "Bairro Farrapos",
  "Bairro Floresta",
  "Bairro Glória",
  "Bairro Hípica",
  "Bairro Humaitá",
  "Bairro Ipanema",
  "Bairro Jardim Carvalho",
  "Bairro Lami",
  "Bairro Lomba do Pinheiro",
  "Bairro Mário Quintana",
  "Bairro Medianeira",
  "Bairro Menino Deus",
  "Bairro Moinhos de Vento",
  "Bairro Navegantes",
  "Bairro Partenon",
  "Bairro Ponta Grossa",
  "Bairro Praia de Belas",
  "bairro Restinga",
  "Bairro Restinga",
  "Bairro Rubem Berta",
  "Bairro São Geraldo",
  "Bairro São José",
  "Bairro Santa Tereza",
  "Bairro Santo Antônio",
  "Bairro Sarandi",
  "Bairro Vila Farrapos",
  "Balada Segura",
  "Balanço",
  "Banco de Leite Humano",
  "Banco de Sangue",
  "Banda Municipal",
  "Baronesa do Gravataí",
  "Basquete",
  "Biblioteca Ecológica Infantil Maria Dinorah",
  "Bicicleta",
  "Bikepoa",
  "Blitz",
  "Bloqueio no trânsito",
  "Bloqueio químico",
  "Bocha",
  "Bombeiros",
  "Brechó",
  "Brechocão",
  "Brigada Militar",
  "Brique da Redenção",
  "BRT's",

  "Cachorro",
  "Cadastro Único",
  "CÃES",
  "Cais Mauá",
  "Caixa Econômica Federal",
  "Camaquã",
  "Câmara de Vereadores",
  "Câmara Municipal de Porto Alegre (CMPA)",
  "Caminhada",
  "Caminho do Gol",
  "Caminho dos Jacarandás",
  "caminhões-pipa",
  "Caminhos Rurais",
  "Campanha",
  "Campanha do Agasalho",
  "Campanha Nacional de Vacinação contra Gripe (influenza)",
  "Campeonato",
  "Câncer",
  "Câncer Bucal",
  "Câncer de Mama",
  "Capacitação",
  "Capester",
  "Capina",
  "Capital Gaúcha",
  "Carnaval",
  "Carnaval 2017",
  "Carris",
  "Carro",
  "Casa de Apoio Viva Maria",
  "Casa de Bombas",
  "Casa de Cultura Mario Quintana",
  "Casa do Gaúcho",
  "Casa dos Conselhos",
  "Casa Lar do Idoso",
  "Casamento",
  "Catamarã",
  "Catedral Metropolitana de Porto Alegre (Matriz)",
  "Causa Animal",
  "Cavalo",
  "CDL Porto Alegre",
  "Cecoflor",
  "CEEE Equatorial",
  "Ceic",
  "CEIC",
  "Cel QOEM Mário Yukio Ikeda",
  "Cel. Evaldo Rodrigues Oliveira",
  "Cemitério da Santa Casa de Misericórdia",
  "Centro Administrativo Municipal (CAM)",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural Usina do Gasômetro",
  "Centro de Atenção Psicossocial Álcool e Drogas (CAPS AD)",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Informações Estratégicas em Vigilância em Saúde (Cievs)",
  "Centro de Referência em Saúde do Trabalhador (Cerest)",
  "Centro de Saúde Modelo",
  "Centro de Saúde Murialdo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro de triagem",
  "Centro de Valorização da Vida",
  "Centro Histórico",
  "Centro Humanístico Vida",
  "Centro Integrado de Comando",
  "Centro Integrado de Comando da Cidade de Porto Alegre (CEIC)",
  "Centro Popular de Compras (CPC)",
  "Cercamento Eletrônico",
  "Cerimônia",
  "Certificado",
  "CETE - Centro Estadual de Treinamento Esportivo",
  "CGVS",
  "Chalé da Praça XV de Novembro",
  "Chikungunya",
  "Chuva",
  "Ciclovia",
  "Cidadania",
  "Cidades Educadoras",
  "Cinemateca Capitólio",
  "Circulação",
  "Circulação e Transporte",
  "Clássicos na Pinacoteca",
  "Clínica da Família",
  "CMDUA",
  "Colégio Militar de Porto Alegre",
  "Coleta",
  "Coleta Seletiva",
  "Coletiva de Imprensa",
  "Colônia de Pescadores Z5",
  "Comandante da Guarda Municipal, Marcelo Nascimento",
  "Comando Militar do Sul",
  "Comércio",
  "Comércio Irregular",
  "Comissão da Pessoa com Deficiência",
  "Comissão de Saúde e Segurança no Trabalho",
  "Comissão Permanente de Atuação em Emergências (Copae)",
  "Companhia Carris Porto Alegrense",
  "Companhia de Processamento de Dados do Município (Procempa)",
  "Companhia Municipal de Dança",
  "Complexo Cultural Porto Seco",
  "Complexo Hospitalar Santa Casa",
  "comportas do Muro da Mauá",
  "Compostagem",
  "Computador",
  "COMTU",
  "Comunicação",
  "Comunicação Social",
  "Conaf",
  "Concerto Musical",
  "Concurso",
  "Conferência",
  "Conscientização",
  "Conselho do OP",
  "Conselho Municipal de Saúde",
  "Conselhos Municipais",
  "Consul Honorária dos Países Baixos em Porto Alegre",
  "Consulado",
  "Consultório na Rua",
  "Consumidor",
  "Controladoria",
  "Convênio",
  "Convite",
  "Coordenação de Operações Especiais (COE)",
  "Coordenação Municipal de Urgências (CMU)",
  "Coordenações",
  "Cootravipa",
  "Coronavírus",
  "Corredor Humanitário",
  "Corregedoria",
  "Corrida",
  "Covid-19",
  "Criança",
  "CRIPs",
  "Cruz Vermelha do Brasil",
  "Cultura",
  "Cultura e Economia Criativa",
  "Curso",
  "Curso de Formação",
  "Curso de Mecânica",

  "Dança",
  "Debate",
  "Declaração de Edimburgo",
  "Defesa Civil",
  "Dengue",
  "Departamento Municipal de Água e Esgotos (DMAE)",
  "Departamento Municipal de Habitação (Demhab)",
  "Departamento Municipal de Limpeza Urbana (DMLU)",
  "Desabrigados",
  "Desastres",
  "Desenvolvimento",
  "Desenvolvimento Economico",
  "Desenvolvimento Econômico",
  "Desenvolvimento Economico e Esporte",
  "Desenvolvimento Social",
  "Desenvolvimento Social e Esporte",
  "Deslizamento",
  "desvio de trânsito",
  "Dia D de Vacinação",
  "Dia do Desafio",
  "Dia do Gari",
  "Dique",
  "Direito do Consumidor",
  "Direitos Animais",
  "Direitos do Consumidor",
  "Direitos dos Animais",
  "Direitos Humanos",
  "diretor-presidente do DMAE, Maurício Loss",
  "Diretoria de Vigilância em Saúde (DVS)",
  "Diversidade sexual",
  "Dmae",
  "DMAE",
  "DMAP",
  "Dmlu",
  "DMLU",
  "Doação",
  "doação de sangue",
  "doação e transplante de órgãos",
  "doações de cestas básicas",
  "Doença Respiratória",
  "Doenças Transmissíveis",
  "Downburst",
  "Dragagem",
  "Drenagem",
  "Drone",

  "Ecobarreira",
  "Economia Solidária",
  "Edifício Intendente José Montaury",
  "Educação",
  "Educação Ambiental",
  "Educação Básica",
  "Educação Especial",
  "Educação Fundamental",
  "Educação Infantil",
  "Educação no Trânsito",
  "Educação Permanente",
  "Educação Superior",
  "Eixo Baltazar",
  "eleições",
  "Embaixada",
  "Embratel",
  "Emeb Liberato Salzano Vieira da Cunha",
  "Emeef Elyseu Paglioli",
  "EMEF",
  "EMEF Deputado Marcírio Goulart Loureiro",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "Emef Migrantes",
  "EMEF Porto Novo",
  "EMEF Professora Ana Íris do Amaral",
  "EMEF Vereador Antônio Giúdice",
  "EMEF Vila Monte Cristo",
  "EMEI",
  "EMEI Dom Luiz de Nadal",
  "EMEI Humaitá",
  "Emei Ilha da Pintada",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "EMEM",
  "Empreendedorismo",
  "Emprego",
  "Empresa Pública de Transporte e Circulação (EPTC)",
  "Encerramento",
  "Enchente",
  "Enchente Porto Alegre",
  "Enchente Porto Alegre Maio de 2024",
  "Ensino",
  "Entrada da cidade",
  "Entrega de Doações",
  "Entrevista Coletiva",
  "Eptc",
  "EPTC",
  "Equipe de Manejo Arbóreo (EMA)",
  "Equipe de Vigilância de Alimentos da SMS",
  "Equipe de Vigilância em Saúde Ambiental e Águas (EVSAA)",
  "Escola",
  "Escola de Gestão Pública (EGP)",
  "Escolas Municipais de Educação Infantil",
  "Escolta",
  "Escultura",
  "Esgoto",
  "Esgoto Pluvial",
  "Espetáculo",
  "Esporte",
  "Esporte, Lazer e Juventude",
  "Esporte Lazer e Juventude",
  "Esportes e Lazer",
  "Esquina Democrática",
  "Estação de Bombeamento de Águas Pluviais (Ebap)",
  "Estação Rodoviária de Porto Alegre",
  "Estácio",
  "Estações de Bombeamento de Águas Pluviais (Ebaps)",
  "Estádio Beira-rio",
  "Estrada das Furnas",
  "Estreia",
  "Estudantes",
  "ETA",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Exame médico",
  "Executivo",
  "Exército Brasileiro",
  "Expointer",
  "exposição",
  "Extremo Sul",

  "Fachada",
  "Famurs",
  "Farmácia",
  "Farmácia Distrital Modelo",
  "Farmácia Móvel",
  "Fasc",
  "Fauna",
  "Fazenda",
  "febre amarela",
  "Fecomércio",
  "Feira do Livro",
  "Feira Ecológica",
  "Feira Temática",
  "Festejos",
  "Festival",
  "Festival de Inverno",
  "Festival do Japão",
  "Fiergs",
  "Finanças",
  "Finanças Públicas",
  "Fios Soltos",
  "Fique Sabendo Jovem",
  "Fiscalização",
  "Flagrante",
  "Flora",
  "foco de lixo",
  "Food truck",
  "Força Nacional do SUS",
  "Força-Tarefa",
  "Forças Armadas",
  "Formação",
  "Formatura",
  "Fórum",
  "Fórum Social Mundial da População Idosa",
  "Fotografia",
  "Frio",
  "Fundação de Assistência Social e Cidadania – Fasc",
  "Fundação Iberê Camargo",
  "Fundação O Pão dos Pobres",
  "Futebol",
  "Futebol de Várzea",
  "Futebol Feminino",
  "Futsal",

  "Gabinete",
  "Gabinete da Causa Animal (GCA)",
  "Gabinete de Inovação (GI)",
  "Gabinete do Prefeito",
  "Gabinete Prefeito",
  "gari",
  "Gato",
  "GeraçãoPoa",
  "GeraEncontro",
  "Gestão e Planejamento",
  "Ginásio Lupi Martins",
  "Ginásio Tesourinha",
  "Ginástica",
  "Governador",
  "Governador Eduardo Leite",
  "Governacia Local e Coordenação Politica",
  "Governança",
  "Governança Local e Coordenação Política",
  "Governança Local e Coordenação Política.",
  "Governo Federal",
  "Gp",
  "Grêmio Foot-Ball Porto Alegrense",
  "Grêmio Sargento Expedicionário Geraldo Santana",
  "Gre-Nal",
  "Gre-nal de Todos",
  //"Greve",
  "Gripe",
  "Grupo Experimental de Dança (GED)",
  "Grupo Hospitalar Conceição (GHC)",
  "Guaíba",
  "Guarda Municipal",
  "Gvp",

  "Habitação",
  "Habitação Regularização Fundiária",
  "Habitação e Regularização Fundiária",
  "Hamilton Sossmeier",
  "Handebol",
  "Hanseníase",
  "Hipismo",
  "HMIPV",
  "Homenagem",
  "Horário estendido",
  "Hospital da Restinga Extremo Sul (HRES)",
  "Hospital de campanha",
  "Hospital de Clínicas de Porto Alegre (HCPA)",
  "Hospital de Pronto Socorro (HPS)",
  "Hospital Materno-Infantil Presidente Vargas (HMIPV)",
  "Hospital Moinhos de Vento",
  "Hospital Santa Ana",

  "Ideb",
  "Idosos",
  "Igreja Nossa Senhora das Dores",
  "Ilha da Pintada",
  "Ilha dos Marinheiros",
  "Iluminação Pública",
  "Imagem Aérea",
  "Imigrantes",
  "Imposto",
  "Inauguração",
  "Incêndio",
  "Inclusão Social",
  "Indústria",
  "Infecções Sexualmente Transmissíveis (IST)",
  "Informatização",
  "Infraestrutura e Mobilidade",
  "Infraestrutura e Mobilidade Urbana",
  "Infraestrutura e Urbanismo",
  "Inovação",
  "Inspeção veicular",
  "Instituto Caldeira",
  "Instituto Ling",
  "Interdição",
  "Internet",
  "IPTU",

  "Jockey Club",
  "Jogos Abertos",
  "Jogos dos Estudantes Surdos",
  "Junta de Serviço Militar",
  "Justiça",
  "Juventude",

  "Laçador",
  "Lago Guaíba",
  "Lançamento",
  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "lavagem de vias e pontos",
  "Lazer",
  "Lei",
  "Lei de Diretrizes Orçamentárias (LDO)",
  "Lei Orçamentária Anual (LOA)",
  "Lei Seca",
  "Leishmaniose",
  "Leito Hospitalar",
  "LGBT",
  "Licenciamento Urbano",
  "Limpeza",
  "Limpeza Urbana",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Live",
  "Livro e Literatura",
  "Lixo",
  "Lomba do Pinheiro",
  "Loteamento",

  "Mãe",
  "Maio Amarelo",
  "Maio Vermelho",
  "Manifestação",
  "Manutenção",
  "Mapa",
  "Maratona",
  "Maratona de Dança",
  "Maria de Fátima Záchia Paludo",
  "Marinha do Brasil",
  "Mascote",
  "Material Escolar",
  "Mauro Pinheiro",
  "MEC",
  "Medicamentos",
  "Medicina",
  "Medicina Veterinária",
  "Meio Ambiente",
  "Meio Ambiente e Sustentabilidade",
  "Meio Ambiente, Urbanismo e Sustentabilidade",
  "Memória",
  "Menino Deus",
  "Mercado Público",
  "Mercado Público Central",
  "Metas",
  "Ministério da Saúde",
  "Ministerio Público - RS",
  "Mobiliário Urbano",
  "Mobilidade",
  "Mobilidade Urbana",
  "Moinhos de Vento",
  "Monitoramento",
  "Morro Ricaldone",
  "Mortes no trânsito",
  "Mosquito Aedes Aegypti",
  "Motocicleta",
  "Mulher",
  "multivacinação",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Música",
  "Mutirão",
  "Mutirão de cirurgias",

  "Natal",
  "Natal dos Encantos",
  "Navegantes",
  "Nivel do Guaíba",
  "Novembro Azul",
  "Novo Marco Global",
  "Núcleo de Imunizações DVS (NI)",
  "Nutrição",
  "Nuvens",

  "OAB-RS",
  "Obra de arte",
  "Obras",
  "Obras da Copa de 2014",
  "Obras e Infraestrutura",
  "OdontoSesc",
  "Oficina",
  "Ônibus",
  "OP",
  "Op 2017",
  "Operação Inverno",
  "Orçamento Participativo",
  "Orçamento Participativo 2018",
  "Orla de Ipanema",
  "Orla do Guaíba",
  "Orla Moacyr Scliar",
  "Outubro Rosa",

  "Paço dos Açorianos",
  "Paço Municipal de Porto Alegre",
  "Palácio do Comércio",
  "Palácio Piratini",
  "Palestra",
  "Parceria Público-Privada",
  "Parcerias",
  "Parcerias Estratégicas",
  "Parklet",
  "Paróquia de São Jorge",
  "Parque Ararigbóia",
  "Parque Chico Mendes",
  "Parque Farroupilha (Redenção)",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Parque Maurício Sirotsky Sobrinho (Harmonia)",
  "Parque Moinhos de Vento (Parcão)",
  "Parque Natural Municipal Morro do Osso",
  "Parque Urbano da Orla Moacyr Scliar",
  "Partenon",
  "Páscoa",
  "Passeio",
  "Patrimônio",
  "Pavimentação",
  "Pedestre",
  "Pedestre Idoso",
  "Pessoa com Deficiência",
  "Pessoa com mobilidade reduzida",
  "Petrópolis",
  "PGM",
  "Pinacoteca Aldo Locatelli",
  "Pinacoteca Ruben Berta",
  "Pisa",
  "Piscinas Públicas",
  "Placa de veículos",
  "Planejamento",
  "Planejamento e Assuntos Estratégicos",
  "Planejamento e Gestão",
  "Plano de Superação da Situação de Rua",
  "Plataforma Reconstruir Porto Alegre",
  "Plantio",
  "Plano de ação Porto Alegre Forte",
  "Plano Diretor",
  "Plaza São Rafael",
  "Poa Em Cena",
  "PoaHub",
  "Poda",
  "Polícia Rodoviária Federal",
  "Polícia Rodoviária Federal (PRF)",
  "Polícia Rodoviária Federal - PRF",
  "Pontal do Estaleiro",
  "Ponte do Guaíba",
  "Pontifícia Universidade Católica do RS (PUCRS)",
  "População de Rua",
  "População em Situação de Rua",
  "População Negra",
  "Porão do Paço",
  "Porto Alegre",
  "Posse",
  "Povo Negro",
  "PPA",
  "Praça da Alfândega",
  "Praça Doutor Lopes Trovão",
  "Praça Marechal Deodoro (Matriz)",
  "Praça Montevideo",
  "Praças e Parques",
  "Praia de Belas",
  "Prédio público",
  "Prédios e Edificações",
  "Prefeito",
  "Prefeito de Porto Alegre, Sebastião Melo",
  "Prefeitura de Porto Alegre",
  "Prefeitura nos Bairros",
  "Prefeitura Nos Bairros",
  "Premiação",
  "Presidente",
  "Presidente da Câmara Municipal de Vereadores,  Idenir Cecchim",
  "Presidente da Companhia de Processamentos de Dados do Município de Porto Alegre, Leticia Batistela",
  "presidente da Fundação de Assistência Social e Cidadania (FASC), Cristiano Roratto",
  "Presidente da República Luiz Inácio Lula da Silva",
  "Prevenção",
  "Previdência",
  "Previmpa",
  "Previsão do Tempo",
  "Primeira Infância Melhor (PIM)",
  "Primeira Infância Melhor no Contexto Prisional (Pim Prisional)",
  "Primeiros Socorros",
  "Procempa",
  "Procissão",
  "Procon",
  "Procon Móvel",
  "Procon Municipal",
  "Procurador geral do município de Porto Alegre, Roberto Silva da Rocha",
  "Procuradoria",
  "Procuradoria Geral",
  "Procuradoria-Geral do Município de Porto Alegre",
  "Profissionais de Saúde",
  "Programa de Residência Técnico-Superior (PRTS)",
  "Programa Municipal de Rastreamento de Câncer Colorretal",
  "Programa de Trabalho Educativo (PTE)",
  "Programação do Reveillon",
  "Projeto de Lei",
  "Projeto Jogo Limpo",
  "Projeto Pescar",
  "Prometas",
  "Propaganda Eleitoral",
  "PUCRS",

  "Quadras de Beach Tennis",
  "Quarto Distrito",
  "Quilombos",

  "Ramiro Rosário",
  "Reciclagem",
  "Rede Calabria",
  "Rede de abastecimento de água",
  "Rede Municipal de Ensino",
  "redes de água",
  "Região Metropolitana",
  "Relações Institucionais",
  "Regularização",
  "Regularização Fundiária",
  "Reintegração de Posse",
  "Remanejo",
  "remoção de lixo",
  "Reserva Biológica do Lami José Lutzenberger",
  "Resgate",
  "Resíduos Sólidos",
  "Resiliência",
  "Restauração",
  "Restaurante Popular",
  "Retirada de Passarela",
  "Retrato",
  "Reunião",
  "Reunião-almoço Tá Na Mesa",
  "Revitalização",
  "Robótica",
  "Roçada",
  "ROMU",
  "roubo",
  "Rua José Pedro Boessio",
  "Ruas e avenidas",

  "Sala Aldo Locatelli",
  "Sala Álvaro Moreyra",
  "Sala da Fonte",
  "Sala dos Embaixadores",
  "Sala P. F. Gastal",
  "Salão Internacional de Desenho para Imprensa (Sidi)",
  "Salão Nobre",
  "Salão Nobre do Paço Municipal",
  "sanção de Projeto de Lei",
  "Sangue",
  "Santa Cecília",
  "Santander",
  "Saúde",
  "Saúde Bucal",
  "Saúde do Idoso",
  "Saúde do Trabalhador",
  "Saúde Mental",
  "Saúde Nutricional e Amamentação",
  "Sebrae",
  "Secretaria Extraordinária do Trabalho e da Qualificação Profissional (SMTQ)",
  "Secretaria Municipal de Administração e Patrimônio (SMAP)",
  "Secretaria Municipal de Cultura e Economia Criativa (SMCEC)",
  "Secretaria Municipal de Desenvolvimento Econômico e Turismo (SMDET)",
  "Secretaria Municipal de Desenvolvimento Social (SMDS)",
  "Secretária municipal da Educação (SMED)",
  "Secretaria Municipal de Educação (SMED)",
  "Secretaria Municipal de Esporte, Lazer e Juventude (SMELJ)",
  "Secretaria Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretaria Municipal de Habitação e Regularização Fundiária (SMHARF)",
  "Secretária municipal de Habitação e Regularização Fundiária, Simone Somensi",
  "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (SMAMUS)",
  "Secretaria Municipal de Mobilidade Urbana (SMMU)",
  "Secretaria Municipal de Obras e Infraestrutura (SMOI)",
  "Secretaria Municipal de Parcerias (SMP)",
  "Secretaria Municipal de Planejamento e Assuntos Estratégicos (SMPAE)",
  "Secretaria Municipal de Saúde (SMS)",
  "Secretaria Municipal de Segurança (SMSEG)",
  "Secretaria Municipal de Serviços Urbanos (SMSURB)",
  "Secretaria Municipal de Transparência e Controladoria (SMTC)",
  "Secretariado",
  "Secretário Municipal da Educação (SMED)",
  "Secretário municipal da Fazenda, Rodrigo Fantinel",
  "Secretário Municipal da Saúde (SMS)",
  "Secretário Municipal da Saúde (SMS), Fernando Ritter",
  "Secretário Municipal de Administração e Patrimônio (SMAP)",
  "Secretário municipal de Administração e Patrimônio, André Barbosa",
  "Secretário municipal de Desenvolvimento Social, Leo Voigt",
  "Secretário Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretário municipal de Obras e Infraestrutura, André Flores",
  "Secretário municipal de Planejamento e Assuntos Estratégicos, Cezar Schirmer",
  "Secretário municipal do Gabinete de Inovação, Luiz Carlos Pinto da Silva Filho",
  "Secretário municipal do Meio Ambiente, Urbanismo e Sustentabilidade, Germano Bremm",
  "Sede do Tribunal de Contas do Estado (TCE)",
  "Seguranç",
  "Segurança",
  "Segurança Publica",
  "Segurança Pública",
  "Semáforos",
  "Semana Cidade Limpa",
  "Semana de Porto Alegre",
  "Semana do Japão",
  "Semana Farroupilha",
  "Seminário",
  "Senac",
  "Serviço de Atendimento Móvel de Urgência (SAMU)",
  "Serviço Funerário",
  "Serviço Social",
  "Serviços Urbanos",
  "Servidor",
  "Sesc",
  "SESI",
  "Shopping Total",
  "Simpósio",
  "Sinalização de trânsito",
  "Sindha",
  "Sindicato dos Municipários de Porto Alegre (Simpa)",
  "Sindilojas",
  "síndrome de down",
  "Sine Municipal",
  "Sistema Único de Saúde (SUS)",
  "Situação de rua",
  "Smdes",
  "Smds",
  "Smdse",
  "SMED",
  "Smpg",
  "Smic",
  "Smim",
  "Smri",
  "Sms",
  "SMSEG - Segurança",
  "Socioambiental",
  "Sociedade Libanesa de Porto Alegre",
  "Sol",
  "Solidariedade",
  "Sport Club Internacional",
  "Subprefeituras",
  "Sustentabilidade",

  "Tabagismo",
  "Tapa Buracos",
  "Tarifa",
  "Táxi",
  "Teatro",
  "Teatro de Câmara Túlio Piva",
  "Teatro do Sesc",
  "Teatro Renascença",
  "Tecnologia",
  "TelessaúdeRS",
  "Tempo",
  "Temporal",
  "Tenda",
  "Terminais de ônibus",
  "Terminal Parobé",
  "Terminal Triângulo",
  "Terreno",
  "Testagem",
  "Teste do Pezinho",
  "Theatro São Pedro",
  "TJ-RS",
  "Todos Contra O Assédio",
  "Totem iluminado",
  "Trabalho e Emprego",
  "Trabalho e Qualificação",
  "Tradicionalismo",
  "Transexualidade",
  "trânsito",
  "Trânsito e Circulação",
  "Transito e Transporte",
  "Transmissão de Cargo",
  "Transparência",
  "Transparência e Controladoria",
  "Transparência e Controladoria Geral",
  "Transporte",
  "Transporte Coletivo",
  "Transporte e Circulaçao",
  "Transporte e Circulação",
  "Transporte Público",
  "Transtornos no trânsito",
  "Tratamento de água",
  "Trensurb",
  "Tribunal de Contas do Estado do Rio Grande do Sul (TCE-RS)",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Tributação",
  "Trilha",
  "Trincheira da Ceará",
  "Tristeza",
  "troféu Prefeito Inovador",
  "Túnel da Conceição",
  "Turismo",

  "Ulbra",
  "Unesco",
  "Unidade de Coleta e Transfusão (UCT) do HPS",
  "Unidade de Pronto Atendimento (UPA)",
  "Unidade de Saúde",
  "Unidade de Saúde Animal Victória (Usav)",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Modelo",
  "Unidade de Saúde Santa Marta",
  "Unidade de Saúde São Carlos",
  "Unidade de Saúde Tristeza",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "Uniritter",
  "Unisinos",
  "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)",
  "Universidade Federal do Rio Grande do Sul (UFRGS)",
  "UPA Moacyr Scliar",
  "Urbanismo",
  "Urbanização",
  "Usina do Gasômetro",

  "Vacina",
  "vacina contra a Dengue",
  "Vacinação",
  "Vagas de Emprego",
  "Vandalismo",
  "Varejo",
  "veículo",
  "Veículos",
  "Vento",
  "vereador",
  "Vereadores",
  "Viaduto Conceição",
  "Viaduto da Conceição",
  "Viaduto Otávio Rocha",
  "Viagem à Brasília",
  "Viagem à Europa",
  "Vice-governador Gabriel Souza",
  "Vice-prefeito",
  "Vice-prefeito de Porto Alegre, Ricardo Gomes",
  "vice-prefeito Ricardo Gomes",
  "Videoconferência",
  "Vigidesastres",
  "Vigilância de Alimentos",
  "Vigilância em Saúde",
  "Vigilância Em Saúde",
  "Vigilância Sanitária",
  "Vila dos Ferroviários",
  "Vila Ipiranga",
  "Vila Nova",
  "Vírus T-linfotrópico humano (HTLV)",
  "Visita",
  "Visita de Cortesia",
  "Visita domiciliar",
  "Vistoria",
  "Vítimas",
  "Vôlei",
  "Volta às aulas",
  "Voluntariado",

  "WhatsApp",
  "Workshop",

  "Zona Leste",
  "Zona Norte",
  "Zona Sul",
];
