// List of tags for which the category is the same
export const sameNameTags = [
  "A Cara da Obra",
  "Abrigo de Animais da EPTC",
  "Ação Rua",
  "Adote um Escritor",
  "Albergue Felipe Diehl",
  "Aldeia Kaingang",
  "Anfiteatro Pôr do Sol",
  "Aplicativo 156+POA",
  "Área Azul",
  "Arena do Grêmio",
  "Arroio Cavalhada",
  "Arroio Dilúvio",
  "Arroio Sarandi",
  "Associação Hospitalar Vila Nova",
  "Atelier Livre Xico Stockinger",
  "Asilo Padre Cacique",
  "Auditório Araújo Vianna",
  "Auditório do Global Tecnopuc",
  "Avenida Assis Brasil",
  "Avenida Coronel Marcos",
  "Avenida Padre Cacique",
  "Avenida Sertório",
  "Avenida Severo Dullius",

  "Balada Segura",
  "Banco de Talentos",
  "Biblioteca Ecológica Infantil Maria Dinorah",
  "Bikepoa",
  "Brechocão",
  "Brique da Redenção",

  "Cais Mauá",
  "Caixa Econômica Federal",
  "Câmara Rio-Grandense do Livro",
  "Caminho do Gol",
  "Caminho dos Jacarandás",
  "Capester",
  "Casa de Apoio Viva Maria",
  "Casa de Cultura Mario Quintana",
  "Casa do Gaúcho",
  "Casa Lar do Idoso",
  "Cecoflor",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural Usina do Gasômetro",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Saúde IAPI",
  "Centro de Saúde Modelo",
  "Centro de Saúde Murialdo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro de Valorização da Vida",
  "Chikungunya",
  "Cinemateca Capitólio",
  "Clássicos na Pinacoteca",
  "Colégio Militar de Porto Alegre",
  "Colônia de Pescadores Z5",
  "Comando Militar do Sul",
  "Companhia Jovem de Dança",
  "Companhia Municipal de Dança",
  "Complexo Hospitalar Santa Casa",
  "Consultório na Rua",
  "Cootravipa",

  "DermatoNet",
  "Dia D de Vacinação",
  "Dia do Gari",

  "Edifício Intendente José Montaury",
  "Eixo Baltazar",
  "Embratel",
  "EMEF Deputado Marcírio Goulart Loureiro",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "EMEF Mario Quintana",
  "EMEF Migrantes",
  "EMEF Porto Novo",
  "EMEF Professora Ana Íris do Amaral",
  "EMEF Vereador Antônio Giúdice",
  "EMEF Vila Monte Cristo",
  "EMEI Dom Luiz de Nadal",
  "EMEI Humaitá",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "Esquina Democrática",
  "Estrada das Furnas",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Extremo Sul",

  "Farmácia Distrital Modelo",
  "Farmácia Móvel",
  "Fique Sabendo Jovem",
  "Fórum Social Mundial da População Idosa",
  "Fundação Iberê Camargo",

  "Galpão da Hospitalidade",
  "GeraçãoPoa",
  "GeraEncontro",
  "Ginásio Lupi Martins",
  "Ginásio Tesourinha",
  "Grêmio Foot-Ball Porto Alegrense",

  "Hortomercado Parobé",
  "Hospital Moinhos de Vento",
  "Hospital Santa Ana",

  "I Love Poa",
  "Ilha da Pintada",
  "Instituto Caldeira",
  "Instituto Ling",
  "Instituto Penal Feminino de Porto Alegre",

  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Lomba do Pinheiro",

  "Maio Amarelo",
  "Maio Vermelho",
  "Mexatchê",
  "Moinhos de Vento",
  "Morro Ricaldone",
  "Museu de Porto Alegre Joaquim Felizardo",

  "Natal dos Encantos",

  "OdontoSesc",
  "Operação Bota-Fora",
  "Operação Inverno",
  "Orçamento Participativo 2018",
  "Orla de Ipanema",

  "Palácio Piratini",
  "Parque Chico Mendes",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Parque Natural Municipal Morro do Osso",
  "Pedestre Idoso",
  "Pinacoteca Ruben Berta",
  "Plano de Superação da Situação de Rua",
  "Plataforma Reconstruir Porto Alegre",
  "Plaza São Rafael",
  "Polícia Rodoviária Federal",
  "Ponte do Guaíba",
  "Porão do Paço",
  "Porto Alegre",
  "Praça Darcy Azambuja",
  "Praça Doutor Lopes Trovão",
  "Praia de Belas",
  "Prefeitos de Praça",
  "Prefeitura nos Bairros",
  "Programa Municipal de Rastreamento de Câncer Colorretal",
  "Projeto 100% Digital",
  "Projeto Jogo Limpo",
  "Projeto Pescar",
  "Prometas",

  "Rede Calabria",
  "Reserva Biológica do Lami José Lutzenberger",
  "Residencial São Guilherme",
  "Rua José Pedro Boessio",

  "Sala Álvaro Moreyra",
  "Sala Cecy Frank",
  "Sala da Fonte",
  "Sala P. F. Gastal",
  "Semana Cidade Limpa",
  "Semanas Internacionais",
  "Seminário Nacional de Trânsito - Mobilidade Sustentável, Educação, e Segurança",
  "Shopping Total",
  "Sindilojas",
  "Sociedade Libanesa de Porto Alegre",
  "Sport Club Internacional",

  "Teatro Carlos Carvalho",
  "Teatro de Câmara Túlio Piva",
  "Teatro Renascença",
  "TelessaúdeRS",
  "Terminal Triângulo",
  "Termo de Adoção de Verde Complementar",
  "Todos Contra O Assédio",
  "Todos Somos Porto Alegre",
  "Trensurb",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Tristeza",
  "Túnel da Conceição",

  "Unidade de Saúde Alto Embratel",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Orfanotrófio",
  "Unidade de Saúde Osmar Freitas",
  "Unidade de Saúde Ponta Grossa",
  "Unidade de Saúde Santo Alfredo",
  "Unidade de Saúde São Carlos",
  "Unidade de Saúde Tristeza",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "UPA Moacyr Scliar",
  "Usina do Gasômetro",

  "Viaduto da Conceição",
  "Viaduto Otávio Rocha",
  "Vigidesastres",
  "Vila dos Ferroviários",
  "Vila Jardim",
  "Vila Minuano",
  "WhatsApp",
];
