// List of tags for which the category is the same
export const sameNameTags = [
  "1ª Expo-Feira Náutica Almirante Tamandaré 2019",

  "A Cara da Obra",
  "A Flauta Mágica",
  "Abrigo de Animais da EPTC",
  "Abrigo Residencial AR 7",
  "Ação Rua",
  "Ação Rua Calábria",
  "Adote um Escritor",
  "Adutora Antonio Borges",
  "Albergue Felipe Diehl",
  "Anfiteatro Pôr do Sol",
  "Aplicativo 156+POA",
  "Área Azul",
  "Arena do Grêmio",
  "Arroio Cavalhada",
  "Arroio Sarandi",
  "Assembleia de Verão da Famurs 2025",
  "Associação Comunitária Núcleo Esperança",
  "Associação Hospitalar Vila Nova",
  "Atelier Livre Xico Stockinger",
  "Asilo Padre Cacique",
  "Atenção Especializada à Saúde",
  "Auditório Araújo Vianna",
  "Auditório da EPTC",
  "Auditório da ESPM",
  "Auditório da SMPE",
  "Auditório da SMTC",
  "Auditório do Global Tecnopuc",
  "Auditório do Instituto Cultural",
  "Auditório do Palácio da Polícia",
  "Auditório do Previmpa",
  "Auditório do Telessaúde-RS",
  "Avenida Assis Brasil",
  "Avenida Bento Gonçalves",
  "Avenida Coronel Marcos",
  "Avenida Eduardo Prado",
  "Avenida Goethe",
  "Avenida Nilo Peçanha",
  "Avenida Nonoai",
  "Avenida Padre Cacique",
  "Avenida Plínio Brasil Milano",
  "Avenida Sertório",
  "Avenida Severo Dullius",
  "Avenida Venâncio Aires",

  "Balada Segura",
  "Banco de Talentos",
  "Bará do Mercado Público",
  "Biblioteca Ecológica Infantil Maria Dinorah",
  "Biblioteca Jornalista Roberto Eduardo Xavier",
  "Bikepoa",
  "Bloco cirúrgico do Posto do IAPI",
  "Bolsa Atleta Municipal",
  "Bolsa Família",
  "Brechocão",
  "Brique da Redenção",

  "Cais Mauá",
  "Caixa Econômica Federal",
  "Câmara Rio-Grandense do Livro",
  "Caminho do Gol",
  "Caminho dos Jacarandás",
  "Capester",
  "Capitol Riverfront",
  "Campo de Futebol Luiz Carlos Oliveira (Bolinha)",
  "Carta de Serviços",
  "Cartão Material Escolar",
  "Casa da Estrela",
  "Casa de Apoio Viva Maria",
  "Casa de Cultura Mario Quintana",
  "Casa de Festas Brincalhão",
  "Casa do Gaúcho",
  "Casa Lar do Idoso",
  "Cecoflor",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural Multimeios Restinga",
  "Centro Cultural Usina do Gasômetro",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Eventos Laçador",
  "Centro de Monitoramento e Contingência Climática",
  "Centro de Saúde IAPI",
  "Centro de Saúde Modelo",
  "Centro de Saúde Murialdo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro de Valorização da Vida",
  "Centro Logístico de Medicamentos Especiais",
  "Chikungunya",
  "Ciclo de Debates Barbara Starfield",
  "Cinemateca Capitólio",
  "Circuito Urbano EPTC",
  "Clássicos na Pinacoteca",
  "Clube de Criação RS",
  "Colégio Militar de Porto Alegre",
  "Colônia de Férias Geraldo Santana",
  "Colônia de Pescadores Z5",
  "Comando Militar do Sul",
  "Companhia Jovem de Dança",
  "Companhia Municipal de Dança",
  "Complexo Hospitalar Santa Casa",
  "Compra Assistida",
  "Confeitaria Rocco",
  "Conferência Municipal do Meio Ambiente",
  "Consultório na Rua",
  "Cootravipa",
  "Coro do DMAE",
  "Côrte da Festa da Uva e da Ameixa de Porto Alegre",
  "Corte do Carnaval de Porto Alegre 2025",
  "CRIP Extremo-Sul",

  "Desafio Microrrevoluções Urbanas",
  "Descida da Borges",
  "DermatoNet",
  "Dia D de Vacinação",
  "Dia do Gari",
  "Direitos Humanos na Educação Infantil e Ensino Fundamental",

  "Edifício Intendente José Montaury",
  "Educa+Saúde",
  "Eixo Baltazar",
  "Embratel",
  "EMEF Deputado Marcírio Goulart Loureiro",
  "EMEF Gabriel Obino",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "EMEF Leopolda Barnewitz",
  "EMEF Mario Quintana",
  "EMEF Migrantes",
  "EMEF Porto Novo",
  "EMEF Professora Ana Íris do Amaral",
  "EMEF Vereador Antônio Giúdice",
  "EMEF Vila Monte Cristo",
  "EMEI Dom Luiz de Nadal",
  "EMEI Humaitá",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Nova Restinga",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "EMEI Vila Tronco",
  "Equipe eMulti SUS",
  "Escadaria da Rua João Manoel",
  "Escola Especial para Surdos Frei Pacífico",
  "Escola Politécnica da PUCRS",
  "Escola Técnica Mesquita",
  "Escritório de Transição",
  "Espaço Memórias",
  "Esquina Democrática",
  "Estação Cristiano Fischer",
  "Estacionamento da EPTC",
  "Estátua do Laçador",
  "Estrada das Furnas",
  "Estrada João de Oliveira Remião",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Expo Favela RS 2024",
  "Exposição de Gravuras Portuguesas",
  "Exposição Maresia",
  "Extremo Sul",

  "Farmácia Distrital Modelo",
  "Farmácia Distrital Murialdo",
  "Farmácia Móvel",
  "Feira de Oportunidades",
  "Feira Fora da Feira",
  "Festa de Natal dos Acolhidos de Porto Alegre",
  "Festa dos Idosos da Fasc",
  "Festuris 2018",
  "Fique Sabendo Jovem",
  "Formação de Multiplicadores",
  "Fórum Desenvolvimento Sustentável no Sul",
  "Fórum Social Mundial da População Idosa",
  "Frente Parlamentar de Segurança",
  "Funcriança",
  "Fundação Iberê Camargo",

  "Gabinete da SMDSE",
  "Galera Curtição",
  "Galpão da Hospitalidade",
  "GeraçãoPoa",
  "GeraEncontro",
  "Ginásio do Colégio Protásio Alves",
  "Ginásio Lupi Martins",
  "Ginásio Tesourinha",
  "Grêmio Foot-Ball Porto Alegrense",
  "Grupo Executivo Municipal das Ações de Contingência de Combate ao AEDES",

  "Heineken F1 Experience",
  "Hortomercado Parobé",
  "Hospital Fêmina",
  "Hospital Moinhos de Vento",
  "Hospital Porto Alegre",
  "Hospital Santa Ana",
  "Hotel Laghetto Stilo Higienópolis",
  "Hotel Serra Park Gramado",

  "I Love Poa",
  "Instituto Caldeira",
  "Instituto Ling",
  "Instituto Penal Feminino de Porto Alegre",

  "Janeiro Branco",
  "Jardins do DMAE",

  "Kombina",

  "Largo David Coimbra",
  "Largo Zumbi dos Palmares",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Lomba do Pinheiro",
  "Loteamento Santa Terezinha",

  "Maio Amarelo",
  "Maio Vermelho",
  "Memorial do Rio Grande do Sul",
  "Mercado do Bom Fim",
  "Mês do Idoso",
  "Mexatchê",
  "Missão Estados Unidos",
  "Missão Xangai 2018",
  "Moinhos de Vento",
  "Monumento a Júlio de Castilhos",
  "Morro da Apamecor",
  "Morro Ricaldone",
  "Morro Santa Tereza",
  "Mostra Acústicos e Elétricos",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Museu do Hip Hop",

  "Nação Kids",
  "Natal dos Encantos",
  "Nós na Praça",
  "Nova Ponte do Guaíba",

  "OdontoSesc",
  "Ônibus de Natal da Carris 2018",
  "Ópera-rock Revolução Farroupilha",
  "Operação Bota-Fora",
  "Operação Ferro-Velho",
  "Operação Inverno",
  "Operação Jaguar",
  "Operação Natal da Retomada",
  "Operação Sossego",
  "Operação Viagem Segura",
  "Orçamento Participativo 2018",
  "Orla de Ipanema",

  "Pacto Alegre",
  "Parque Chico Mendes",
  "Parque Germânia",
  "Parque Marinha do Brasil",
  "Parque Natural Municipal Morro do Osso",
  "Pedestre Idoso",
  "Pier do Barra Shopping Sul",
  "Plano de Superação da Situação de Rua",
  "Plataforma Reconstruir Porto Alegre",
  "Plaza São Rafael",
  "Plenário 20 de Setembro",
  "Plenário Otávio Rocha",
  "POA Solidária",
  "Polícia Rodoviária Federal",
  "Ponte do Guaíba",
  "Porão do Paço",
  "Porto Alegre",
  "Praça Darcy Azambuja",
  "Praça Doutor Lopes Trovão",
  "Praça Mafalda Veríssimo",
  "Praça Província de Shiga",
  "Praia de Belas",
  "Praia do Lami",
  "Prefeitos de Praça",
  "Prefeitura nos Bairros",
  "Prêmio MPT na Escola",
  "Programa Municipal de Rastreamento de Câncer Colorretal",
  "Projeto 100% Digital",
  "Projeto Jogo Limpo",
  "Projeto Pescar",
  "Projeto Source",
  "Prometas",

  "Quadrilátero Central",

  "Rádio Gaúcha",
  "Rede Calabria",
  "Rede Pampa de Comunicação",
  "Reserva Biológica do Lami José Lutzenberger",
  "Residencial São Guilherme",
  "Roda de Conversa Inclusiva",
  "Rua Camoati",
  "Rua Cecília Meireles",
  "Rua Francisco Petuco",
  "Rua José Pedro Boessio",

  "Sala Álvaro Moreyra",
  "Sala Cecy Frank",
  "Sala da Fonte",
  "Sala de Reuniões da SMPG",
  "Sala de Treinamento da SMPG",
  "Sala P. F. Gastal",
  "Salão Alberto Pasqualini",
  "Salão Negrinho do Pastoreio",
  "Santa Casa de Misericórdia de Porto Alegre",
  "Sarau Café com Letras",
  "Saúde da População Negra",
  "Sede da SMED",
  "Sede da SMPG",
  "Sede do Comando Militar do Sul",
  "Sede do Previmpa",
  "Sede social da SERGS",
  "Seletiva no Contêiner",
  "Semana Cidade Limpa",
  "Semana da Água",
  "Semana da Consciência Negra",
  "Semanas Internacionais",
  "Seminário Boas Práticas na Gestão de Trânsito dos Municípios",
  "Seminário Compliance",
  "Seminário da Rede de Acolhimento Municipal – Criança e Adolescente",
  "Seminário do Comitê de Aleitamento Materno e Alimentação Complementar Saudável de Porto Alegre",
  "Seminário Nacional de Trânsito - Mobilidade Sustentável, Educação, e Segurança",
  "Seminário pela Visibilidade Trans",
  "Seminário POA 2020",
  "Seminário Povos Indígenas e Saúde: Um Corpo São",
  "Shopping Total",
  "Show de Talentos da FASC",
  "Sindilojas",
  "Sociedade Libanesa de Porto Alegre",
  "Sport Club Internacional",
  "STU Pro-Tur 2025",

  "Teatro Carlos Carvalho",
  "Teatro da Unisinos",
  "Teatro de Câmara Túlio Piva",
  "Teatro do Bourbon Country",
  "Teatro do CIEE",
  "Teatro Renascença",
  "TelessaúdeRS",
  "Terminal Praia de Belas",
  "Terminal Triângulo",
  "Todos Contra O Assédio",
  "Todos Somos Porto Alegre",
  "Travessa dos Venezianos",
  "Trensurb",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Tributo a Elis Regina",
  "Tristeza",
  "Túnel da Conceição",

  "Unidade de Saúde 1º de Maio",
  "Unidade de Saúde Alto Embratel",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Fradique Vizeu",
  "Unidade de Saúde Orfanotrófio",
  "Unidade de Saúde Osmar Freitas",
  "Unidade de Saúde Panorama",
  "Unidade de Saúde Ponta Grossa",
  "Unidade de Saúde Santo Alfredo",
  "Unidade de Saúde São Carlos",
  "Unidade de Saúde Tristeza",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "UPA Moacyr Scliar",
  "Usina do Gasômetro",

  "Viaduto da Conceição",
  "Viaduto Dom Pedro I",
  "Viaduto Otávio Rocha",
  "Vigidesastres",
  "Vila dos Ferroviários",
  "Vila dos Sargentos",
  "Vila Jardim",
  "Vila Minuano",
  "Vila Monte Cristo",
  "Viva o Centro a Pé",
  "Viva Porto Alegre a Pé",

  "WhatsApp",
];
