// List of tags for which the category is the same
export const sameNameTags = [
  "1ª Expo-Feira Náutica Almirante Tamandaré 2019",

  "A Cara da Obra",
  "Abrigo de Animais da EPTC",
  "Abrigo Residencial AR 7",
  "Ação Rua",
  "Adote um Escritor",
  "Albergue Felipe Diehl",
  "Anfiteatro Pôr do Sol",
  "Aplicativo 156+POA",
  "Área Azul",
  "Arena do Grêmio",
  "Arroio Cavalhada",
  "Arroio Dilúvio",
  "Arroio Sarandi",
  "Associação Comunitária Núcleo Esperança",
  "Associação Hospitalar Vila Nova",
  "Atelier Livre Xico Stockinger",
  "Asilo Padre Cacique",
  "Atenção Especializada à Saúde",
  "Auditório Araújo Vianna",
  "Auditório da EPTC",
  "Auditório do Global Tecnopuc",
  "Auditório do prédio II da UFCSPA",
  "Avenida Assis Brasil",
  "Avenida Coronel Marcos",
  "Avenida Eduardo Prado",
  "Avenida Goethe",
  "Avenida Nilo Peçanha",
  "Avenida Nonoai",
  "Avenida Padre Cacique",
  "Avenida Sertório",
  "Avenida Severo Dullius",
  "Avenida Venâncio Aires",

  "Balada Segura",
  "Banco de Talentos",
  "Biblioteca Ecológica Infantil Maria Dinorah",
  "Bikepoa",
  "Bolsa Família",
  "Brechocão",
  "Brique da Redenção",

  "Cais Mauá",
  "Caixa Econômica Federal",
  "Câmara Rio-Grandense do Livro",
  "Caminho do Gol",
  "Caminho dos Jacarandás",
  "Capester",
  "Casa de Apoio Viva Maria",
  "Casa de Cultura Mario Quintana",
  "Casa do Gaúcho",
  "Casa Lar do Idoso",
  "Cecoflor",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural Usina do Gasômetro",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Saúde IAPI",
  "Centro de Saúde Modelo",
  "Centro de Saúde Murialdo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro de Valorização da Vida",
  "Chikungunya",
  "Cinemateca Capitólio",
  "Clássicos na Pinacoteca",
  "Colégio Militar de Porto Alegre",
  "Colônia de Pescadores Z5",
  "Comando Militar do Sul",
  "Companhia Jovem de Dança",
  "Companhia Municipal de Dança",
  "Complexo Hospitalar Santa Casa",
  "Conferência Municipal do Meio Ambiente",
  "Consultório na Rua",
  "Cootravipa",

  "Desafio Microrrevoluções Urbanas",
  "Descida da Borges",
  "DermatoNet",
  "Dia D de Vacinação",
  "Dia do Gari",

  "Edifício Intendente José Montaury",
  "Eixo Baltazar",
  "Embratel",
  "EMEF Deputado Marcírio Goulart Loureiro",
  "EMEF Gabriel Obino",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "EMEF Mario Quintana",
  "EMEF Migrantes",
  "EMEF Porto Novo",
  "EMEF Professora Ana Íris do Amaral",
  "EMEF Vereador Antônio Giúdice",
  "EMEF Vila Monte Cristo",
  "EMEI Dom Luiz de Nadal",
  "EMEI Humaitá",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Nova Restinga",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "Equipe eMulti SUS",
  "Escola Especial para Surdos Frei Pacífico",
  "Esquina Democrática",
  "Estrada das Furnas",
  "Estrada João de Oliveira Remião",
  "ETA Moinhos de Vento",
  "ETA São João",
  "Extremo Sul",

  "Farmácia Distrital Modelo",
  "Farmácia Móvel",
  "Feira de Oportunidades",
  "Fique Sabendo Jovem",
  "Formação de Multiplicadores",
  "Fórum Social Mundial da População Idosa",
  "Fundação Iberê Camargo",

  "Galpão da Hospitalidade",
  "GeraçãoPoa",
  "GeraEncontro",
  "Ginásio do Colégio Protásio Alves",
  "Ginásio Lupi Martins",
  "Ginásio Tesourinha",
  "Grêmio Foot-Ball Porto Alegrense",

  "Heineken F1 Experience",
  "Hortomercado Parobé",
  "Hospital Moinhos de Vento",
  "Hospital Santa Ana",
  "Hotel Laghetto Stilo Higienópolis",

  "I Love Poa",
  "Ilha da Pintada",
  "Instituto Caldeira",
  "Instituto Ling",
  "Instituto Penal Feminino de Porto Alegre",

  "Janeiro Branco",
  "Jardins do DMAE",

  "Kombina",

  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Lomba do Pinheiro",

  "Maio Amarelo",
  "Maio Vermelho",
  "Memorial do Rio Grande do Sul",
  "Mercado do Bom Fim",
  "Mês do Idoso",
  "Mexatchê",
  "Missão Xangai 2018",
  "Moinhos de Vento",
  "Monumento a Júlio de Castilhos",
  "Morro Ricaldone",
  "Mostra Acústicos e Elétricos",
  "Museu de Porto Alegre Joaquim Felizardo",

  "Natal dos Encantos",
  "Nova Ponte do Guaíba",

  "OdontoSesc",
  "Operação Bota-Fora",
  "Operação Inverno",
  "Operação Jaguar",
  "Orçamento Participativo 2018",
  "Orla de Ipanema",

  "Palácio Piratini",
  "Parque Chico Mendes",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Parque Natural Municipal Morro do Osso",
  "Pedestre Idoso",
  "Pier do Barra Shopping Sul",
  "Plano de Superação da Situação de Rua",
  "Plataforma Reconstruir Porto Alegre",
  "Plaza São Rafael",
  "Polícia Rodoviária Federal",
  "Ponte do Guaíba",
  "Porão do Paço",
  "Porto Alegre",
  "Praça Darcy Azambuja",
  "Praça Doutor Lopes Trovão",
  "Praça Mafalda Veríssimo",
  "Praça Província de Shiga",
  "Praia de Belas",
  "Prefeitos de Praça",
  "Prefeitura nos Bairros",
  "Prêmio MPT na Escola",
  "Programa Municipal de Rastreamento de Câncer Colorretal",
  "Projeto 100% Digital",
  "Projeto Jogo Limpo",
  "Projeto Pescar",
  "Prometa 2017",
  "Prometas",

  "Rede Calabria",
  "Reserva Biológica do Lami José Lutzenberger",
  "Residencial São Guilherme",
  "Rua Camoati",
  "Rua Cecília Meireles",
  "Rua Francisco Petuco",
  "Rua José Pedro Boessio",

  "Sala Álvaro Moreyra",
  "Sala Cecy Frank",
  "Sala da Fonte",
  "Sala de Treinamento da SMPG",
  "Sala P. F. Gastal",
  "Santa Casa de Misericórdia de Porto Alegre",
  "Sarau Café com Letras",
  "Saúde da População Negra",
  "Sede da SMPG",
  "Seletiva no Contêiner",
  "Semana Cidade Limpa",
  "Semana da Água",
  "Semanas Internacionais",
  "Seminário Nacional de Trânsito - Mobilidade Sustentável, Educação, e Segurança",
  "Seminário Povos Indígenas e Saúde: Um Corpo São",
  "Shopping Total",
  "Show de Talentos da FASC",
  "Sindilojas",
  "Sociedade Libanesa de Porto Alegre",
  "Sport Club Internacional",

  "Teatro Carlos Carvalho",
  "Teatro de Câmara Túlio Piva",
  "Teatro do CIEE",
  "Teatro Renascença",
  "TelessaúdeRS",
  "Terminal Triângulo",
  "Termo de Adoção de Verde Complementar",
  "Todos Contra O Assédio",
  "Todos Somos Porto Alegre",
  "Trensurb",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Tributo a Elis Regina",
  "Tristeza",
  "Túnel da Conceição",

  "Unidade de Saúde 1º de Maio",
  "Unidade de Saúde Alto Embratel",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Fradique Vizeu",
  "Unidade de Saúde Orfanotrófio",
  "Unidade de Saúde Osmar Freitas",
  "Unidade de Saúde Ponta Grossa",
  "Unidade de Saúde Santo Alfredo",
  "Unidade de Saúde São Carlos",
  "Unidade de Saúde Tristeza",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "UPA Moacyr Scliar",
  "Usina do Gasômetro",

  "Viaduto da Conceição",
  "Viaduto Otávio Rocha",
  "Vigidesastres",
  "Vila dos Ferroviários",
  "Vila dos Sargentos",
  "Vila Jardim",
  "Vila Minuano",
  "Vila Monte Cristo",
  "Viva o Centro a Pé",

  "WhatsApp",
];
