export const tagReplacements = {
  "“Tamo Junto na Rua”": ["Situação de rua"],
  "População de Rua": ["Situação de rua"],
  "População em Situação de Rua": ["Situação de rua"],
  "25º POA Em Cena": ["Poa Em Cena"],
  "Em Cena": ["Poa Em Cena"],
  "POA Em Cena": ["Poa Em Cena"],
  "Smc - Poa Em Cena": ["Poa Em Cena"],
  "3º Inclusão em Cena": ["Inclusão Em Cena"],
  "Projeto Inclusão em Cena 2018": ["Inclusão Em Cena"],
  "64ª Edição da Feira do Livro de Porto Alegre": ["Feira do Livro"],
  "70ª Feira do Livro de Porto Alegre": ["Feira do Livro"],
  "Totem de atendimento 156": ["Feira do Livro"],
  "90 Anos da Cinemateca Capitólio": ["Cinemateca Capitólio"],
  "relações Institucionais": ["Smri"],
  "Relações Institucionais": ["Smri"],
  "Relações Institucional": ["Smri"],
  "Secretaria Municipal de Relações Institucionais (SMRI)": ["Smri"],
  "Acampamento 2018": ["Acampamento Farroupilha"],
  "Acampamento Farropilha": ["Acampamento Farroupilha"],
  "Ação Conjunta de Fiscalização": ["Fiscalização"],
  "Fiscalização do Transporte Resíduos da Construção Civil": ["Fiscalização"],
  "Ação de Pulverização de Inseticida": ["Bloqueio químico"],
  "Ação Mais Comunidade": ["Projeto Mais Comunidade"],
  "Programa Mais Comunidade": ["Projeto Mais Comunidade"],
  "Água e Esgotos": ["DMAE"],
  "Água e Esgoto": ["DMAE"],
  "Departamento Municipal de Água e Esgotos (DMAE)": ["DMAE"],
  "Análises clínicas": ["Laboratórios Municipais"],
  "Anfiteatro Moacyr Scliar": ["Teatro Moacyr Scliar"],
  "Auditório do prédio II da UFCSPA": ["Teatro Moacyr Scliar"],
  "Animal silvestre": ["Fauna"],
  "Apresentação Calendário Pagamento IPTU 2019": ["IPTU"],
  "Guias de Pagamento de Tributos": ["IPTU"],
  "Repavimentação asfáltica": ["Pavimentação"],
  "Assembléia Legislativa": ["Assembleia Legislativa"],
  "Assistencia Social": ["Serviço Social"],
  "Assistência Social": ["Serviço Social"],
  "Assistência Social e Cidadania": ["Fasc"],
  "Fundação de Assistência Social e Cidadania – Fasc": ["Fasc"],
  "Avaliação dos Serviços Públicos Municipais": ["Carta de Serviços"],
  "Auditório Marcelo Dario Kifne - MP-RS": ["Auditório do Ministério Público"],
  "Bairro Centro Histórico": ["Centro Histórico"],
  "Bairro Coronel Aparício Borges": ["Bairro Cel. Aparício Borges"],
  "Bairro Petrópolis": ["Petrópolis"],
  "bairro Restinga": ["Bairro Restinga"],
  "Bairro Santa Teresa": ["Bairro Santa Tereza"],
  "Bairro Vila Ipiranga": ["Vila Ipiranga"],
  "Bairro Vila Nova": ["Vila Nova"],
  "Benchmarking do Governo do Rio Grande do Norte": ["Visita"],
  "Viagem à Brasília": ["Visita"],
  "Visita de Cortesia": ["Visita"],
  "Visita dos Alunos do IFRS da Restinga ao Poa.Hub": ["Visita"],
  "visita institucional": ["Visita"],
  "Visita Técnica": ["Visita"],

  "Biblioteca do Parcão": ["Biblioteca Ecológica Infantil Maria Dinorah"],
  "Câmara Municipal de Porto Alegre (CMPA)": ["Legislativo"],
  "Câmara de Vereadores": ["Legislativo"],
  "Câmeras de segurança": ["Videomonitoramento"],
  "Campus da Unisinos Porto Alegre": ["Unisinos"],
  "Capitão de Mar e Guerra, Rafael Silva dos Santos": [
    "Rafael Silva dos Santos",
  ],
  "Cássia Carpes": ["Cassiá"],
  "vereador Cassiá Carpes": ["Cassiá"],
  "Celebração do Dia da Criança": ["Dia da Criança"],
  "Dia das Crianças": ["Dia da Criança"],
  "Centro Integrado de Comando": ["CEIC"],
  "Centro Integrado de Comando da Cidade de Porto Alegre (CEIC)": ["CEIC"],
  "Centro Municipal de Cultura": ["Centro de Cultura Lupicínio Rodrigues"],
  "Cerimônia de posse gestão 2025/2028": ["Posse"],
  "Posse da  Comissão de Saúde e Segurança da Fasc": ["Posse"],
  "Posse da Comissão de Saúde e Segurança do Trabalho da SMRI": ["Posse"],
  "Posse da Procuradora Municipal": ["Posse"],
  "Posse Novos Procuradores-Gerais do Município": ["Posse"],
  "Posse Novos Secretários Municipais": ["Posse"],
  "Sessão especial de posse da Mesa Diretora de 2019": ["Posse"],
  "Chefe de Gabinete": ["André Coronel"],
  "Ciclo de Palestras da Transparência": ["Palestra"],
  "Circuito Urbano": ["Circuito Urbano EPTC"],
  "Circulação e Transporte": ["Transporte"],
  "Integração Metropolitana de Transporte": ["Transporte"],
  "Trânsito e Circulação": ["Transporte"],
  "Trânsito e Circulaçâo": ["Transporte"],
  "Transito e Transporte": ["Transporte"],
  "Transporte e Circulaçao": ["Transporte"],
  "Transporte e Circulação": ["Transporte"],
  "Transporte Metropolitano": ["Transporte"],
  "Companhia Carris Porto Alegrense": ["Carris"],
  "Companhia de Processamento de Dados do Município (Procempa)": ["Procempa"],
  "Conselho da Procempa": ["Procempa"],
  "Conselho Superior da PGM": ["PGM"],
  "Gabinete da Procuradoria": ["PGM"],
  "Procuradoria Geral": ["PGM"],
  "Procuradoria Geral do Município": ["PGM"],
  "Procuradoria-Geral do Município de Porto Alegre": ["PGM"],
  "Consul Honorária dos Países Baixos em Porto Alegre": ["Consulado"],
  "Cônsul-Geral do Japão em Curitiba, Sr. Yasuhiro Mitsu.": ["Yasuhiro Mitsu"],
  "Cônsul-Geral dos Estados Unidos em Porto Alegre": ["Jason Green"],
  "Cônsul-Geral dos Estados Unidos, Sr. Jason Green.": ["Jason Green"],
  "Coordenação de Operações Especiais (COE)": ["EPTC"],
  "Empresa Pública de Transporte e Circulação (EPTC)": ["EPTC"],
  "Eptc -": ["EPTC"],
  "corpo de bombeiros": ["Bombeiros"],
  "Cultura e Economia Criativa": ["Cultura Economia Criativa"],
  "Secretaria Municipal de Cultura (SMC)": ["Cultura Economia Criativa"],
  "Curso de Formação de Diretores da SMED": ["Curso de Formação"],
  "Defesa Cívil": ["Defesa Civil"],
  "Defesa Civil de Porto Alegre-RS": ["Defesa Civil"],
  "Departamento Municipal de Habitação ( Demhab)": ["Demhab"],
  "Departamento Municipal de Habitação (Demhab)": ["Demhab"],
  "Departamento Municipal de Limpeza Urbana (DMLU)": ["DMLU"],
  "Limpeza Urbana": ["DMLU"],
  "Deputado Estadual Fixinha": ["João Fischer"],
  "Desenvolviment Econômico": ["Smde"],
  "Desenvolvimento Econômico": ["Smde"],
  "Desenvolvimento Economico e Esporte": ["Smde"],
  "Desenvolvimento Econômico e Turismo": ["Smde"],
  "Secretaria Municipal de Desenvolvimento Econômico (SMDE)": ["Smde"],
  "SMDE - Secretaria Municipal de Desenvolvimento Econômico": ["Smde"],
  "Desenvolvimento Social": ["Smdse"],
  "Desenvolvimento Social e Esporte": ["Smdse"],
  "SMDSE - Desenvolvimento Social e Esporte": ["Smdse"],
  "Secretaria Municipal de Desenvolvimento Social e Esporte (SMDSE)": ["Smdse"],
  "Dia D": ["Dia D de Vacinação"],
  "Diretor Regional do SESC": ["Sesc"],
  "diretora-presidente": ["Helen Machado"],
  "Doação de Equipamentos": ["Doação"],
  "Doações de Materiais": ["Doação"],
  "Entrega de Doações": ["Doação"],
  "Entrega de kits de brinquedos doados pela Fundação Abrinq": ["Doação"],
  "Editais para Realização do Carnaval de Rua/POA 2019": ["Carnaval de Rua"],
  "Embaixador de Luxemburgo no Brasil": ["Carlo Krieger"],
  "Emef Migrantes": ["EMEF Migrantes"],
  "Emef Vereador Antonio Giúdice": ["EMEF Vereador Antônio Giúdice"],
  "Emef Vila Montecristo": ["EMEF Vila Monte Cristo"],
  "Empreendimento para o 4º distrito": ["4º Distrito"],
  "Prefeitura e DMAE anunciam obras no 4º Distrito": ["Obras", "4º Distrito"],
  "Quarto Distrito": ["4º Distrito"],
  "Escola Municipal de Educação infantil Humaitá": ["EMEI Humaitá"],
  "Espaço Hortomercado Parobé": ["Hortomercado Parobé"],
  "Espaço Infantil": ["Criança"],
  "Esporte Lazer e Juventude": ["Esporte e Lazer"],
  "Esporte, Lazer e Juventude": ["Esporte e Lazer"],
  "Esportes e Lazer": ["Esporte e Lazer"],
  "Esportes, Recreação e Lazer": ["Esporte e Lazer"],
  "Executivo, Ministro da Saúde Gilberto Occhi": ["Gilberto Occhi"],
  "Expo Favela": ["Expo Favela RS 2024"],
  "Finanças Públicas": ["SMF"],
  "Gabinete da SMF": ["SMF"],
  "Secretaria Municipal da Fazenda (SMF)": ["SMF"],
  "Secretário Municipal da Fazenda (SMF)": ["SMF"],
  "Federação das Indústrias do Estado do Rio Grande do Sul (Fiergs)": [
    "Fiergs",
  ],

  "Festa da Virada": ["Ano Novo"],
  "Programação do Reveillon": ["Ano Novo"],
  "Reveillon 2019": ["Ano Novo"],
  "Réveillon 2025": ["Ano Novo"],
  "Réveillon de Porto Alegre - Pro Ano Nascer Feliz": ["Ano Novo"],
  "Réveillon Porto Alegre": ["Ano Novo"],

  "144ª Festa de Nossa Senhora dos Navegantes": [
    "Festa de Nossa Senhora dos Navegantes",
  ],

  "foto aérea": ["Aéreas"],
  "Imagem Aérea": ["Aéreas"],
  "Frente Nacional dos Prefeitos (FNP)": ["FNP"],
  "Gabinete da Causa Animal": ["Causa Animal"],
  "Gabinete da Causa Animal (GCA)": ["Causa Animal"],
  "Gabinete da Inovação": ["Inovação"],
  "Gabinete de Inovação": ["Inovação"],
  "Gabinete de Inovação (GI)": ["Inovação"],
  "Gabinete da Primeira-Dama": ["Valéria Leopoldino"],
  "Primeira-dama": ["Valéria Leopoldino"],
  "Primeira-dama de Porto Alegre, Valéria Leopoldino": ["Valéria Leopoldino"],
  "General Edson Leal Pujol": ["Edson Leal Pujol"],
  "general Hertz Pires do Nascimento": ["Hertz Pires do Nascimento"],
  "Gestão e Planejamento": ["Smpg"],
  "Planejamento e Gestão": ["Smpg"],
  "Secretaria Municipal de Planejamento e Gestão (SMPG)": ["Smpg"],
  "Gestores dos CRIPs": ["CRIPs"],
  "Governador José Ivo Sartori": ["José Ivo Sartori"],
  "Grupo de Combate ao Tabagismo": ["Tabagismo"],
  "Grupo de Trabalho da Orla Moacyr Scliar": ["Orla Moacyr Scliar"],
  "Parque Urbano da Orla Moacyr Scliar": ["Orla Moacyr Scliar"],
  "Grupo POA Solidárias": ["POA Solidária"],
  "Representantes do POA Solidária": ["POA Solidária"],
  "Projeto Poa Solidária": ["POA Solidária"],
  "Habitação Regularização Fundiária": ["SMHARF"],
  "Habitação e Regularização Fundiária": ["SMHARF"],
  "hipertensão arterial": ["hipertenso"],
  "Hortas Comunitárias": ["horta"],
  "IberCup World 2019": ["IberCup"],
  "Torneio Internacional de Futebol Infantil": ["IberCup"],
  "Inauguração do Hospital Santa Ana": ["Hospital Santa Ana"],
  "Infraestrutura e Mobilidade": ["Smim"],
  "Infraestrutura e Mobilidade Urbana": ["Smim"],
  "Mobilidade Urbana": ["Smim"],
  "Secretaria Municipal de Mobilidade Urbana (SMMU)": ["Smim"],
  "SMIM - Infraestrutura e Mobilidade Urbana": ["Smim"],
  "Infraestrutura e Urbanismo": ["Smoi"],
  "Obras e Infraestrutura": ["Smoi"],
  "Secretaria Municipal de Obras e Infraestrutura (SMOI)": ["Smoi"],
  "IST Aids": ["Aids"],
  "Lançamento do Pacto Pela Inovação - Pacto Alegre": ["Pacto Alegre"],
  "Pacto Pela Inovação": ["Pacto Alegre"],
  "LGBTQIA+": ["LGBT"],
  "Livro e Literatura": ["Literatura"],
  "Meio Ambiente e Sustentabilidade": ["SMAMS"],
  "Meio Ambiente Sustentabilidade": ["SMAMS"],
  "Meio Ambiente Urbanismo e Sustentabilidade": ["Smamus"],
  "Meio Ambiente, Urbanismo e Sustentabilidade": ["Smamus"],
  "Mercado Público Central": ["Mercado Público"],
  "Ministro de Estado da Infraestrutura Tarcísio Freitas": ["Tarcísio Freitas"],
  "Museu Iberê Camargo": ["Fundação Iberê Camargo"],
  "Museu Joaquim Felizardo": ["Museu de Porto Alegre Joaquim Felizardo"],
  "Obras de implantação da adutora da Estrada Antonio Borges": ["Obras"],
  "Parcerias Estratégicas": ["Smpe"],
  "Parque Harmonia": ["Parque Maurício Sirotsky Sobrinho (Harmonia)"],
  "Parque Mascarenhas de Moraes": ["Parque Marechal Mascarenhas de Moraes"],
  "Parque Moinhos de Vento (Parcão)": ["Parcão"],
  "Permissionários do Serviço de Táxis": ["Táxi"],
  "Táxis Novos": ["Táxi"],
  "Plantio Urbano Sustentável": ["Plantio Sustentável do DMLU"],
  "Pókemon GO Safari Zone": ["Pokémon GO"],
  "Pontifícia Universidade Católica do RS (PUCRS)": ["PUCRS"],
  "População Negra": ["Saúde da População Negra"],
  "Povo Negro": ["Saúde da População Negra"],
  "Promotores da Saúde da População Negra": ["Saúde da População Negra"],
  "Porto Alegre-RS": ["Porto Alegre"],
  "Porto Verão Alegre 2019": ["Porto Verão Alegre"],
  "Praça Marechal Deodoro (Matriz)": ["Praça da Matriz"],
  "Prédio Intendente José Montaury": ["Edifício Intendente José Montaury"],
  "prefeita em exercício, Betina Worm": ["Betina Worm"],
  "Vice-prefeita, Betina Worm": ["Betina Worm"],
  "Vice-prefeita de Porto Alegre, Betina Worm": ["Betina Worm"],
  "prefeito de Florianópolis, Topázio Neto": ["Topázio Neto"],
  "presidente CEEE Equatorial, Riberto Barbarena": ["Riberto Barbanera"],
  "Presidente da República Luiz Inácio Lula da Silva": [" Lula"],
  "Presidente das Mantenedoras Maristas do Sul": ["Inacio Etges"],
  "presidente do Grêmio Foot-Ball Porto Alegrense": ["Romildo Bolzan Júnior"],
  "Procuradora-geral do município Eunice Nequete": ["Eunice Nequete"],
  "Produtor Rural": ["Zona Rural"],
  "Propriedades Rurais": ["Zona Rural"],
  "Programa Adote um Escritor": ["Adote um Escritor"],
  "Projeto Adote um Escritor": ["Adote um Escritor"],
  "Projeto Clássicos na Pinacoteca": ["Clássicos na Pinacoteca"],
  "Projeto Feira Fora da Feira": ["Feira Fora da Feira"],
  "Retratos Oficiais": ["Retrato"],

  "Secretária Denise Russo": ["Denise Russo"],
  "secretária Juliana Castro": ["Juliana Castro"],
  "secretária municipal da Fazenda (SMF), Ana Pellini": ["Ana Pellini"],
  "Secretaria Municipal de Desenvolvimento Social (SMDS)": ["Smds"],
  "Secretaria Municipal de Educação (SMED)": ["SMED"],
  "Secretaria Municipal de Inclusão e Desenvovimento Humano": ["Smidh"],
  "secretaria municipal de Inlcusão e Desenvolvimento Humano (SMIDH)": [
    "Smidh",
  ],
  "Secretaria Municipal de Saúde (SMS)": ["SMS"],
  "Secretaria Municipal de Segurança (SMSEG)": ["Smseg"],
  "Smseg - Segurança": ["Smseg"],
  "SMSEG - Segurança": ["Smseg"],
  "Secretaria Municipal de Serviços Urbanos (SMSURB)": ["SMSURB"],
  "Secretário Municipal de Serviços Urbanos (SMSUrb)": ["SMSURB"],
  "Serviços Urbanos": ["SMSURB"],
  Smurb: ["SMSURB"],
  "Secretaria Municipal de Transparência e Controladoria (SMTC)": ["Smtc"],
  "SMTC - Transparência e Controladoria Geral": ["Smtc"],
  "Transparência e Controladoria": ["Smtc"],
  "Transparência e Controladoria Geral": ["Smtc"],

  "Secretária Nádia Gerhard": ["Comandante Nádia"],
  "secretária-adjunta da SMED Ivana Genro": ["Ivana Genro"],

  "Secretário da SMAMS, Maurício Fernandes": ["Maurício Fernandes"],
  "Secretário Eduardo Cidade": ["Eduardo Cidade"],
  "Secretário Estadual dos Transportes Juvir Costella": ["Juvir Costella"],
  "Secretário municipal de Educação, Leonardo Pascoal": ["Leonardo Pascoal"],
  "Secretário Municipal da Educação (SMED), Maurício Cunha": ["Maurício Cunha"],
  "secretário municipal de Esporte e Lazer, Professor Tovi": ["Professor Tovi"],
  "Secretário-adjunto municipal de Governança Local e Coordenação Política, Luciano Marcantonio":
    "Luciano Marcantônio",

  "Sinalização de trânsito": ["Sinalização viária"],
  "sinalização semafórica": ["Semáforos"],
  "Smc -": ["Smc"],
  "SMC - FUMPROARTE comemora 25 anos": ["25 Anos do  FUMPROARTE"],
  "Programação de Novembro": ["Programação Cultural"],
  "Teatro da AMRIGS": ["Centro de Eventos da Amrigs"],
  "Terminal Parobé": ["Praça Parobé"],
  "Vereador Giovane Byl": ["Giovane Byl"],
  "Vereador Moisés Barboza": ["Moisés Barboza"],
  "Viagem à Europa": ["Missão Internacional"],
  "viagem internacional": ["Missão Internacional"],
  "Viagem Segura EPTC": ["Operação Viagem Segura"],
  "Vice-prefeito de Porto Alegre, Ricardo Gomes": ["Ricardo Gomes"],
  "vice-prefeito Ricardo Gomes": ["Ricardo Gomes"],
};
