export const validTags = [
  "relações Institucionais",
  "(EBAB) Moinhos de Vento",
  "(Emei JP) Cantinho Amigo",
  "(Emei JP) Meu Amiguinho",
  "(Emei) Florência Vurlod Socias",
  "#eufaçopoa",
  "#proconpoaresponde",
  "“Tamo Junto na Rua”",

  "1ª Expo-Feira Náutica Almirante Tamandaré 2019",
  "1ª Faixa Reversível semafórica de Porto Alegre",
  "1ª Feira da Agricultura Familiar - Agrifam",
  "1º Festival de Arte e Cultura Senegalesa",
  "1º Fórum das Cidades Inteligentes, Humanizadas e Inovadoras - Smart Cities",
  "11ª Conferência Municipal dos Direitos da Criança e do Adolescente",
  "126 Anos da Guarda Municipal de Porto Alegre",
  "14ª edição do Campeonato Porto Alegre de Handebol 2018",
  "14ª Gincana Ambiental",
  "144ª Festa de Nossa Senhora dos Navegantes",
  "15ª Chegada do Papai Noel - Abertura oficial do Natal de Porto Alegre",
  "149 anos do Mercado Público",
  "17ª Edição dos Jogos Municipais da Terceira Idade",
  "2° Fórum de Logística Sustentável",
  "2º Seminário de Comunicação da Prefeitura de Porto Alegre",
  "20 Anos da Mostra dos Servidores do DMAE",
  "245ª Feira do Peixe de Porto Alegre",
  "25 Anos do  FUMPROARTE",
  "25ª Corrida pela Vida",
  "25º POA Em Cena",
  "3ª Edição da Mostra Cultural Eixo Baltazar",
  "3º Inclusão em Cena",
  "30 Anos da Defesa Civil",
  "30 Anos da Kinder",
  "32º Festival de Arte da Cidade de Porto Alegre",
  "34ª edição da entrega da Láurea Engenheiro do ano da Sociedade de Engenharia do Rio Grande do Sul",
  "34ª Feira de Natal do Bom Fim",
  "34ª Festa do Pêssego Municipal",
  "4º Distrito",
  "48º Troféu Seival e 29ª Regata Farroupilha",
  "59º Festival Hípico Noturno em Porto Alegre",
  "64ª Edição da Feira do Livro de Porto Alegre",
  "70ª Feira do Livro de Porto Alegre",
  "8ª Edição do Curso de Multiplicadores de Educação para o Trânsito sobre o Pedestre Idoso",
  "8ª Semana Municipal da Água",
  "86 anos do Viaduto Otávio Rocha",
  "90 Anos da Cinemateca Capitólio",

  "A Cara da Obra",
  "A Flauta Mágica",
  "Abandono de Veículos",
  "Abastecimento",
  "Abertura",
  "abordagem",
  "ABRH",
  "Abrigo de Animais da EPTC",
  "Abrigo Residencial AR 7",
  "Abrigos",
  "Abrigos Residenciais - AR 7 e 8",
  "Academia de Samba Praiana",
  "academias ao ar livre",
  "Acampamento 2018",
  "Acampamento Farropilha",
  "Acampamento Farroupilha",
  "Ação Educativa",
  "Ação Conjunta de Fiscalização",
  "Ação de Pulverização de Inseticida",
  "Ação de Natal US Santa Anita",
  "Ação Integrada",
  "Ação Mais Comunidade",
  "Ação Rua",
  "Ação Rua Calábria",
  "Ação Social",
  "Acervo de fotos",
  "Acessibilidade",
  "Acidente",
  "Acidentalidade",
  "Acolhimento",
  "Acolhimento aos Imigrantes Venezuelanos",
  "Administração",
  "Administração e Patrimônio",
  "Administração É Patrimônio",
  "Adoção de animais",
  "Adolescente",
  "Adote um Escritor",
  "Adutora",
  "Adutora Antonio Borges",
  "Aedes aegypti",
  "Aéreas",
  "Aeronáutica",
  "Aeroporto Internacional Salgado Filho",
  "Aeroporto Salgado Filho",
  "Agencia Alemã Deutsche Gesellschaft Internationale Zusammenarbeit - GIZ",
  "Agência Estadual de Regulação dos Serviços Públicos Delegados do Rio Grande do Sul (AGERGS)",
  "Agente de Combate às Endemias (ACE)",
  "Agentes Comunitários de Saúde (ACS)",
  "Agentes de Fiscalização",
  "Agentes de Trânsito",
  "Água",
  "Água e Esgoto",
  "Água e Esgotos",
  "Aids",
  "Alagamento",
  "Albergue Felipe Diehl",
  "Albergue Municipal",
  "Albergues",
  "Álcool  e Outras Drogas",
  "Aldeia do Morro do Osso",
  "Aldeia Indígena",
  "Aldeia Infantil SOS",
  "Aldeia Kaingang",
  "Aleitamento materno",
  "Alerta",
  "Alimentação",
  "Alimento",
  "Aluno",
  "Alunos",
  "Alvará",
  "Amamentação",
  "Ambulância",
  "Ambulantes",
  "Ambulatório Odontológico",
  "Amsterdam",
  "Ana Amélia Lemos",
  "Análises clínicas",
  "André Coronel",
  "Animal silvestre",
  "Aniversário",
  "Aniversário de 6 Anos do CEIC",
  "Aniversário do Parque Moinhos de Vento",
  "Ano Novo",
  "Anúncio de Recursos para a Saúde de Porto Alegre",
  "Anfiteatro Moacyr Scliar",
  "Anfiteatro Pôr do Sol",
  "Apae",
  "Aplicativo 156+POA",
  "Aplicativo (app)",
  "Apreensão",
  "Apresentação",
  "Apresentação Calendário Pagamento IPTU 2019",
  "apuração do Carnaval",
  "Área Azul",
  "Área de risco",
  "Arena do Grêmio",
  "Arquipélago (Ilhas)",
  "Arquivo",
  "Arquivo Histórico Moysés Vellinho",
  "Arrecadação Fiscal",
  "Arroio Cavalhada",
  "Arroio Dilúvio",
  "Arroio Sarandi",
  "Arte Cemiterial",
  "Arte Urbana",
  "Artes Cênicas",
  "Artes Plásticas",
  "Artes Visuais",
  "Artesanato",
  "Árvore",
  "Árvore de Natal",
  "Asfaltamento",
  "Asfalto",
  "Asilo Padre Cacique",
  "ASSAC - Associação Amigos do Cristal",
  "Assembleia de Verão da Famurs 2025",
  "Assembleia Legislativa",
  "Assembléia Legislativa",
  "Assinatura",
  "Assistência Farmacêutica",
  "Assistência Hospitalar",
  "Assistencia Social",
  "Assistência Social",
  "Assistência Social e Cidadania",
  "Associação Brasileira de Shopping Centers (ABRASCE)",
  "Associaçao Comercial de Porto Alegre (ACPA)",
  "Associação Comercial de Porto Alegre (ACPA)",
  "Associação Comunitária Núcleo Esperança",
  "Associação de Dirigentes Cristãos de Empresa de Porto Alegre (ADCE)",
  "Associação do Corpo Consular RS",
  "Associação dos Auditores Fiscais da Receita Municipal de Porto Alegre (Aiamu)",
  "Associação dos Municípios da Região Metropolitana de Porto Alegre (Granpal)",
  "Associação dos Transportadores de Caçamba Estacionárias (ATCE)",
  "Associação Hospitalar Vila Nova",
  "Associação Internacional de Parques Científicos e Áreas de Inovação (IASP)",
  "Associação Recreativa Cultural União da Vila do Iapi",
  "Associação Riograndense de Propaganda (ARP)",
  "Atelier Livre Xico Stockinger",
  "Atenção Ambulatorial, Hospitalar e Urgências",
  "Atenção Básica",
  "Atenção Especializada à Saúde",
  "Atenção Primária à Saúde (APS)",
  "Atendimento",
  "Atendimento de Urgência",
  "Atendimento em Casa",
  "Atendimento Improvisado",
  "Atendimento Infanto-Juvenil",
  "Atendimento Médico",
  "Atividade Alusiva ao Combate à Violência no Trânsito",
  "atividade física",
  "Atletismo",
  "Ato de Apresentação do Programa Família Acolhedora",
  "Ato de Entrega da Obras de Melhoria da Praça Argentina, e da Assinatura do Termo de Adoção da praça pela Santa Casa de Misericórdia de Porto Alegre",
  "Ato de Lançamento do Edital do PMI do Parque Mauricio Sirotsky Sobrinho - Parque Harmonia",
  "Audiência",
  "Auditório Araújo Vianna",
  "Auditório Dante Barone da Assembleia Legislativa",
  "Auditório da Caixa Econômica Federal",
  "Auditório da EPTC",
  "Auditório da ESPM",
  "Auditório da FAMURS",
  "Auditório da Puc",
  "Auditório da SMPE",
  "Auditório da SMED",
  "Auditório da SMPG",
  "Auditório da SMTC",
  "Auditório do Departamento Municipal de Habitação (Demhab)",
  "Auditório do Global Tecnopuc",
  "Auditório do Instituto Cultural",
  "Auditório do Ministério Público",
  "Auditório do Palácio da Polícia",
  "Auditório do prédio II da UFCSPA",
  "Auditório do Previmpa",
  "Auditório do Telessaúde-RS",
  "Auditório do Tribunal Regional Eleitoral (TRE)",
  "Auditório Marcelo Dario Kifne - MP-RS",
  "Augusto Buchweitz",
  "Aula aberta",
  "Aula Inaugural",
  "Autoteste para HIV",
  "Autuação",
  "Av. Mauá",
  "Av. Soledade",
  "Av. Tronco",
  "Av. Wenceslau Escobar",
  "Avaliação dos Serviços Públicos Municipais",
  "Ave",
  "Avenida Assis Brasil",
  "Avenida Bento Gonçalves",
  "Avenida Castello Branco",
  "Avenida Cel Aparício Borges",
  "Avenida Coronel Marcos",
  "Avenida Eduardo Prado",
  "Avenida Goethe",
  "Avenida Ipiranga",
  "Avenida João Pessoa",
  "Avenida Nilo Peçanha",
  "Avenida Nonoai",
  "Avenida Padre Cacique",
  "Avenida Plínio Brasil Milano",
  "Avenida Severo Dullius",
  "Avenida Venâncio Aires",
  "Avenida Voluntários da Pátria",

  "Bairro Agronomia",
  "Bairro Anchieta",
  "Bairro Azenha",
  "Bairro Bela Vista",
  "Bairro Belém Novo",
  "Bairro Belém Velho",
  "Bairro Boa Vista",
  "Bairro Bom Fim",
  "Bairro Bom Jesus",
  "Bairro Campo Novo",
  "Bairro Cavalhada",
  "Bairro Cel. Aparício Borges",
  "Bairro Centro Histórico",
  "Bairro Cidade Baixa",
  "Bairro Coronel Aparício Borges",
  "Bairro Cristal",
  "Bairro Cruzeiro",
  "Bairro Farrapos",
  "Bairro Floresta",
  "Bairro Glória",
  "Bairro Guarujá",
  "Bairro Hípica",
  "Bairro Humaitá",
  "Bairro IAPI",
  "Bairro Ipanema",
  "Bairro Jardim Botânico",
  "Bairro Jardim Carvalho",
  "Bairro Jardim Planalto",
  "Bairro Lami",
  "Bairro Lomba do Pinheiro",
  "Bairro Mário Quintana",
  "Bairro Medianeira",
  "Bairro Menino Deus",
  "Bairro Moinhos de Vento",
  "Bairro Navegantes",
  "Bairro Nonoai",
  "Bairro Partenon",
  "Bairro Passo das Pedras",
  "Bairro Petrópolis",
  "Bairro Ponta Grossa",
  "Bairro Praia de Belas",
  "bairro Restinga",
  "Bairro Restinga",
  "Bairro Rubem Berta",
  "Bairro Santana",
  "Bairro São Geraldo",
  "Bairro São João",
  "Bairro São José",
  "Bairro Santa Teresa",
  "Bairro Santa Tereza",
  "Bairro Santo Antônio",
  "Bairro Sarandi",
  "Bairro Teresópolis",
  "Bairro Tristeza",
  "Bairro Vila Farrapos",
  "Bairro Vila Ipiranga",
  "Bairro Vila Nova",
  "Balada Segura",
  "Balanço",
  "Banco de Desarrollo de América Latina (CAF )",
  "Banco de Leite Humano",
  "Banco de Sangue",
  "Banco Interamericano de Desenvolvimento (BID)",
  "Banco Nacional de Desenvolvimento Econômico e Social (BNDES)",
  "Banda Municipal",
  "Banheiros Públicos",
  "banho assistido",
  "Bar Opinião",
  "Bará do Mercado Público",
  "Barcos",
  "Baronesa do Gravataí",
  "BarraShoppingSul",
  "Basquete",
  "Benchmarking do Governo do Rio Grande do Norte",
  "Biblioteca da Escola de Educação Infantil Paulo Freire",
  "Biblioteca do Parcão",
  "Biblioteca Ecológica Infantil Maria Dinorah",
  "Biblioteca Jornalista Roberto Eduardo Xavier",
  "Bicicleta",
  "Bikepoa",
  "Blitz",
  "Bloco cirúrgico do Posto do IAPI",
  "Bloco da Sustentabilidade (DMLU)",
  "Bloqueio no trânsito",
  "Bloqueio químico",
  "Bocha",
  "Bolsa Atleta Municipal",
  "Bolsa Família",
  "Bombeiros",
  "Bônus-Moradia",
  "Brechó",
  "Brechocão",
  "Brigada Militar",
  "Brinquedo",
  "Brique da Redenção",
  "BRT's",
  "Bruno Vanuzzi",
  "bullying",

  "Cabines Telefônicas",
  "Cachorro",
  "cachorródromo",
  "cadastramento",
  "Cadastro Único",
  "cadeiras anfíbias",
  "CÃES",
  "Café Coworking do Parque Científico e Tecnológico da PUCRS (TecnoPuc)",
  "Cais Mauá",
  "Caixa Econômica Federal",
  "calçadão de Ipanema",
  "Calor",
  "Camaquã",
  "Câmara de Vereadores",
  "Câmara Municipal de Porto Alegre (CMPA)",
  "Câmara Rio-Grandense do Livro",
  "Câmeras de segurança",
  "Caminhada",
  "Caminho do Gol",
  "Caminho dos Jacarandás",
  "Caminhão",
  "caminhões-pipa",
  "Caminhos Rurais",
  "Campanha",
  'Campanha " Aluguel Solidário - A Vida de Casa Nova"',
  "Campanha de Prevenção as DSTs",
  "Campanha do Agasalho",
  "Campanha do Brinquedo Solidário",
  "Campanha Nacional de Vacinação contra Gripe (influenza)",
  "Campanha Troco Amigo",
  "Campeonato",
  "Campo de Futebol Luiz Carlos Oliveira (Bolinha)",
  "Campus da Unisinos Porto Alegre",
  "Campus do Vale - UFRGS",
  "Câncer",
  "Câncer Bucal",
  "Câncer de Mama",
  "Cantata de Natal",
  "Capacitação",
  "Capacitação - Controle Social e Educação: Projeto-Piloto de capacitação de conselheiros escolares",
  "Capacitação e Gerenciamento de Projetos Prioritários de Governo",
  "Capester",
  "Capina",
  "Capital Gaúcha",
  "Capitão de Mar e Guerra, Rafael Silva dos Santos",
  "Capitol Riverfront",
  "Carlos Siegle",
  "Carnaval",
  "Carnaval de Rua",
  "Carris",
  "Carro",
  "Carta de Serviços",
  "Cartão Material Escolar",
  "Casa da Estrela",
  "Casa de Apoio Viva Maria",
  "Casa de Bombas",
  "Casa de Cultura Mario Quintana",
  "Casa de Festas Brincalhão",
  "Casa do Gaúcho",
  "Casa dos Conselhos",
  "Casa Lar do Idoso",
  "Casa Menino Jesus de Praga",
  "Casa NTX",
  "Casamento",
  "Catamarã",
  "Catedral Metropolitana de Porto Alegre (Matriz)",
  "Causa Animal",
  "Cavalo",
  "CDL Porto Alegre",
  "Cecoflor",
  "CEEE Equatorial",
  "Ceic",
  "CEIC",
  "Cel QOEM Mário Yukio Ikeda",
  "Cel. Evaldo Rodrigues Oliveira",
  "Celebração do Dia da Criança",
  "Cemitério da Santa Casa de Misericórdia",
  "Central Única das Favelas (CUFA)",
  "Centro Administrativo Municipal (CAM)",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural da Universidade Federal do Rio Grande do Sul (UFRGS)",
  "Centro Cultural Multimeios Restinga",
  "Centro Cultural Usina do Gasômetro",
  "Centro da Comunidade Parque Madepinho (Cecopam)",
  "Centro de Artes e Esporte da Restinga (CEU)",
  "Centro de Atenção Psicossocial Álcool e Drogas (CAPS AD)",
  "Centro de Atenção Psicossocial Álcool e Drogas 3 – Pernambuco",
  "Centro de Atenção Psicossocial Álcool e Drogas 4 – Céu Aberto",
  "Centro de Atenção Psicossocial Álcool e Drogas do Tipo IV",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Eventos da Amrigs",
  "Centro de Eventos da PUC",
  "Centro de Eventos do Barrashoppingsul",
  "Centro de Eventos Laçador",
  "Centro de Informações Estratégicas em Vigilância em Saúde (Cievs)",
  "Centro de Integração Empresa Escola do Rio Grande do Sul (CIEE-RS)",
  "Centro de Integração Empresa-Escola – CIEE",
  "Centro de Monitoramento e Contingência Climática",
  "Centro de Referência em Saúde do Trabalhador (Cerest)",
  "Centro de Saúde Modelo",
  "Centro de Saúde Murialdo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro de triagem",
  "Centro de Valorização da Vida",
  "Centro Dia do Idoso (CDI) Nascer do Sol",
  "Centro Dia do Idoso Zona Norte - Nascer do Sol",
  "Centro Esportivo da Vila Ingá (Cevi)",
  "Centro Histórico",
  "Centro Humanístico Vida",
  "Centro Integrado de Comando",
  "Centro Integrado de Comando da Cidade de Porto Alegre (CEIC)",
  "Centro Integrado de Coordenação e Serviços da Cidade de Porto Alegre (CEIC)",
  "Centro Logístico de Medicamentos Especiais",
  "Centro Municipal de Cultura",
  "Centro Municipal de Cultura Lupicínio Rodrigues",
  "Centro Popular de Compras (CPC)",
  "Centro Social Marista - CESMAR",
  "Cerimônia de Apresentação de PLs de Concessão e Adoção",
  "Cerimônia de inaguração do Centro de Referência de Assistência Social (CRAS - ILHAS)",
  "Cerimônia de Passagem de Comando na Capitania Fluvial de Porto Alegre",
  "Cerimônia de posse da Comissão de Saúde e Segurança do Trabalho da PGM",
  "Cercamento Eletrônico",
  "Cerimônia",
  "Cerimônia de posse gestão 2025/2028",
  "Certificado",
  "CETE - Centro Estadual de Treinamento Esportivo",
  "Cezar Miola",
  "CGVS",
  "Chalé da Praça XV de Novembro",
  "Chefe de Gabinete",
  "Chikungunya",
  "Chimarrão",
  "churrasqueiras",
  "Chuva",
  "Ciclo de Debates Barbara Starfield",
  "Ciclo de Palestras da Transparência",
  "Cidadania",
  "Cidades Educadoras",
  "Cinemateca Capitólio",
  "Circuito Urbano",
  "Circuito Urbano EPTC",
  "Circulação",
  "Circulação e Transporte",
  "Clássicos na Pinacoteca",
  "Claudio Bier",
  "clima",
  "Clínica da Família",
  "Clube de Criação RS",
  "CMDUA",
  "Colégio Militar de Porto Alegre",
  "Colégio São Judas Tadeu",
  "Coleta",
  "Coleta Domiciliar (orgânicos e rejeito)",
  "Coleta Seletiva",
  "Coletiva de Imprensa",
  "Colheita",
  "Colônia de Férias Geraldo Santana",
  "Colônia de Pescadores Z5",
  "Comandante da Guarda Municipal, Marcelo Nascimento",
  "Comandante Nádia",
  "Comando do Policiamento da Capital (CPC)",
  "Comando Militar do Sul",
  "Combate a Dengue",
  "Comcet",
  "Comércio",
  "Comércio Irregular",
  "Comissão da Pessoa com Deficiência",
  "Comissão de Economia, Finanças, Orçamento e do Mercosul (Cefor)",
  "Comissão de Saúde e Meio Ambiente da CMPA (Cosmam)",
  "Comissão de Saúde e Segurança no Trabalho",
  "Comissão Permanente de Atuação em Emergências (Copae)",
  "Comitê do Projeto Vida no Trânsito",
  "Comitê Municipal de Transmissão Vertical do HIV e Sífilis Congênita",
  "Comitê Paralímpico Brasileiro (CPB)",
  "Comitiva de Suzhou",
  "Comitiva portuguesa",
  "Companhia Carris Porto Alegrense",
  "Companhia de Processamento de Dados do Município (Procempa)",
  "Companhia de Saneamento Básico do Estado de São Paulo (Sabesp)",
  "Companhia Municipal de Dança",
  "Complexo Cultural Porto Seco",
  "Complexo Hospitalar Santa Casa",
  "comportas do Muro da Mauá",
  "Compostagem",
  "Compra Assistida",
  "Computador",
  "COMTU",
  "Comui",
  "Comunicação",
  "Comunicação Social",
  "Conaf",
  "Concerto Musical",
  "Concessionária GAM3 Parks",
  "Concurso",
  "Confeitaria Rocco",
  "Conferência",
  "Conferência das Nações Unidas sobre as Mudanças Climáticas (COP29)",
  "Conferência Municipal do Meio Ambiente",
  "Conscientização",
  "Conselheiros Tutelares",
  "Conselho da Procempa",
  "Conselho do OP",
  "Conselho Municipal de Assistência Social (CMAS)",
  "Conselho Municipal de Saúde",
  "Conselho Municipal dos Direitos das Pessoas com Deficiência ( Comdepa)",
  "Conselho Superior da PGM",
  "Conselhos Municipais",
  "Conserto Didático da Banda Municipal de Porto Alegre",
  "Cônsul da Ucrânia no Brasil",
  "Cônsul do Japão em Porto Alegre",
  "Cônsul-Geral do Japão em Curitiba, Sr. Yasuhiro Mitsu.",
  "Cônsul-Geral dos Estados Unidos em Porto Alegre",
  "Cônsul-Geral dos Estados Unidos, Sr. Jason Green.",
  "Consulado",
  "Consultório na Rua",
  "Consumidor",
  "Contratação emergencial de professores",
  "Contrato com a Caixa Econômica Federal (CEF)",
  "Contrato de concessão da Rodovia Integração Sul (RIS)",
  "Contrato para Obras de Reassentamento da Vila Tronco",
  "Controladoria",
  "Convênio",
  "Convite",
  "Coordenação de Nutrição",
  "Coordenação de Operações Especiais (COE)",
  "Coordenação Municipal de Urgências (CMU)",
  "Coordenação-Geral dos Direitos Animais (CGDA)",
  "Coordenações",
  "Cootravipa",
  "Coro do DMAE",
  "Coronavírus",
  "corpo de bombeiros",
  "corredor de ônibus",
  "Corredor Humanitário",
  "Corregedoria",
  "Corrida",
  "Côrte da Festa da Uva e da Ameixa de Porto Alegre",
  "Corte do Carnaval de Porto Alegre 2025",
  "Covid-19",
  "cozinheiras",
  "Criança",
  "CRIP Extremo-Sul",
  "CRIPs",
  "Cruz Vermelha do Brasil",
  "Cultur",
  "Cultura",
  "Cultura e Economia Criativa",
  "Cultura Economia Criativa",
  "Curso",
  "Curso de Aperfeiçoamento em Legislação de Trânsito e Transporte na EPTC",
  "Curso de Formação",
  "Curso de Formação de Diretores da SMED",
  "Curso de Mecânica",

  "Dança",
  "Daniel Rigon",
  "Debate",
  "Declaração de Edimburgo",
  "Decoração de Natal Sustentável",
  "Decreto que Regulamenta a Lei Anticorrupção",
  "Defesa Civil",
  "Defesa Civil de Porto Alegre-RS",
  "Demhab",
  "Dengue",
  "Departamento de Arrecação e Cobrança (DAC)",
  "Departamento de Iluminação Pública (DIP)",
  "Departamento Estadual de Trânsito (Detran)",
  "Departamento Municipal de Água e Esgotos (DMAE)",
  "Departamento Municipal de Habitação ( Demhab)",
  "Departamento Municipal de Habitação (Demhab)",
  "Departamento Municipal de Limpeza Urbana (DMLU)",
  "Departamento Nacional de Infraestrutura de Transportes (Dnit)",
  "Deputado Estadual Fixinha",
  "Desabrigados",
  "Desafio do City Cancer Challenge",
  "Desafio Microrrevoluções Urbanas",
  "Desastres",
  "Descida da Borges",
  "Desenvolviment Econômico",
  "Desenvolvimento",
  "Desenvolvimento Economico",
  "Desenvolvimento Econômico",
  "Desenvolvimento Economico e Esporte",
  "Desenvolvimento Econômico e Turismo",
  "Desenvolvimento Social",
  "Desenvolvimento Social e Esporte",
  "Desfile Farroupilha 2018",
  "Deslizamento",
  "desvio de trânsito",
  "Dia D",
  "Dia D de Vacinação",
  "Dia da Criança",
  "Dia da Visibilidade Trans",
  "Dia das Crianças",
  "Dia de Finados",
  "Dia de Passe Livre",
  "Dia do Desafio",
  "Dia do Gari",
  "Dia do Livro",
  "Dia internacional da Mulher",
  "Dia Internacional da Pessoa com Deficiência",
  "Dia Mundial da Alimentação",
  "DIA SEM CARRO",
  "Diplomação",
  "Dique",
  "Direito do Consumidor",
  "Direitos Animais",
  "Direitos do Consumidor",
  "Direitos dos Animais",
  "Direitos Humanos",
  "Direitos Humanos na Educação Infantil e Ensino Fundamental",
  "Diretor-geral do DMAE",
  "Diretor-presidente da Empresa Pública de Transporte e Circulação(EPTC), Pedro Bisch Neto",
  "diretor-presidente da EPTC",
  "diretor-presidente do DMAE, Maurício Loss",
  "Diretor Regional do SESC",
  "diretora-presidente",
  "Diretoria de Esporte, Recreação e Lazer (Diresp)",
  "Diretoria de Governança e Gestão da Prefeitura de Esteio",
  "Diretoria de Vigilância em Saúde (DVS)",
  "Diversidade sexual",
  "Divisão de Conservação de Vias Urbanas (DCVU)",
  "Dmae",
  "DMAE",
  "DMAP",
  "Dmlu",
  "DMLU",
  "Doação",
  "Doação de Automóvel para a FASC",
  "Doação de Equipamentos",
  "Doação de Guarda-Sóis",
  "doação de sangue",
  "doação e transplante de órgãos",
  "Doações",
  "doações de cestas básicas",
  "Doações de Materiais",
  "Doença Respiratória",
  "Doenças Transmissíveis",
  "Donativos",
  "Downburst",
  "Dragagem",
  "Dragagem do Segundo Trecho do Arroio Dilúvio",
  "Drenagem",
  "Drone",

  "E.E.E.F. Uruguai",
  "Ecobarreira",
  "Economia",
  "Economia Solidária",
  "Edifício Intendente José Montaury",
  "Editais para Realização do Carnaval de Rua/POA 2019",
  "Eduardo Cunha da Costa",
  "Educa+Saúde",
  "Educação",
  "Educação Ambiental",
  "Educação Básica",
  "Educação Especial",
  "Educação Fundamental",
  "Educação Infantil",
  "Educação no Trânsito",
  "Educação Permanente",
  "Educação Superior",
  "Eixo Baltazar",
  "eleições",
  "Eleições 2018",
  "Em Cena",
  "Embaixada",
  "Embaixador de Luxemburgo no Brasil",
  "Embratel",
  "Emeb Liberato Salzano Vieira da Cunha",
  "Emeef Elyseu Paglioli",
  "EMEF",
  "Emef Anísio Teixeira",
  "Emef Dep. Marcírio Goulart Loureiro",
  "EMEF Deputado Marcírio Goulart Loureiro",
  "EMEF Gabriel Obino",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "Emef Ildo Meneguetti",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "Emef Leocádia Felizardo Prestes",
  "EMEF Leopolda Barnewitz",
  "EMEF Mario Quintana",
  "Emef Migrantes",
  "EMEF Migrantes",
  "Emef Nossa Senhora do Carmo",
  "Emef Pepita de Leão",
  "EMEF Porto Novo",
  "Emef Presidente Vargas",
  "EMEF Professora Ana Íris do Amaral",
  "Emef Saint Hilaire",
  "Emef Vereador Antonio Giúdice",
  "EMEF Vereador Antônio Giúdice",
  "Emef Vereador Carlos Pessoa de Brum",
  "EMEF Vila Monte Cristo",
  "Emef Vila Montecristo",
  "EMEI",
  "EMEI Dom Luiz de Nadal",
  "EMEI Humaitá",
  "Emei Ilha da Pintada",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Nova Restinga",
  "Emei Protásio Alves",
  "Emei Santo Expedito",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "EMEI Vila Tronco",
  "EMEM",
  "Empreendedorismo",
  "Empreendimento para o 4º distrito",
  "Emprego",
  "Empresa Pública de Transporte e Circulação (EPTC)",
  "Encerramento",
  "Encerramento da Missão Técnica do BNDES",
  "Encerramento do Programa Compartilhar",
  "Enchente",
  "Enchente Porto Alegre",
  "Enchente Porto Alegre Maio de 2024",
  "Encontro com as Associação das Empresas dos Bairros Humaitá e Navegantes",
  "Ensino",
  "entidades carnavalescas",
  "Entrada da cidade",
  "Entrega da Lei Orçamentária Anual (LOA) 2019",
  "Entrega de Doações",
  "Entrega de kits de brinquedos doados pela Fundação Abrinq",
  "Entrega de matrículas",
  "Entrega de Matrículas de Imóveis da Vila Canadá",
  "Entrega de Matrículas de Regularização para Moradores da Zona Sul",
  "Entrega de Obras",
  "Entrega dos Certificados aos Gestores dos CRIP's",
  "entrevista",
  "Entrevista ao Programa Timeline",
  "Entrevista Coletiva",
  "Epidemiologia",
  "Eptc",
  "EPTC",
  "Eptc -",
  "Equipamentos Hospitalares",
  "Equipe de Manejo Arbóreo (EMA)",
  "Equipe de Veículos de Tração Animal (VTA)",
  "Equipe de Vigilância de Alimentos da SMS",
  "Equipe de Vigilância de Antropozoonoses (Evantropo)",
  "Equipe de Vigilância em Saúde Ambiental e Águas (EVSAA)",
  "Equipe de Vigilância Eventos Vitais (EVEV)",
  "Equipe eMulti SUS",
  "Erno Harzheim",
  "Escada rolante",
  "Escadaria da Rua João Manoel",
  "Escola",
  "Escola Comunitária de Educação Infantil (Ecei) Madre Teresa",
  "Escola Comunitária de Educação Infantil (Ecei) Tia Mariazinha",
  "Escola de Ensino Médio Raul Pilla",
  "Escola de Gestão Pública (EGP)",
  "Escola de Samba Império da Zona Norte",
  "Escola Especial para Surdos Frei Pacífico",
  "Escola Estadual de Ensino Fundamental Duque de Caxias",
  "Escola Estadual Piauí",
  "Escola Mariano Beck",
  "Escola Municipal de Educação infantil Humaitá",
  "Escola Municipal de Educação Infantil Jardim de Praça Pica-Pau Amarelo",
  "Escola Municipal de Ensino Fundamental (Emef) Grande Oriente",
  "Escola Municipal de Ensino Fundamental Deputado Victor Issler",
  "Escola Municipal de Ensino Fundamental José Loureiro da Silva",
  "Escola Municipal de Ensino Fundamental Nossa Senhora de Fátima",
  "Escola Municipal Especial de Ensino Fundamental Eliseu Paglioli",
  "Escola Politécnica da PUCRS",
  "Escola Superior de Direito Municipal - ESDM",
  "Escola Técnica Mesquita",
  "Escolas Municipais de Educação Infantil",
  "Escolas Preparatórias de Dança (EPDs)",
  "Escolta",
  "Escorpião Amarelo",
  "Escritório da Rede 100 Cidades Resilientes - 100RC",
  "Escritório das Nações Unidas (UNOPS)",
  "Escritório de Parcerias Público-Privadas do Distrito de Columbia (OP3)",
  "Escritório de Reconstrução",
  "Escritório de Transição",
  "Escultura",
  "Esgoto",
  "Esgoto Pluvial",
  "Espaço Hortomercado Parobé",
  "Espaço Infantil",
  "Espaço Memórias",
  "Espaços Públicos",
  "Espetáculo",
  "Espetáculo O Rei da Vela",
  "Espetáculo Revolução Farroupilha: um História de Sangue e Metal",
  "Esporte",
  "Esporte, Lazer e Juventude",
  "Esporte e Lazer",
  "Esporte Lazer e Juventude",
  "Esportes e Lazer",
  "Esquina Democrática",
  "Estação Cristiano Fischer",
  "Estação de Bombeamento de Águas Pluviais (Ebap)",
  "Estação de Transbordo",
  "Estação Rodoviária de Porto Alegre",
  "Estácio",
  "Estação Integrada de Compostagem",
  "Estação Radio Base (ERBs)",
  "Estacionamento da EPTC",
  "Estações de Bombeamento de Águas Pluviais (Ebaps)",
  "Estádio Beira-rio",
  "Estátua do Laçador",
  "Estiagem",
  "Estrada das Furnas",
  "Estrada João de Oliveira Remião",
  "Estreia",
  "Estudantes",
  "Estúdio de Rádio",
  "Estúdios da Rádio Guaíba",
  "ETA",
  "ETA Moinhos de Vento",
  "ETA São João",
  "evento social",
  "evento turístico internacional",
  "Eventos Climáticos",
  "Exame médico",
  "Executivo",
  "Exército Brasileiro",
  "Expo Favela",
  "Expo Favela RS 2024",
  "Expointer",
  "exposição",
  "Exposição de Gravuras Portuguesas",
  "Exposição Fotográfica",
  "Exposição Maresia",
  "Extremo Sul",

  "Fachada",
  "Faixa Preferencial Deslocamento de Ônibus",
  "Fake News",
  "Famurs",
  "Farmácia",
  "Farmácia Distrital Modelo",
  "Farmácia Distrital Murialdo",
  "Farmácia Móvel",
  "Farsul",
  "Fasc",
  "Fauna",
  "Fazenda",
  "febre amarela",
  "Fecomércio",
  "Federação das Associações de Municípios do Rio Grande do Sul (FAMURS)",
  "Federação das Indústrias do Estado do Rio Grande do Sul (Fiergs)",
  "Federação de Entidades Empresariais do Rio Grande do Sul ( Federasul )",
  "Feira de Oportunidades",
  "Feira do Livro",
  "Feira Ecológica",
  "Feira Fora da Feira",
  "Feira Temática",
  "Felicity/GIZ",
  "Felipe Hirsch",
  "Fernanda Barth",
  "Festa da Uva e da Ameixa",
  "Festa da Virada",
  "Festa de Oxum",
  "Festa de Natal",
  "Festa de Natal dos Acolhidos de Porto Alegre",
  "Festa dos Idosos da Fasc",
  "Festa Jovem do Programa de Trabalho Educativo (PTE)",
  "Festejos",
  "Festa de Nossa Senhora dos Navegantes",
  "Festival",
  "Festival de Inverno",
  "Festival do Japão",
  "Festuris 2018",
  "Fiergs",
  "Fim de tarde",
  "Finanças",
  "Finanças Públicas",
  "Financiamento",
  "Fios Soltos",
  "Fique Sabendo Jovem",
  "Fiscalização",
  "Fiscalização do Transporte Resíduos da Construção Civil",
  "Flagrante",
  "Flora",
  "Florianópolis-SC",
  "FNP",
  "foco de lixo",
  "fogos de artifício",
  "Fonte Talavera",
  "Food truck",
  "Força Nacional do SUS",
  "Força-Tarefa",
  "Forças Armadas",
  "Formação",
  'Formação "O trabalho em Direitos Humanos na Educação Infantil"',
  "Formação de Multiplicadores",
  "Formatura",
  "Formulário",
  "Fórum",
  "Fórum de Justiça e Segurança do Centro",
  "Fórum dos Conselhos",
  "Fórum Desenvolvimento Sustentável no Sul",
  "Fórum Social Mundial –População Idosa, Pessoas com Deficiência e Diversidades",
  "Fórum Social Mundial da População Idosa",
  "foto aérea",
  "foto noturna",
  "Fotografia",
  "Fotos Antigas",
  "Fraport Brasil S.A.",
  "Frente Nacional dos Prefeitos (FNP)",
  "Frente Parlamentar de Segurança",
  "Frio",
  "Funcriança",
  "Fundação de Assistência Social e Cidadania – Fasc",
  "Fundação de Atendimento Socioeducativo do Rio Grande do Sul (Fase)",
  "Fundação Iberê Camargo",
  "Fundação O Pão dos Pobres",
  "Futebol",
  "Futebol de Várzea",
  "Futebol Feminino",
  "Futsal",

  "Gabinete",
  "Gabinete da Causa Animal",
  "Gabinete da Causa Animal (GCA)",
  "Gabinete da Inovação",
  "Gabinete da Primeira-Dama",
  "Gabinete da Procuradoria",
  "Gabinete da SMDSE",
  "Gabinete da SMF",
  "Gabinete de Comunicação",
  "Gabinete de Gestão Integrada Municipal (GGIM)",
  "Gabinete de Inovação",
  "Gabinete de Inovação (GI)",
  "Gabinete do Prefeito",
  "Gabinete do Vice-Prefeito",
  "Gabinete Prefeito",
  "Gabriel Souza",
  "Galera Curtição",
  "Galeria de Arte do Dmae",
  "Galeria dos Secretários",
  "Galpão da Hospitalidade",
  "gari",
  "Gasolina",
  "Gato",
  "General Edson Leal Pujol",
  "general Hertz Pires do Nascimento",
  "GeraçãoPoa",
  "GeraEncontro",
  "Gestante",
  "Gestão 2025 - 2028",
  "Gestão e Planejamento",
  "Gestores dos CRIPs",
  "Ginásio do Colégio Protásio Alves",
  "Ginásio Lupi Martins",
  "Ginásio Tesourinha",
  "Ginástica",
  "Governador",
  "Governador Eduardo Leite",
  "governador em exercício",
  "Governador José Ivo Sartori",
  "Governacia Local e Coordenação Politica",
  "Governança",
  "Governança Local e Coordenação Política",
  "Governança Local e Coordenação Política.",
  "Governo Federal",
  "Gp",
  "Gráfico Década de Ação pela Segurança no Trânsito da ONU",
  "Grêmio Foot-Ball Porto Alegrense",
  "Grêmio Sargento Expedicionário Geraldo Santana",
  "Gre-Nal",
  "Gre-nal de Todos",
  //"Greve",
  "Gripe",
  "Grupo de Combate ao Tabagismo",
  "Grupo de Trabalho da Orla Moacyr Scliar",
  "Grupo Executivo Municipal das Ações de Contingência de Combate ao AEDES",
  "Grupo Experimental de Dança (GED)",
  "Grupo Hospitalar Conceição (GHC)",
  "Grupo POA Solidárias",
  "Grêmio Recreativo Escola de Samba Filhos de Maria",
  "Guaíba",
  "Guarda Municipal",
  "Guias de Pagamento de Tributos",
  "Gustavo Paim",
  "Gvp",

  "Habitação",
  "Habitação Regularização Fundiária",
  "Habitação e Regularização Fundiária",
  "Hamilton Sossmeier",
  "Handebol",
  "Hanseníase",
  "Haia",
  "Heineken F1 Experience",
  "Helen Machado",
  "Hepatite",
  "hipertensão arterial",
  "hipertenso",
  "Hipismo",
  "HMIPV",
  "Homenagem",
  "Homologação",
  "Horário estendido",
  "horta",
  "Hortas Comunitárias",
  "Hortomercado Parobé",
  "Hospital da Restinga Extremo Sul (HRES)",
  "Hospital de campanha",
  "Hospital de Clínicas de Porto Alegre (HCPA)",
  "Hospital de Pronto Socorro (HPS)",
  "Hospital Fêmina",
  "Hospital Materno-Infantil Presidente Vargas (HMIPV)",
  "Hospital Moinhos de Vento",
  "Hospital Porto Alegre",
  "Hospital Santa Ana",
  "Hospital São Lucas PUCRS",
  "Hotel Deville",
  "Hotel Laghetto Stilo Higienópolis",
  "Hotel Serra Park Gramado",

  "I Love Poa",
  "IberCup World 2019",
  "Ideb",
  "Idosos",
  "Igreja Nossa Senhora das Dores",
  "Ilha da Pintada",
  "Ilha dos Marinheiros",
  "Iluminação Cênica",
  "Iluminação Pública",
  "Imagem Aérea",
  "Imigrantes",
  "Imposto",
  "Inacio Etges",
  "Inauguração",
  "Inauguração do Hospital Santa Ana",
  "Inauguração Restaurante 360 POA GASTROBAR",
  "Incêndio",
  "Incluir + POA",
  "Inclusão Em Cena",
  "Inclusão Social",
  "Indumentária Gaúcha",
  "Indústria",
  "Infecções Sexualmente Transmissíveis (IST)",
  "Infográfico",
  "Informatização",
  "Infraestrutura e Mobilidade",
  "Infraestrutura e Mobilidade Urbana",
  "Infraestrutura e Urbanismo",
  "Início da operação da primeira faixa reversível semaforizada da Capital",
  "Início das Atividades do Regula+Brasil na Capital Gaúcha",
  "Início da Primavera 2018",
  "Inovação",
  "Inspeção veicular",
  "Instituições de Longa Permanência para Idosos (ILPI)",
  "Instituto Caldeira",
  "Instituto Cultural Floresta (ICF)",
  "Instituto São Francisco",
  "Instituto Ling",
  "Instituto Penal Feminino de Porto Alegre",
  "Integração Metropolitana de Transporte",
  "Interdição",
  "Internet",
  "Iptu",
  "IPTU",
  "Isatir Antonio Bottin Filho",
  "IST Aids",
  "IST Aids e Hepatites Virais",
  "IV Mostra de Atividades do Projovem Adolescente",

  "Janeiro Branco",
  "Jardins do DMAE",
  "Jockey Club",
  "Jogos Abertos",
  "Jogos dos Estudantes Surdos",
  "Jogos Escolares da Cidade de Porto Alegre (Jespoa)",
  "Jorge Gerdau Johannpeter",
  "Jornada Científica do HPS",
  "Jornal Correio do Povo",
  "jornalista",
  "Josep Piqué",
  "Juliana Castro",
  "Junta de Serviço Militar",
  "Justiça",
  "Juventude",

  "Kelly Matos",
  "Kombina",

  "Laboratório de Informática do Prédio da Prefeitura de Porto Alegre",
  "Laboratório do HMIPV",
  "Laboratórios Municipais",
  "Laçador",
  "Lago Guaíba",
  "Lançamento",
  "Lançamento do Lance de Craque 2018",
  "Lançamento do Pacto Pela Inovação - Pacto Alegre",
  "Lançamento do Projeto de Lei para PPP de Iluminação Pública",
  "Lançamento Oficial da 64ª edição da Feira do Livro de Porto Alegre",
  "Lançamento oficial da Expodireto Cotrijal 2025",
  "Largo David Coimbra",
  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "lavagem de vias e pontos",
  "Lazer",
  "Lei",
  "Lei de Diretrizes Orçamentárias (LDO)",
  "Lei Orçamentária Anual (LOA)",
  "Lei Seca",
  "Leilão de Inservíveis",
  "Leishmaniose",
  "Leito Hospitalar",
  "Leonardo Busatto",
  "Leonardo Pascoal",
  "LGBT",
  "LGBTQIA+",
  "Licenciamento Ambiental",
  "Licenciamento Urbano",
  "Licitação para Manutenção Elevadores e Escadas Rolantes",
  "LIDE RIO GRANDE DO SUL",
  "Limpeza",
  "Limpeza Urbana",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Literatura",
  "Live",
  "Livro e Literatura",
  "Livros",
  "Lixo",
  "Lomba do Pinheiro",
  "Loteamento",
  "Loteamento Santa Terezinha",
  "Luciano Alabarse",

  "macacos-prego",
  "Mãe",
  "Maio Amarelo",
  "Maio Vermelho",
  "Manifestação",
  "Manutenção",
  "Mapa",
  "mapa de serviço de trânsito",
  "Maratona",
  "Maratona de Dança",
  "Marcele Malta",
  "Marcelo Soletti",
  "Marcino Fernandes",
  "Marcos Frota",
  "Maria Carpi",
  "Maria de Fátima Záchia Paludo",
  "Marinha do Brasil",
  "Mascote",
  "Mastectomia em animais",
  "Material Escolar",
  "Maurício Fernandes",
  "Mauro Pinheiro",
  "MEC",
  "Medicamentos",
  "Medicina",
  "Medicina Veterinária",
  "Meio Ambiente",
  "Meio Ambiente e Sustentabilidade",
  "Meio Ambiente Sustentabilidade",
  "Meio Ambiente Urbanismo e Sustentabilidade",
  "Meio Ambiente, Urbanismo e Sustentabilidade",
  "Memória",
  "Memorial do Rio Grande do Sul",
  "Menino Deus",
  "Mercado do Bom Fim",
  "Mercado Público",
  "Mercado Público Central",
  "Mês do Idoso",
  "Metas",
  "Mexatchê",
  "micro-ônibus",
  "Ministério da Saúde",
  "Ministerio Público - RS",
  "Ministro da Saúde Gilberto Occhi",
  "Ministro de Estado da Infraestrutura Tarcísio Freitas",
  "Minha Casa Minha Vida",
  "Missão Estados Unidos",
  "Missão Internacional",
  "Missão Técnica com representantes do BNDES",
  "Missão Xangai 2018",
  "Mobiliário Urbano",
  "Mobilidade",
  "Mobilidade Urbana",
  "Moinhos de Vento",
  "Mônica Leal",
  "Monitoramento",
  "monumento em homenagem aos voluntários da enchente",
  "Montagem de estruturas",
  "Montagem das Estruturas da 64ª Feira do Livro de Porto Alegre",
  "Monumento à Elis Regina",
  "Monumento a Júlio de Castilhos",
  "Monumento ao Expedicionário",
  "moradias temporárias",
  "Moradores do Alameda Partenon",
  "Morcego",
  "Morro da Apamecor",
  "Morro da Cruz",
  "Morro Ricaldone",
  "Morro Santa Tereza",
  "Morro Santana",
  "Mortes no trânsito",
  "Mosquito Aedes Aegypti",
  "Mostra Acústicos e Elétricos",
  "Mostra Porto-alegrense da Atenção Primária à Saúde",
  "Motocicleta",
  "Mulher",
  "multivacinação",
  "Muro da Mauá",
  "Museu de Arte do Paço (MAPA)",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Museu do Hip Hop",
  "Museu Iberê Camargo",
  "Museu Joaquim Felizardo",
  "Música",
  "Mutirão",
  "Mutirão de cirurgias",
  "Mutirão de Limpeza",

  "Nação Kids",
  "Natal",
  "Natal dos Encantos",
  "Navegantes",
  "Negociação de Precatórios",
  "Nelson Marchezan Júnior",
  "Nivel do Guaíba",
  "Noite dos Museus",
  "Nós na Praça",
  "Nova Ponte do Guaíba",
  "Novas Viaturas para a Guarda Municipal",
  "Novembro Azul",
  "Novo Espaço de Recreação Infantil da Praça Carlos Simão Arnt",
  "Novo Layout Caminhões Coleta Seletiva",
  "Novo Líder de Governo na Câmara de Vereadores de Porto Alegre",
  "Novo Marco Global",
  "Núcleo de Ações Preventivas (NAP)",
  "Núcleo de Imunizações DVS (NI)",
  "Núcleo Municipal de Segurança do Paciente",
  "Nutrição",
  "Nuvens",

  "OAB-RS",
  "Obra de arte",
  "Obra na Alça de Acesso da Cristóvão Colombo",
  "Obras",
  "Obras da Copa de 2014",
  "Obras de implantação da adutora da Estrada Antonio Borges",
  "Obras e Infraestrutura",
  "Obras Restinga 2018",
  "Observatório de Porto Alegre",
  "óculos",
  "OdontoSesc",
  "Oficina",
  "Oficina ‘Rabiscando Ideias: Da cabeça para o papel’",
  "Oficina de Dança",
  "oficinas artísticas",
  "Oficinas Regionais sobre o Plano de Mobilidade Urbana (PMU)",
  "oftalmologista",
  "Olimpíada Brasileira de Matemática - OBMEP",
  "Ônibus",
  'Ônibus da Carris adesivado para  campanha "Aluguel Solidário"',
  "Ônibus de Natal da Carris 2018",
  "ônibus elétrico",
  "OP",
  "Ópera-rock Revolução Farroupilha",
  "Operação Bota-Fora",
  "Operação de Segurança",
  "Operação Ferro-Velho",
  "Operação Inverno",
  "Operação Jaguar",
  "Operação Natal da Retomada",
  "Operação Sossego",
  "Operação Viagem Segura",
  "operários",
  "Orçamento Participativo",
  "Orçamento Participativo 2018",
  "Orla",
  "Orla de Ipanema",
  "Orla do Guaíba",
  "Orla Moacyr Scliar",
  "Orla Skate Park",
  "Orly Portal",
  "Orquestra Sinfônica de Porto Alegre (OSPA)",
  "Orquestra Vila Lobos",
  "Outubro Rosa",

  "Paço dos Açorianos",
  "Paço Municipal de Porto Alegre",
  "Pacto Alegre",
  "Pacto Pela Inovação",
  "Painel",
  "Palácio do Comércio",
  "Palácio Piratini",
  "Palestra",
  "Papai e Mamãe Noel da Carris",
  "parada de ônibus",
  "Parcão",
  "Parceria Público-Privada",
  "Parcerias",
  "Parcerias Estratégicas",
  "Parklet",
  "Paróquia de São Jorge",
  "Parque Ararigbóia",
  "Parque Chico Mendes",
  "Parque Farroupilha (Redenção)",
  "Parque Germânia",
  "Parque Harmonia",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Parque Maurício Sirotsky Sobrinho (Harmonia)",
  "Parque Moinhos de Vento (Parcão)",
  "Parque Natural Municipal Morro do Osso",
  "Parque Urbano da Orla Moacyr Scliar",
  "parquímetro",
  "Partenon",
  "Páscoa",
  "Passeio",
  "Passeio cliclistico De Bike para o Trabalho",
  "Patrimônio",
  "Patrimônio Histórico e Cultural do município",
  "Patrulha da Mulher (PATAM)",
  "Patrulhamento",
  "Pavimentação",
  "Pedestre",
  "Pedestre Idoso",
  "Permissionários do Serviço de Táxis",
  "Pessoa com Deficiência",
  "Pessoa com mobilidade reduzida",
  "pessoas",
  "Petrópolis",
  "Pgm",
  "PGM",
  "Pier do Barra Shopping Sul",
  "Pinacoteca Aldo Locatelli",
  "Pinacoteca Ruben Berta",
  "Pintura",
  "Pisa",
  "Piscinas Públicas",
  "Placa de veículos",
  "Planejamento",
  "Planejamento e Assuntos Estratégicos",
  "Planejamento e Gestão",
  "Plano de Mobilidade de Porto Alegre (MobiliPOA)",
  "Plano de Superação da Situação de Rua",
  "Plano Municipal de Superação da Situação de Rua",
  "Plataforma Reconstruir Porto Alegre",
  "Plantio",
  "Plantio de Árvores",
  "Plantio Sustentável do DMLU",
  "Plantio Urbano Sustentável",
  "Plano de ação Porto Alegre Forte",
  "Plano Diretor",
  "Plataforma Google for Education",
  "Plaza São Rafael",
  "Plenário 20 de Setembro",
  "Plenário Ana Terra - CMPA",
  "Plenário Otávio Rocha",
  "Poa Em Cena",
  "POA Em Cena",
  "PoaHub",
  "Poda",
  "Podas de Árvores",
  "Pokémon GO",
  "Pókemon GO Safari Zone",
  "Polícia Rodoviária Federal",
  "Polícia Rodoviária Federal (PRF)",
  "Polícia Rodoviária Federal - PRF",
  "Pontal do Estaleiro",
  "Ponte do Guaíba",
  "Pontifícia Universidade Católica do RS (PUCRS)",
  "População de Rua",
  "População em Situação de Rua",
  "População Negra",
  "pôr-do-sol",
  "Porão do Paço",
  "Portal da Transparência",
  "porteiros",
  "Porto Alegre",
  "Porto Alegre-RS",
  "Porto Verão Alegre 2019",
  "Posse",
  "Posse da  Comissão de Saúde e Segurança da Fasc",
  "Posse da Comissão de Saúde e Segurança do Trabalho da SMRI",
  "Posse da Delegada Andine Anflor como chefe da Polícia Civil do RS",
  "Posse da Procuradora Municipal",
  "Posse Deputados Estaduais",
  "Posse do Governador Eduardo Leite",
  "Posse Novos Procuradores-Gerais do Município",
  "Posse Novos Secretários Municipais",
  "Posto de Gasolina",
  "Povo Negro",
  "PPA",
  "PPCIs",
  "Praça da Alfândega",
  "Praça da Matriz",
  "Praça Darcy Azambuja",
  "Praça Doutor Lopes Trovão",
  "Praça Garibaldi",
  "Praça Mafalda Veríssimo",
  "Praça Marechal Deodoro (Matriz)",
  "Praça Montevideo",
  "Praça Parobé",
  "Praça Província de Shiga",
  "Praça XV de Novembro",
  "Praças e Parques",
  "Praia de Belas",
  "Praia do Lami",
  "Prédio Intendente José Montaury",
  "Prédio público",
  "Prédios e Edificações",
  "Prédios Históricos",
  "prefeita em exercício, Betina Worm",
  "Prefeito",
  "prefeito de Florianópolis, Topázio Neto",
  "Prefeito de Porto Alegre, Sebastião Melo",
  "prefeito em exercício",
  "prefeito Nelson Marchezan Júnior",
  "Prefeitos de Praça",
  "Prefeitura de Porto Alegre",
  "Prefeitura e DMAE anunciam obras no 4º Distrito",
  "Prefeitura Municipal de Porto Alegre",
  "Prefeitura nos Bairros",
  "Prefeitura Nos Bairros",
  "Premiação",
  "Prêmio Açorianos",
  "Prêmio Inovação",
  "Prêmio MPT na Escola",
  "Presidente",
  "presidente CEEE Equatorial, Riberto Barbarena",
  "Presidente da Câmara de Vereadores",
  "Presidente da Câmara Municipal de Vereadores,  Idenir Cecchim",
  "Presidente da Companhia de Processamentos de Dados do Município de Porto Alegre, Leticia Batistela",
  "presidente da Fundação de Assistência Social e Cidadania (FASC), Cristiano Roratto",
  "Presidente da República Luiz Inácio Lula da Silva",
  "Presidente das Mantenedoras Maristas do Sul",
  "presidente do Grêmio Foot-Ball Porto Alegrense",
  "Presidente do Tribunal de Contas do Estado (TCE)",
  "Presidente eleita da Associação do Ministério Público do RS",
  "Prestação de serviços",
  "Prevenção",
  "Previdência",
  "Previmpa",
  "Previsão do Tempo",
  "Primeira-dama",
  "Primeira-dama de Porto Alegre, Valéria Leopoldino",
  "Primeira edição do Natal Tri Demais",
  "Primeira Edição do Projeto Porto dos Natais",
  "Primeira Infância Melhor (PIM)",
  "Primeira Infância Melhor no Contexto Prisional (Pim Prisional)",
  "Primeiros Socorros",
  "Procempa",
  "Procissão",
  "Procon",
  "Procon Móvel",
  "Procon Municipal",
  "Procurador geral do município de Porto Alegre, Roberto Silva da Rocha",
  "Procuradora-geral do município Eunice Nequete",
  "Procuradoria",
  "Procuradoria Geral",
  "Procuradoria Geral do Município",
  "Procuradoria-Geral do Município de Porto Alegre",
  "Produtor Rural",
  "Professor",
  "Professora Finalista do Prêmio RBS de Educação 2018",
  "Profissionais de Saúde",
  'programa "Lean nas Emergências"',
  "Programa Adote um Escritor",
  "Programa de escuta da comunidade",
  "Programa de Residência Técnico-Superior (PRTS)",
  "Programa de Trabalho Educativo (PTE)",
  "Programa Esfera Pública",
  "Programa Família Acolhedora",
  "Programa Jornal do Almoço",
  "Programa Jovem Aprendiz",
  "Programa Mais Comunidade",
  "Programa Melhor em Casa",
  "Programa Municipal de Rastreamento de Câncer Colorretal",
  "Programa Nacional de Gestão de Custos (PNGC)",
  "Programa Poa + Social",
  "Programa Saúde na Escola (PSE)",
  "Programa Start.edu",
  "Programa Teste e Trate",
  "Programação Cultural",
  "Programação de Novembro",
  "Programação do Reveillon",
  "Projeto 100% Digital",
  "Projeto Adote um Escritor",
  "projeto Cidade Cardioprotegida",
  "Projeto Clássicos na Pinacoteca",
  "Projeto de Lei",
  "Projeto do Trecho 3 da Orla do Guaíba",
  "Projeto Esporte Verão",
  "Projeto Feira Fora da Feira",
  "Projeto Idoso no Trânsito",
  "Projeto Inclusão em Cena 2018",
  "Projeto Jogo Limpo",
  "Projeto Kilombinho de Verão",
  "Projeto Mais Comunidade",
  "Projeto Pescar",
  "Projeto Poa Solidária",
  "Projeto Sistema de Gestão de Parcerias com as Entidades Sociais",
  "Projeto Source",
  "Prometas",
  "Promotores da Saúde da População Negra",
  "Pronto Atendimento de Traumatologia e Ortopedia no Hospital Restinga Extremo Sul",
  "Propaganda Eleitoral",
  "Propaganda Irregular",
  "Proposta orçamentária 2019",
  "Propriedades Rurais",
  "Proteção Animal",
  "PUCRS",

  "Quadras de Beach Tennis",
  "Quadrilátero Central",
  "Qualidade do Ar",
  "Quartel do Comando-Geral do Corpo de Bombeiros Militar (CBMRS)",
  "Quarto Distrito",
  "Quero- Quero",
  "Quilombos",

  "Radar de Trânsito",
  "Rádio Gaúcha",
  "raiva",
  "Ramiro Rosário",
  "Reciclagem",
  "Recital para Doação de um Piano para o Centro Cultural Multimeios Restinga",
  "Recolhimento de Resíduos",
  "Rede Calabria",
  "Rede de abastecimento de água",
  "Rede Municipal de Ensino",
  "Rede Pampa de Comunicação",
  "Rede Pública de Ensino",
  "redes de água",
  "reforma",
  "Refugiados",
  "Região Metropolitana",
  "região oeste",
  "Regularização de Escolas Comunitárias",
  "Relações Institucionais",
  "Relações Institucional",
  "Regularização",
  "Regularização Fundiária",
  "Reintegração de Posse",
  "Reitoria da Pontifícia Universidade Católica do Rio Grande do Sul (PUCRS)",
  "Relatório das pré-Conferências Municipais dos direitos da Pessoa Idosa",
  "Relatório de Gestão",
  "Remanejo",
  "Remoção de árvore",
  "remoção de lixo",
  "Renda",
  "Repavimentação asfáltica",
  "Representantes da CEF",
  "Representantes do POA Solidária",
  "Reserva Biológica do Lami José Lutzenberger",
  "Resgate",
  "Resíduos",
  "Resíduos Sólidos",
  "Resiliência",
  "Restauração",
  "Restaurante Baumbach",
  "Restaurante Orla 360",
  "Restaurante Popular",
  "Retirada de Passarela",
  "Retomada das Obras da Rua Ernesto Neugebauer",
  "Retrato",
  "Retratos Oficiais",
  "Reunião",
  "Reunião com  a ASCONTEC",
  "Reunião com a Associação Dos Procuradores Do Município De Porto Alegre (APMPA)",
  "Reunião com a BM Par",
  "Reunião com a CRIP Leste",
  "Reunião com a EPTC e Sindicatos",
  "Reunião com o Conselho do Orçamento Participativo",
  "Reunião com o Diretor regional da Caixa Econômica Federal",
  "Reunião com o Presidente da Câmara de Vereadores de Porto Alegre",
  "Reunião com representantes das entidades e das associações de praças e parques",
  "Reunião com Representantes do Banco Mundial",
  "Reunião com Supervisores das EMEFS",
  "Reunião do Comitê Executivo",
  "Reunião do UNOPS e secretaria de parcerias estratégicas",
  "Reunião no BID",
  "Reunião no International Finance Corporation (IFC)",
  "Reunião Plenária do COMUI",
  "Reunião sobre a IBERCUP",
  "Reunião sobre acolhida  ao grupo de venezuelanos",
  "Reunião Sobre Sistemas Informatizados",
  "Reunião-Almoço Menupoa",
  "Reunião-almoço Tá Na Mesa",
  "Reurbanização da Vila Tronco",
  "Reveillon 2019",
  "Réveillon 2025",
  "Réveillon de Porto Alegre - Pro Ano Nascer Feliz",
  "Réveillon Porto Alegre",
  "Revitalização",
  "Robótica",
  "Roçada",
  "Roda de Conversa Inclusiva",
  "rolo compressor",
  "Romaria de Santa Maria",
  "Romildo Bolzan Júnior",
  "ROMU",
  "roubo",
  "Roubos de fios",
  "Rua Camoati",
  "Rua Cecília Meireles",
  "Rua dos Andradas",
  "Rua Francisco Petuco",
  "Rua José Pedro Boessio",
  "Rua Olavo Bilac",
  "Ruas e avenidas",

  "S.B.C.R. Associação Comunitária Copacabana",
  "Saint Patrick's Day",
  "Sala Aldo Locatelli",
  "Sala Álvaro Moreyra",
  "Sala Cecy Frank",
  "Sala da Fonte",
  "Sala de aula",
  "Sala de monitoramento do Aedes da SES/RS",
  "Sala de Reuniões da SMPG",
  "Sala de Treinamento da SMPG",
  "Sala dos Embaixadores",
  "Sala P. F. Gastal",
  "Salão de Atos da UFRGS",
  "Salão Internacional de Desenho para Imprensa (Sidi)",
  "Salão Alberto Pasqualini",
  "Salão Negrinho do Pastoreio",
  "Salão Nobre",
  "Salão Nobre do Paço Municipal",
  "Sanção da Lei das Antenas",
  "sanção de Projeto de Lei",
  "Sangue",
  "Santa Casa de Misericórdia de Porto Alegre",
  "Santa Cecília",
  "Santa Maria Goretti",
  "Santander",
  "Santuário de Nossa Senhora do Rosário",
  "Sarampo",
  "Sarau Café com Letras",
  "Saúde",
  "Sáude",
  "Saúde Bucal",
  "Saúde da Criança e Adolescente",
  "Saúde da População Negra",
  "Saúde do Idoso",
  "Saúde do Trabalhador",
  "Saúde LGBTQIAP+",
  "Saúde Mental",
  "Saúde Nutricional e Amamentação",
  "Saúde Prisional",
  "Sebrae",
  "Secretária de Desenvolvimento Econômico e Turismo (SMDET), Júlia Evangelista Tavares.",
  "Secretária de Planejamento e Gestão",
  "Secretária Denise Russo",
  "Secretaria Estadual de Saúde do RS (SES RS)",
  "Secretaria Extraordinária do Trabalho e da Qualificação Profissional (SMTQ)",
  "secretária Juliana Castro",
  "Secretária Municipal Cultura e Economia Criativa, Liliana Cardoso",
  "Secretaria Municipal da Fazenda (SMF)",
  "secretária municipal da Fazenda (SMF), Ana Pellini",
  "Secretaria Municipal de Administração e Patrimônio (SMAP)",
  "Secretaria Municipal de Assistência Social (SMAS)",
  "Secretaria Municipal de Cultura (SMC)",
  "Secretaria Municipal de Cultura e Economia Criativa (SMCEC)",
  "Secretaria Municipal de Desenvolvimento Econômico (SMDE)",
  "Secretaria Municipal de Desenvolvimento Econômico e Turismo (SMDET)",
  "Secretaria municipal de Desenvolvimento Econômico, Turismo e Eventos (SMDETE)",
  "secretária municipal de Desenvolvimento Econômico, Turismo e Eventos (SMDETE), Rosani Alves Pereira",
  "Secretaria Municipal de Desenvolvimento Social (SMDS)",
  "Secretaria Municipal de Desenvolvimento Social e Esporte (SMDSE)",
  "Secretária municipal da Educação (SMED)",
  "Secretaria Municipal de Educação (SMED)",
  "Secretaria Municipal de Esporte, Lazer e Juventude (SMELJ)",
  "Secretária municipal de Esporte, Lazer e Juventude (SMELJ), Débora Garcia",
  "Secretaria Municipal de Governança Cidadã e Desenvolvimento Rural (Smgov)",
  "Secretaria Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretaria Municipal de Habitação e Regularização Fundiária (SMHARF)",
  "Secretária municipal de Habitação e Regularização Fundiária, Simone Somensi",
  "Secretaria Municipal de Inclusão e Desenvovimento Humano",
  "secretaria municipal de Inlcusão e Desenvolvimento Humano (SMIDH)",
  "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (SMAMUS)",
  "Secretaria Municipal de Mobilidade Urbana (SMMU)",
  "Secretaria Municipal de Obras e Infraestrutura (SMOI)",
  "Secretaria Municipal de Parcerias (SMP)",
  "Secretaria Municipal de Planejamento e Assuntos Estratégicos (SMPAE)",
  "Secretaria Municipal de Planejamento e Gestão (SMPG)",
  "Secretaria Municipal de Relações Institucionais (SMRI)",
  "Secretaria Municipal de Relações Institucionais e Articulação Política (SMRI)",
  "Secretaria Municipal de Saúde (SMS)",
  "Secretaria Municipal de Segurança (SMSEG)",
  "Secretaria Municipal de Serviços Urbanos (SMSURB)",
  "Secretaria Municipal de Transparência e Controladoria (SMTC)",
  "Secretária Municipal de Transparência e Controladoria (SMTC), Mônica Leal",
  "Secretaria Municipal do Meio Ambiente e da Sustentabilidade (SMAMS)",
  "Secretária Nádia Gerhard",
  "secretária-adjunta da SMED Ivana Genro",
  "Secretariado",
  "Secretário da SMAMS, Maurício Fernandes",
  "Secretário Eduardo Cidade",
  "Secretário Estadual dos Transportes Juvir Costella",
  "Secretário Municipal da Educação (SMED)",
  "Secretário Municipal da Fazenda (SMF)",
  "Secretário municipal da Fazenda, Rodrigo Fantinel",
  "Secretário Municipal da Saúde (SMS)",
  "Secretário Municipal da Saúde (SMS), Fernando Ritter",
  "Secretário municipal da Segurança, Alexandre Augusto Aragon",
  "Secretário Municipal de Administração e Patrimônio (SMAP)",
  "Secretário municipal de Administração e Patrimônio, André Barbosa",
  "Secretário Municipal de Comunicação Orestes de Andrade Jr.",
  "Secretário Municipal de Desenvolvimento Social (SMDS), Jorge Brasil",
  "Secretário municipal de Desenvolvimento Social, Leo Voigt",
  "Secretário Municipal de Educação Adriano Naves de Brito",
  "Secretário municipal de Educação, Leonardo Pascoal",
  "Secretário Municipal da Educação (SMED), Maurício Cunha",
  "secretário municipal de Esporte e Lazer, Professor Tovi",
  "secretário municipal de Governança Cidadã e Desenvolvimento Rural (Smgov), Cássio Trogildo.",
  "Secretário Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretário municipal de Governança Local e Coordenação Política, Cássio Trogildo",
  "secretário municipal de Inlcusão e Desenvolvimento Humano (SMIDH), Juliano Passini",
  "Secretário municipal de Mobilidade Urbana, Adão de Castro Júnior",
  "Secretário municipal de Obras e Infraestrutura, André Flores",
  "Secretário municipal de Planejamento e Assuntos Estratégicos, Cezar Schirmer",
  "Secretário municipal de Planejamento e Gestão, Cezar Schirmer (SMPG)",
  "Secretário Municipal de Serviços Urbanos (SMSUrb)",
  "Secretário municipal de Transparência e Controladoria, Gustavo Ferenci",
  "Secretário municipal do Gabinete de Inovação, Luiz Carlos Pinto da Silva Filho",
  "Secretário municipal do Meio Ambiente, Urbanismo e Sustentabilidade, Germano Bremm",
  "Secretário-adjunto municipal de Governança Local e Coordenação Política, Luciano Marcantonio",
  "Secretário-adjunto de Planejamento e Gestão",
  "Sede da EPTC",
  "Sede da SMED",
  "Sede da SMPG",
  "Sede do Comando Militar do Sul",
  "Sede do Detran -RS",
  "Sede do Previmpa",
  "Sede do Tribunal de Contas do Estado (TCE)",
  "Sede social da SERGS",
  "Seguranç",
  "Segurança",
  "Segurança do Paciente",
  "Segurança Publica",
  "Segurança Pública",
  "Seletiva no Contêiner",
  "Semáforos",
  "Semana Acadêmica da Escola de Engenharia",
  "Semana Cidade Limpa",
  "Semana da Água",
  "Semana da Consciência Negra",
  "Semana de Porto Alegre",
  "Semana do Japão",
  "Semana Farroupilha",
  "Semanas Internacionais",
  "Seminário",
  "Seminário Boas Práticas na Gestão de Trânsito dos Municípios",
  "Seminário Compliance",
  "Seminário da Rede de Acolhimento Municipal – Criança e Adolescente",
  "Seminário do Comitê de Aleitamento Materno e Alimentação Complementar Saudável de Porto Alegre",
  "Seminário Nacional de Trânsito - Mobilidade Sustentável, Educação, e Segurança",
  "Seminário pela Visibilidade Trans",
  "Seminário POA 2020",
  "Seminário Povos Indígenas e Saúde: Um Corpo São",
  "Senac",
  "Serviço de Atendimento Móvel de Urgência (SAMU)",
  "Serviço Funerário",
  "Serviço Social",
  "Serviços de Roçada e Capina",
  "Serviços Ortopédicos",
  "Serviços Urbanos",
  "Servidor",
  "Sessão de julgamento da 1ª Câmara do TART",
  "Sessão especial de posse da Mesa Diretora de 2019",
  "Sessão Solene de outorga de Título de Cidadão de Porto Alegre ao Presidente Estadual da Assembleia de Deus Pastor Adalberto Santos Dutra",
  "Sessão Solene de Posse da OAB/RS Triênio 2019/2021",
  "Sesc",
  "SESI",
  "Sétimo encontro de Medicina Tradicional Kaingang",
  "Shopping Total",
  "Show de Talentos",
  "Show de Talentos da FASC",
  "Sífilis",
  "Simpósio",
  "Sinalização de trânsito",
  "sinalização semafórica",
  "Sinalização viária",
  "Sindha",
  "Sindicato dos Municipários de Porto Alegre (Simpa)",
  "Sindilojas",
  "síndrome de down",
  "Sine Municipal",
  "Sistema de Monitoramento de Tráfego Eletrônico",
  "Sistema Fecomércio RS",
  "Sistema Único de Saúde (SUS)",
  "Sítio do Mato",
  "Situação de rua",
  "Skate",
  "Smams",
  "SMAMS",
  "Smamus",
  "Smc",
  "Smc -",
  "SMC - 1ª Invernada Farroupilha Paixão Cortes 2018 Mostra de Dança",
  "SMC - FUMPROARTE comemora 25 anos",
  "Smc - Poa Em Cena",
  "Smde",
  "SMDE - Secretaria Municipal de Desenvolvimento Econômico",
  "Smdes",
  "Smdete",
  "Smds",
  "Smdse",
  "SMDSE - Desenvolvimento Social e Esporte",
  "Smed",
  "SMED",
  "Smf",
  "SMF",
  "Smgov",
  "Smic",
  "Smidh",
  "Smim",
  "SMIM - Infraestrutura e Mobilidade Urbana",
  "Smoi",
  "Smpe",
  "Smpg",
  "Smri",
  "Sms",
  "SMS",
  "Smseg",
  "Smseg - Segurança",
  "SMSEG - Segurança",
  "Smsurb",
  "SMSURB",
  "Smtc",
  "SMTC - Marco Regulatório das Organizações da Sociedade Civil",
  "SMTC - Transparência e Controladoria Geral",
  "Smurb",
  "Socioambiental",
  "Sociedade Beneficente Cultural Bambas da Orgia",
  "Sociedade Beneficente Cultural e Filantrópica Protegidos da Princesa Isabel",
  "Sociedade Beneficente Cultural e Recreativa Fidalgos e Aristocratas",
  "Sociedade Beneficente Cultural e Recreativa Imperatriz Dona Leopoldina",
  "Sociedade Beneficente Cultural Realeza",
  "Sociedade Beneficente Recreativa e Cultural Academia de Samba Unidos da Vila Mapa",
  "Sociedade Beneficente Recreativa Imperadores do Samba",
  "Sociedade Cultural Beneficente e Carnavalesca Império do Sol",
  "Sociedade Cultural e Beneficiente Acadêmicos de Gravataí",
  "Sociedade de Engenharia do Rio Grande do Sul (Sergs)",
  "Sociedade Esportiva, Recreativa, Cultural e Comunitária Ervino de Assis - SER ASSIS",
  "Sociedade Libanesa de Porto Alegre",
  "Sociedade Recreativa Beneficente Carnavalesca Academia de Samba União da Tinga",
  "Sociedade Recreativa Beneficente Tribo Carnavalesca Os Comanches",
  "Sociedade Recreativa Cultural e Carnavalesca Academia de Samba Unidos de Vila Isabel",
  "Sociedade Recreativa e Beneficente Estado Maior da Restinga",
  "Sol",
  "Solenidade de transmissão do Cargo do Procurador-Geral do Estado",
  "Solidariedade",
  "Sport Club Internacional",
  "STU Pro-Tur 2025",
  "Subprefeituras",
  "Sustentabilidade",

  "Tabagismo",
  "Tapa Buracos",
  "Talude",
  "Tarifa",
  "Táxi",
  "Táxis Novos",
  "taxistas",
  "Teatro",
  "Teatro Carlos Carvalho",
  "Teatro da AMRIGS",
  "Teatro da Unisinos",
  "Teatro Dante Barone da Assembleia Legislativa",
  "Teatro de Câmara Túlio Piva",
  "teatro de rua",
  "Teatro do Bourbon Country",
  "Teatro do CIEE",
  "Teatro do Sesc",
  "Teatro do Sesi",
  "Teatro Moacyr Scliar da Universidade de Ciências da Saúde de Porto Alegre",
  "Teatro Renascença",
  "Tecnologia",
  "Telefonia",
  "Telemedicina",
  "TelessaúdeRS",
  "Tempo",
  "Temporada das Piscinas Comunitárias de Porto Alegre",
  "Temporal",
  "Tenda",
  "Terminais de ônibus",
  "Terminal Praia de Belas",
  "Terminal Parobé",
  "Terminal Triângulo",
  "Termo de Adoção de Verde Complementar",
  "Termo de Adoção do Parque Marechal Mascarenhas de Moraes",
  "Termo de Cooperação Técnica",
  "Termos de Permissão uso bares da Orla do Guaíba",
  "Termos para criação de mais dois CAPs",
  "Terreno",
  "Testagem",
  "Teste do Pezinho",
  "teste rápido sífilis, hiv e hepatite C",
  "Theatro São Pedro",
  "TJ-RS",
  "Todos Contra O Assédio",
  "Todos Somos Porto Alegre",
  "Top de Marketing ADVB/RS",
  "Torneio Internacional de Futebol Infantil",
  "Totem de atendimento 156",
  "Totem iluminado",
  "Trabalho e Emprego",
  "Trabalho e Qualificação",
  "Trade Commissioner",
  "Tradição",
  "Tradicionalismo",
  "Transexualidade",
  "trânsito",
  "Trânsito",
  "Trânsito e Circulaçâo",
  "Trânsito e Circulação",
  "Transito e Transporte",
  "Transmissão de Cargo",
  "Transparência",
  "Transparência e Controladoria",
  "Transparência e Controladoria Geral",
  "Transporte",
  "Transporte Coletivo",
  "Transporte e Circulaçao",
  "Transporte e Circulação",
  "Transporte fluvial de passageiros",
  "Transporte Irregular de Produtos Perigosos",
  "Transporte Metropolitano",
  "Transporte Público",
  "Transtornos no trânsito",
  "Tratamento de água",
  "Travessa dos Venezianos",
  "Trecho 3 da Orla do Guaíba",
  "Treinamento",
  "Treinamento da Cruz Vermelha",
  "Trensurb",
  "Tribunal de Contas do Estado do Rio Grande do Sul (TCE-RS)",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Tribunal Regional Eleitoral (TRE)",
  "Tributação",
  "Tributo a Elis Regina",
  "Trilha",
  "Trincheira da Av. Cristóvão Colombo",
  "Trincheira da Ceará",
  "Tristeza",
  "Troféu “Atitudes que dão show”",
  "troféu Prefeito Inovador",
  "Túnel da Conceição",
  "Turismo",

  "Ulbra",
  "UM DIA DE AGENTE DA EPTC",
  "Unesco",
  "Unidade de Coleta e Transfusão (UCT) do HPS",
  "Unidade de Pronto Atendimento (UPA)",
  "Unidade de Saúde",
  "Unidade de Saúde 1º de Maio",
  "Unidade de Saúde Animal Victória (Usav)",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Fradique Vizeu",
  "Unidade de Saúde Modelo",
  "Unidade de Saúde Panorama",
  "Unidade de Saúde Ponta Grossa",
  "Unidade de Saúde Santa Marta",
  "Unidade de Saúde São Carlos",
  "Unidade de Saúde Tristeza",
  "Unidade de Vigilância Ambiental (UVA)",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "Uniritter",
  "Unisinos",
  "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)",
  "Universidade Federal do Rio Grande do Sul (UFRGS)",
  "UPA Moacyr Scliar",
  "Urbanismo",
  "Urbanização",
  "Usina do Gasômetro",

  "V Conferência Municipal dos Direitos da Pessoa Idosa",
  "Vacina",
  "vacina contra a Dengue",
  "vacina em animais",
  "Vacinação",
  "Vagas de Emprego",
  "Valtuir Pereira Nunes",
  "Vandalismo",
  "Varejo",
  "veículo",
  "Veículo Roubado",
  "Veículos",
  "Venezuelanos",
  "Vento",
  "Vera Armando",
  "Verão",
  "vereador",
  "vereador Cassiá Carpes",
  "Vereador Giovane Byl",
  "Vereador Moisés Barboza",
  "vereadora",
  "Vereadores",
  "Viaduto Conceição",
  "Viaduto da Conceição",
  "Viaduto Dom Pedro I",
  "Viaduto Otávio Rocha",
  "Viaduto Utzig",
  "viagem",
  "Viagem à Brasília",
  "Viagem à Europa",
  "Viagem à Holanda",
  "viagem internacional",
  "Viagem Segura EPTC",
  "Vice-governador Gabriel Souza",
  "Vice-Governador José Paulo Dornelles Cairoli",
  "Vice-prefeita, Betina Worm",
  "Vice-prefeita de Porto Alegre, Betina Worm",
  "Vice-prefeito",
  "Vice-prefeito de Porto Alegre, Ricardo Gomes",
  "vice-prefeito Gustavo Paim",
  "vice-prefeito Ricardo Gomes",
  "Videoconferência",
  "Videomonitoramento",
  "Vigidesastres",
  "Vigilância de Alimentos",
  "Vigilância em Saúde",
  "Vigilância Em Saúde",
  "Vigilância Sanitária",
  "VIII Seminário de Saúde e Segurança no Trabalho",
  "Vila dos Ferroviários",
  "Vila dos Sargentos",
  "Vila Ipiranga",
  "Vila Jardim",
  "Vila Monte Cristo",
  "Vila Nova",
  "Vírus T-linfotrópico humano (HTLV)",
  "Visita",
  "Visita de Cortesia",
  "Visita dos Alunos do IFRS da Restinga ao Poa.Hub",
  "Visita domiciliar",
  "visita institucional",
  "Visita Técnica",
  "Vistoria",
  "Vistoria Obras Restaurante Panorâmico",
  "Vítimas",
  "Viva o Centro a Pé",
  "Viva Porto Alegre a Pé",
  "Viveiro municipal de Porto Alegre",
  "Vôlei",
  "Volta às aulas",
  "Voluntariado",
  "votação",
  "Votação do programa Família Acolhedora",

  "Wambert Gomes Di Lorenzo",
  "WhatsApp",
  "Workshop",
  "Workshop Gestão da Inovação na Administração Pública",

  "Xangai",
  "XI Prêmio EPTC de Educação para o Trânsito",
  "XVº Congresso Internacional de Cidades Educadoras",
  "XXVIII Colônia de Férias para Idosos",

  "Zizi Possi",
  "Zona Leste",
  "Zona Norte",
  "Zona Rural",
  "Zona Sul",
  "Zona Urbana",
];
