export const validTags = [
  "relações Institucionais",
  "(EBAB) Moinhos de Vento",
  "(Emei JP) Cantinho Amigo",
  "(Emei) Florência Vurlod Socias",
  "#eufaçopoa",
  "#proconpoaresponde",
  "“Tamo Junto na Rua”",

  "1ª Expo-Feira Náutica Almirante Tamandaré 2019",
  "1ª Faixa Reversível semafórica de Porto Alegre",
  "1º Festival de Arte e Cultura Senegalesa",
  "1º Fórum das Cidades Inteligentes, Humanizadas e Inovadoras - Smart Cities",
  "126 Anos da Guarda Municipal de Porto Alegre",
  "14ª edição do Campeonato Porto Alegre de Handebol 2018",
  "14ª Gincana Ambiental",
  "15ª Chegada do Papai Noel - Abertura oficial do Natal de Porto Alegre",
  "149 anos do Mercado Público",
  "17ª Edição dos Jogos Municipais da Terceira Idade",
  "20 Anos da Mostra dos Servidores do DMAE",
  "25 Anos do  FUMPROARTE",
  "25ª Corrida pela Vida",
  "25º POA Em Cena",
  "3ª Edição da Mostra Cultural Eixo Baltazar",
  "3º Inclusão em Cena",
  "30 Anos da Defesa Civil",
  "30 Anos da Kinder",
  "32º Festival de Arte da Cidade de Porto Alegre",
  "34ª Festa do Pêssego Municipal",
  "4º Distrito",
  "48º Troféu Seival e 29ª Regata Farroupilha",
  "59º Festival Hípico Noturno em Porto Alegre",
  "64ª Edição da Feira do Livro de Porto Alegre",
  "8ª Edição do Curso de Multiplicadores de Educação para o Trânsito sobre o Pedestre Idoso",
  "8ª Semana Municipal da Água",
  "90 Anos da Cinemateca Capitólio",

  "A Cara da Obra",
  "Abandono de Veículos",
  "Abastecimento",
  "Abertura",
  "ABRH",
  "Abrigo de Animais da EPTC",
  "Abrigo Residencial AR 7",
  "Abrigos",
  "Abrigos Residenciais - AR 7 e 8",
  "academias ao ar livre",
  "Acampamento 2018",
  "Acampamento Farropilha",
  "Acampamento Farroupilha",
  "Ação Educativa",
  "Ação Conjunta de Fiscalização",
  "Ação de Pulverização de Inseticida",
  "Ação Integrada",
  "Ação Mais Comunidade",
  "Ação Rua",
  "Ação Social",
  "Acessibilidade",
  "Acidente",
  "Acidentalidade",
  "Acolhimento",
  "Administração",
  "Administração e Patrimônio",
  "Administração É Patrimônio",
  "Adoção de animais",
  "Adolescente",
  "Adote um Escritor",
  "Adutora",
  "Aedes aegypti",
  "Aéreas",
  "Aeronáutica",
  "Aeroporto Internacional Salgado Filho",
  "Aeroporto Salgado Filho",
  "Agência Estadual de Regulação dos Serviços Públicos Delegados do Rio Grande do Sul (AGERGS)",
  "Agente de Combate às Endemias (ACE)",
  "Agentes Comunitários de Saúde (ACS)",
  "Agentes de Fiscalização",
  "Agentes de Trânsito",
  "Água",
  "Água e Esgoto",
  "Água e Esgotos",
  "Aids",
  "Alagamento",
  "Albergue Felipe Diehl",
  "Albergue Municipal",
  "Albergues",
  "Álcool  e Outras Drogas",
  "Aldeia do Morro do Osso",
  "Aldeia Indígena",
  "Aldeia Kaingang",
  "Aleitamento materno",
  "Alerta",
  "Alimentação",
  "Alimento",
  "Aluno",
  "Alunos",
  "Alvará",
  "Amamentação",
  "Ambulância",
  "Ambulantes",
  "Ambulatório Odontológico",
  "Análises clínicas",
  "André Coronel",
  "Animal silvestre",
  "Aniversário",
  "Aniversário de 6 Anos do CEIC",
  "Aniversário do Parque Moinhos de Vento",
  "Anfiteatro Pôr do Sol",
  "Apae",
  "Aplicativo 156+POA",
  "Aplicativo (app)",
  "Apreensão",
  "Apresentação",
  "Área Azul",
  "Área de risco",
  "Arena do Grêmio",
  "Arquipélago (Ilhas)",
  "Arquivo",
  "Arquivo Histórico Moysés Vellinho",
  "Arrecadação Fiscal",
  "Arroio Cavalhada",
  "Arroio Dilúvio",
  "Arroio Sarandi",
  "Arte Cemiterial",
  "Arte Urbana",
  "Artes Cênicas",
  "Artes Plásticas",
  "Artes Visuais",
  "Artesanato",
  "Árvore",
  "Asfalto",
  "Asilo Padre Cacique",
  "Assembleia de Verão da Famurs 2025",
  "Assembléia Legislativa",
  "Assinatura",
  "Assistência Farmacêutica",
  "Assistência Hospitalar",
  "Assistencia Social",
  "Assistência Social",
  "Associação Comercial de Porto Alegre (ACPA)",
  "Associação Comunitária Núcleo Esperança",
  "Associação do Corpo Consular RS",
  "Associação dos Auditores Fiscais da Receita Municipal de Porto Alegre (Aiamu)",
  "Associação dos Municípios da Região Metropolitana de Porto Alegre (Granpal)",
  "Associação dos Transportadores de Caçamba Estacionárias (ATCE)",
  "Associação Hospitalar Vila Nova",
  "Associação Internacional de Parques Científicos e Áreas de Inovação (IASP)",
  "Atelier Livre Xico Stockinger",
  "Atenção Ambulatorial, Hospitalar e Urgências",
  "Atenção Básica",
  "Atenção Especializada à Saúde",
  "Atenção Primária à Saúde (APS)",
  "Atendimento em Casa",
  "Atendimento Improvisado",
  "Atendimento",
  "Atendimento de Urgência",
  "Atividade Alusiva ao Combate à Violência no Trânsito",
  "atividade física",
  "Atletismo",
  "Ato de Apresentação do Programa Família Acolhedora",
  "Ato de Entrega da Obras de Melhoria da Praça Argentina, e da Assinatura do Termo de Adoção da praça pela Santa Casa de Misericórdia de Porto Alegre",
  "Audiência",
  "Auditório Araújo Vianna",
  "Auditório da EPTC",
  "Auditório da FAMURS",
  "Auditório da Puc",
  "Auditório da SMED",
  "Auditório da SMPG",
  "Auditório da SMTC",
  "Auditório do Departamento Municipal de Habitação (Demhab)",
  "Auditório do Global Tecnopuc",
  "Auditório do Instituto Cultural",
  "Auditório do Ministério Público",
  "Auditório do prédio II da UFCSPA",
  "Auditório Marcelo Dario Kifne - MP-RS",
  "Augusto Buchweitz",
  "Aula aberta",
  "Aula Inaugural",
  "Av. Mauá",
  "Av. Tronco",
  "Av. Wenceslau Escobar",
  "Ave",
  "Avenida Assis Brasil",
  "Avenida Castello Branco",
  "Avenida Coronel Marcos",
  "Avenida Eduardo Prado",
  "Avenida Goethe",
  "Avenida Ipiranga",
  "Avenida João Pessoa",
  "Avenida Nilo Peçanha",
  "Avenida Nonoai",
  "Avenida Padre Cacique",
  "Avenida Severo Dullius",
  "Avenida Venâncio Aires",
  "Avenida Voluntários da Pátria",

  "Bairro Anchieta",
  "Bairro Azenha",
  "Bairro Belém Novo",
  "Bairro Belém Velho",
  "Bairro Boa Vista",
  "Bairro Bom Fim",
  "Bairro Bom Jesus",
  "Bairro Campo Novo",
  "Bairro Cavalhada",
  "Bairro Centro Histórico",
  "Bairro Cidade Baixa",
  "Bairro Coronel Aparício Borges",
  "Bairro Cristal",
  "Bairro Cruzeiro",
  "Bairro Farrapos",
  "Bairro Floresta",
  "Bairro Glória",
  "Bairro Guarujá",
  "Bairro Hípica",
  "Bairro Humaitá",
  "Bairro IAPI",
  "Bairro Ipanema",
  "Bairro Jardim Carvalho",
  "Bairro Jardim Planalto",
  "Bairro Lami",
  "Bairro Lomba do Pinheiro",
  "Bairro Mário Quintana",
  "Bairro Medianeira",
  "Bairro Menino Deus",
  "Bairro Moinhos de Vento",
  "Bairro Navegantes",
  "Bairro Nonoai",
  "Bairro Partenon",
  "Bairro Petrópolis",
  "Bairro Ponta Grossa",
  "Bairro Praia de Belas",
  "bairro Restinga",
  "Bairro Restinga",
  "Bairro Rubem Berta",
  "Bairro São Geraldo",
  "Bairro São José",
  "Bairro Santa Tereza",
  "Bairro Santo Antônio",
  "Bairro Sarandi",
  "Bairro Teresópolis",
  "Bairro Vila Farrapos",
  "Bairro Vila Ipiranga",
  "Balada Segura",
  "Balanço",
  "Banco de Desarrollo de América Latina (CAF )",
  "Banco de Leite Humano",
  "Banco de Sangue",
  "Banco Nacional de Desenvolvimento Econômico e Social (BNDES)",
  "Banda Municipal",
  "Baronesa do Gravataí",
  "BarraShoppingSul",
  "Basquete",
  "Benchmarking do Governo do Rio Grande do Norte",
  "Biblioteca da Escola de Educação Infantil Paulo Freire",
  "Biblioteca do Parcão",
  "Biblioteca Ecológica Infantil Maria Dinorah",
  "Bicicleta",
  "Bikepoa",
  "Blitz",
  "Bloqueio no trânsito",
  "Bloqueio químico",
  "Bocha",
  "Bolsa Família",
  "Bombeiros",
  "Brechó",
  "Brechocão",
  "Brigada Militar",
  "Brinquedo",
  "Brique da Redenção",
  "BRT's",
  "Bruno Vanuzzi",
  "bullying",

  "Cabines Telefônicas",
  "Cachorro",
  "cachorródromo",
  "Cadastro Único",
  "CÃES",
  "Café Coworking do Parque Científico e Tecnológico da PUCRS (TecnoPuc)",
  "Cais Mauá",
  "Caixa Econômica Federal",
  "calçadão de Ipanema",
  "Calor",
  "Camaquã",
  "Câmara de Vereadores",
  "Câmara Municipal de Porto Alegre (CMPA)",
  "Câmara Rio-Grandense do Livro",
  "Caminhada",
  "Caminho do Gol",
  "Caminho dos Jacarandás",
  "caminhões-pipa",
  "Caminhos Rurais",
  "Campanha",
  "Campanha do Agasalho",
  "Campanha do Brinquedo Solidário",
  "Campanha Nacional de Vacinação contra Gripe (influenza)",
  "Campeonato",
  "Campus da Unisinos Porto Alegre",
  "Câncer",
  "Câncer Bucal",
  "Câncer de Mama",
  "Capacitação",
  "Capacitação - Controle Social e Educação: Projeto-Piloto de capacitação de conselheiros escolares",
  "Capacitação e Gerenciamento de Projetos Prioritários de Governo",
  "Capester",
  "Capina",
  "Capital Gaúcha",
  "Carnaval",
  "Carnaval 2017",
  "Carnaval de Rua",
  "Carnaval Porto Alegre 2025",
  "Carris",
  "Carro",
  "Cartão Material Escolar",
  "Casa de Apoio Viva Maria",
  "Casa de Bombas",
  "Casa de Cultura Mario Quintana",
  "Casa do Gaúcho",
  "Casa dos Conselhos",
  "Casa Lar do Idoso",
  "Casa NTX",
  "Casamento",
  "Catamarã",
  "Catedral Metropolitana de Porto Alegre (Matriz)",
  "Causa Animal",
  "Cavalo",
  "CDL Porto Alegre",
  "Cecoflor",
  "CEEE Equatorial",
  "Ceic",
  "CEIC",
  "Cel QOEM Mário Yukio Ikeda",
  "Cel. Evaldo Rodrigues Oliveira",
  "Celebração do Dia da Criança",
  "Cemitério da Santa Casa de Misericórdia",
  "Centro Administrativo Municipal (CAM)",
  "Centro Administrativo Municipal Guilherme Socias Villela",
  "Centro Cultural da Universidade Federal do Rio Grande do Sul (UFRGS)",
  "Centro Cultural Multimeios Restinga",
  "Centro Cultural Usina do Gasômetro",
  "Centro da Comunidade Parque Madepinho (Cecopam)",
  "Centro de Artes e Esporte da Restinga (CEU)",
  "Centro de Atenção Psicossocial Álcool e Drogas (CAPS AD)",
  "Centro de Cultura Lupicínio Rodrigues",
  "Centro de Eventos da Amrigs",
  "Centro de Informações Estratégicas em Vigilância em Saúde (Cievs)",
  "Centro de Integração Empresa Escola do Rio Grande do Sul (CIEE-RS)",
  "Centro de Referência em Saúde do Trabalhador (Cerest)",
  "Centro de Saúde Modelo",
  "Centro de Saúde Murialdo",
  "Centro de Saúde Navegantes",
  "Centro de Saúde Santa Marta",
  "Centro de triagem",
  "Centro de Valorização da Vida",
  "Centro Histórico",
  "Centro Humanístico Vida",
  "Centro Integrado de Comando",
  "Centro Integrado de Comando da Cidade de Porto Alegre (CEIC)",
  "Centro Integrado de Coordenação e Serviços da Cidade de Porto Alegre (CEIC)",
  "Centro Municipal de Cultura",
  "Centro Popular de Compras (CPC)",
  "Centro Social Marista - CESMAR",
  "Cerimônia de Apresentação de PLs de Concessão e Adoção",
  "Cerimônia de posse da Comissão de Saúde e Segurança do Trabalho da PGM",
  "Cercamento Eletrônico",
  "Cerimônia",
  "Cerimônia de posse gestão 2025/2028",
  "Certificado",
  "CETE - Centro Estadual de Treinamento Esportivo",
  "CGVS",
  "Chalé da Praça XV de Novembro",
  "Chikungunya",
  "Chimarrão",
  "Chuva",
  "Ciclo de Palestras da Transparência",
  "Ciclovia",
  "Cidadania",
  "Cidades Educadoras",
  "Cinemateca Capitólio",
  "Circulação",
  "Circulação e Transporte",
  "Clássicos na Pinacoteca",
  "clima",
  "Clínica da Família",
  "CMDUA",
  "Colégio Militar de Porto Alegre",
  "Colégio São Judas Tadeu",
  "Coleta",
  "Coleta Seletiva",
  "Coletiva de Imprensa",
  "Colônia de Pescadores Z5",
  "Comandante da Guarda Municipal, Marcelo Nascimento",
  "Comandante Nádia",
  "Comando Militar do Sul",
  "Combate a Dengue",
  "Comcet",
  "Comércio",
  "Comércio Irregular",
  "Comissão da Pessoa com Deficiência",
  "Comissão de Saúde e Meio Ambiente da CMPA (Cosmam)",
  "Comissão de Saúde e Segurança no Trabalho",
  "Comissão Permanente de Atuação em Emergências (Copae)",
  "Comitê do Projeto Vida no Trânsito",
  "Comitê Municipal de Transmissão Vertical do HIV e Sífilis Congênita",
  "Companhia Carris Porto Alegrense",
  "Companhia de Processamento de Dados do Município (Procempa)",
  "Companhia Municipal de Dança",
  "Complexo Cultural Porto Seco",
  "Complexo Hospitalar Santa Casa",
  "comportas do Muro da Mauá",
  "Compostagem",
  "Computador",
  "COMTU",
  "Comui",
  "Comunicação",
  "Comunicação Social",
  "Conaf",
  "Concerto Musical",
  "Concurso",
  "Conferência",
  "Conferência Municipal do Meio Ambiente",
  "Conscientização",
  "Conselho do OP",
  "Conselho Municipal de Assistência Social (CMAS)",
  "Conselho Municipal de Saúde",
  "Conselho Superior da PGM",
  "Conselhos Municipais",
  "Conserto Didático da Banda Municipal de Porto Alegre",
  "Cônsul da Ucrânia no Brasil",
  "Cônsul do Japão em Porto Alegre",
  "Cônsul-Geral dos Estados Unidos em Porto Alegre",
  "Cônsul-Geral dos Estados Unidos, Sr. Jason Green.",
  "Consulado",
  "Consultório na Rua",
  "Consumidor",
  "Contrato com a Caixa Econômica Federal (CEF)",
  "Controladoria",
  "Convênio",
  "Convite",
  "Coordenação de Operações Especiais (COE)",
  "Coordenação Municipal de Urgências (CMU)",
  "Coordenações",
  "Cootravipa",
  "Coronavírus",
  "Corredor Humanitário",
  "Corregedoria",
  "Corrida",
  "Covid-19",
  "Criança",
  "CRIPs",
  "Cruz Vermelha do Brasil",
  "Cultura",
  "Cultura e Economia Criativa",
  "Cultura Economia Criativa",
  "Curso",
  "Curso de Formação",
  "Curso de Mecânica",

  "Dança",
  "Debate",
  "Declaração de Edimburgo",
  "Defesa Civil",
  "Defesa Civil de Porto Alegre-RS",
  "Demhab",
  "Dengue",
  "Departamento de Arrecação e Cobrança (DAC)",
  "Departamento de Iluminação Pública (DIP)",
  "Departamento Estadual de Trânsito (Detran)",
  "Departamento Municipal de Água e Esgotos (DMAE)",
  "Departamento Municipal de Habitação (Demhab)",
  "Departamento Municipal de Limpeza Urbana (DMLU)",
  "Departamento Nacional de Infraestrutura de Transportes (Dnit)",
  "Deputado Estadual Fixinha",
  "Desabrigados",
  "Desafio Microrrevoluções Urbanas",
  "Desastres",
  "Descida da Borges",
  "Desenvolviment Econômico",
  "Desenvolvimento",
  "Desenvolvimento Economico",
  "Desenvolvimento Econômico",
  "Desenvolvimento Economico e Esporte",
  "Desenvolvimento Social",
  "Desenvolvimento Social e Esporte",
  "Desfile Farroupilha 2018",
  "Deslizamento",
  "desvio de trânsito",
  "Dia D",
  "Dia D de Vacinação",
  "Dia da Criança",
  "Dia das Crianças",
  "Dia de Finados",
  "Dia do Desafio",
  "Dia do Gari",
  "Dia do Livro",
  "Dia Mundial da Alimentação",
  "DIA SEM CARRO",
  "Dique",
  "Direito do Consumidor",
  "Direitos Animais",
  "Direitos do Consumidor",
  "Direitos dos Animais",
  "Direitos Humanos",
  "Diretor-geral do DMAE",
  "diretor-presidente da EPTC",
  "diretor-presidente do DMAE, Maurício Loss",
  "Diretoria de Esporte, Recreação e Lazer (Diresp)",
  "Diretoria de Vigilância em Saúde (DVS)",
  "Diversidade sexual",
  "Dmae",
  "DMAE",
  "DMAP",
  "Dmlu",
  "DMLU",
  "Doação",
  "doação de sangue",
  "doação e transplante de órgãos",
  "Doações",
  "doações de cestas básicas",
  "Doações de Materiais",
  "Doença Respiratória",
  "Doenças Transmissíveis",
  "Donativos",
  "Downburst",
  "Dragagem",
  "Drenagem",
  "Drone",

  "E.E.E.F. Uruguai",
  "Ecobarreira",
  "Economia",
  "Economia Solidária",
  "Edifício Intendente José Montaury",
  "Educação",
  "Educação Ambiental",
  "Educação Básica",
  "Educação Especial",
  "Educação Fundamental",
  "Educação Infantil",
  "Educação no Trânsito",
  "Educação Permanente",
  "Educação Superior",
  "Eixo Baltazar",
  "eleições",
  "Eleições 2018",
  "Em Cena",
  "Embaixada",
  "Embratel",
  "Emeb Liberato Salzano Vieira da Cunha",
  "Emeef Elyseu Paglioli",
  "EMEF",
  "Emef Anísio Teixeira",
  "EMEF Deputado Marcírio Goulart Loureiro",
  "EMEF Gabriel Obino",
  "EMEF Grande Oriente do Rio Grande do Sul",
  "Emef Ildo Meneguetti",
  "EMEF João Carlos D`Ávila Paixão Côrtes (Laçador)",
  "Emef Leocádia Felizardo Prestes",
  "EMEF Leopolda Barnewitz",
  "EMEF Mario Quintana",
  "Emef Migrantes",
  "EMEF Migrantes",
  "Emef Nossa Senhora do Carmo",
  "Emef Pepita de Leão",
  "EMEF Porto Novo",
  "Emef Presidente Vargas",
  "EMEF Professora Ana Íris do Amaral",
  "Emef Vereador Antonio Giúdice",
  "EMEF Vereador Antônio Giúdice",
  "Emef Vereador Carlos Pessoa de Brum",
  "EMEF Vila Monte Cristo",
  "Emef Vila Montecristo",
  "EMEI",
  "EMEI Dom Luiz de Nadal",
  "EMEI Humaitá",
  "Emei Ilha da Pintada",
  "EMEI JP Passarinho Dourado",
  "EMEI JP Patinho Feio",
  "EMEI JP Pica-Pau Amarelo",
  "EMEI Miguel Granato Velasquez",
  "EMEI Nova Restinga",
  "Emei Protásio Alves",
  "Emei Santo Expedito",
  "EMEI Tio Barnabé",
  "EMEI Vila Elizabeth",
  "EMEM",
  "Empreendedorismo",
  "Emprego",
  "Empresa Pública de Transporte e Circulação (EPTC)",
  "Encerramento",
  "Enchente",
  "Enchente Porto Alegre",
  "Enchente Porto Alegre Maio de 2024",
  "Encontro com as Associação das Empresas dos Bairros Humaitá e Navegantes",
  "Ensino",
  "Entrada da cidade",
  "Entrega da Lei Orçamentária Anual (LOA) 2019",
  "Entrega de Doações",
  "Entrega de kits de brinquedos doados pela Fundação Abrinq",
  "Entrega de Matrículas de Regularização para Moradores da Zona Sul",
  "Entrega de Obras",
  "Entrevista Coletiva",
  "Epidemiologia",
  "Eptc",
  "EPTC",
  "Eptc -",
  "Equipamentos Hospitalares",
  "Equipe de Manejo Arbóreo (EMA)",
  "Equipe de Veículos de Tração Animal (VTA)",
  "Equipe de Vigilância de Alimentos da SMS",
  "Equipe de Vigilância de Antropozoonoses (Evantropo)",
  "Equipe de Vigilância em Saúde Ambiental e Águas (EVSAA)",
  "Equipe de Vigilância Eventos Vitais (EVEV)",
  "Equipe eMulti SUS",
  "Erno Harzheim",
  "Escada rolante",
  "Escola",
  "Escola Comunitária de Educação Infantil (Ecei) Madre Teresa",
  "Escola Comunitária de Educação Infantil (Ecei) Tia Mariazinha",
  "Escola de Gestão Pública (EGP)",
  "Escola Especial para Surdos Frei Pacífico",
  "Escola Estadual de Ensino Fundamental Duque de Caxias",
  "Escola Mariano Beck",
  "Escola Municipal de Educação infantil Humaitá",
  "Escola Municipal de Educação Infantil Jardim de Praça Pica-Pau Amarelo",
  "Escola Municipal de Ensino Fundamental Deputado Victor Issler",
  "Escola Municipal de Ensino Fundamental José Loureiro da Silva",
  "Escola Municipal de Ensino Fundamental Nossa Senhora de Fátima",
  "Escola Municipal Especial de Ensino Fundamental Eliseu Paglioli",
  "Escola Superior de Direito Municipal - ESDM",
  "Escolas Municipais de Educação Infantil",
  "Escolta",
  "Escorpião Amarelo",
  "Escritório de Reconstrução",
  "Escultura",
  "Esgoto",
  "Esgoto Pluvial",
  "Espaço Hortomercado Parobé",
  "Espaço Infantil",
  "Espetáculo",
  "Espetáculo O Rei da Vela",
  "Esporte",
  "Esporte, Lazer e Juventude",
  "Esporte Lazer e Juventude",
  "Esportes e Lazer",
  "Esquina Democrática",
  "Estação de Bombeamento de Águas Pluviais (Ebap)",
  "Estação de Transbordo",
  "Estação Rodoviária de Porto Alegre",
  "Estácio",
  "Estações de Bombeamento de Águas Pluviais (Ebaps)",
  "Estádio Beira-rio",
  "Estiagem",
  "Estrada das Furnas",
  "Estrada João de Oliveira Remião",
  "Estreia",
  "Estudantes",
  "ETA",
  "ETA Moinhos de Vento",
  "ETA São João",
  "evento social",
  "evento turístico internacional",
  "Eventos Climáticos",
  "Exame médico",
  "Executivo",
  "Exército Brasileiro",
  "Expointer",
  "exposição",
  "Exposição Fotográfica",
  "Extremo Sul",

  "Fachada",
  "Fake News",
  "Famurs",
  "Farmácia",
  "Farmácia Distrital Modelo",
  "Farmácia Móvel",
  "Fasc",
  "Fauna",
  "Fazenda",
  "febre amarela",
  "Fecomércio",
  "Federação das Associações de Municípios do Rio Grande do Sul (FAMURS)",
  "Federação de Entidades Empresariais do Rio Grande do Sul ( Federasul )",
  "Feira de Oportunidades",
  "Feira do Livro",
  "Feira Ecológica",
  "Feira Fora da Feira",
  "Feira Temática",
  "Felipe Hirsch",
  "Festejos",
  "Festa de Nossa Senhora dos Navegantes",
  "Festival",
  "Festival de Inverno",
  "Festival do Japão",
  "Festuris 2018",
  "Fiergs",
  "Fim de tarde",
  "Finanças",
  "Finanças Públicas",
  "Fios Soltos",
  "Fique Sabendo Jovem",
  "Fiscalização",
  "Flagrante",
  "Flora",
  "Florianópolis-SC",
  "FNP",
  "foco de lixo",
  "Fonte Talavera",
  "Food truck",
  "Força Nacional do SUS",
  "Força-Tarefa",
  "Forças Armadas",
  "Formação",
  'Formação "O trabalho em Direitos Humanos na Educação Infantil"',
  "Formação de Multiplicadores",
  "Formatura",
  "Formulário",
  "Fórum",
  "Fórum de Justiça e Segurança do Centro",
  "Fórum Social Mundial da População Idosa",
  "foto aérea",
  "foto noturna",
  "Fotografia",
  "Fotos Antigas",
  "Fraport Brasil S.A.",
  "Frente Nacional dos Prefeitos (FNP)",
  "Frente Parlamentar de Segurança",
  "Frio",
  "Fundação de Assistência Social e Cidadania – Fasc",
  "Fundação de Atendimento Socioeducativo do Rio Grande do Sul (Fase)",
  "Fundação Iberê Camargo",
  "Fundação O Pão dos Pobres",
  "Futebol",
  "Futebol de Várzea",
  "Futebol Feminino",
  "Futsal",

  "Gabinete",
  "Gabinete da Causa Animal (GCA)",
  "Gabinete da Inovação",
  "Gabinete da Primeira-Dama",
  "Gabinete da Procuradoria",
  "Gabinete da SMDSE",
  "Gabinete de Inovação",
  "Gabinete de Inovação (GI)",
  "Gabinete do Prefeito",
  "Gabinete Prefeito",
  "Gabriel Souza",
  "Galera Curtição",
  "Galeria de Arte do Dmae",
  "Galpão da Hospitalidade",
  "gari",
  "Gato",
  "GeraçãoPoa",
  "GeraEncontro",
  "Gestão 2025 - 2028",
  "Gestão e Planejamento",
  "Gestores dos CRIPs",
  "Ginásio do Colégio Protásio Alves",
  "Ginásio Lupi Martins",
  "Ginásio Tesourinha",
  "Ginástica",
  "Governador",
  "Governador Eduardo Leite",
  "governador em exercício",
  "Governacia Local e Coordenação Politica",
  "Governança",
  "Governança Local e Coordenação Política",
  "Governança Local e Coordenação Política.",
  "Governo Federal",
  "Gp",
  "Grêmio Foot-Ball Porto Alegrense",
  "Grêmio Sargento Expedicionário Geraldo Santana",
  "Gre-Nal",
  "Gre-nal de Todos",
  //"Greve",
  "Gripe",
  "Grupo de Combate ao Tabagismo",
  "Grupo Experimental de Dança (GED)",
  "Grupo Hospitalar Conceição (GHC)",
  "Grupo POA Solidárias",
  "Guaíba",
  "Guarda Municipal",
  "Gustavo Paim",
  "Gvp",

  "Habitação",
  "Habitação Regularização Fundiária",
  "Habitação e Regularização Fundiária",
  "Hamilton Sossmeier",
  "Handebol",
  "Hanseníase",
  "Heineken F1 Experience",
  "Hepatite",
  "hipertensão arterial",
  "hipertenso",
  "Hipismo",
  "HMIPV",
  "Homenagem",
  "Horário estendido",
  "Hortas Comunitárias",
  "Hortomercado Parobé",
  "Hospital da Restinga Extremo Sul (HRES)",
  "Hospital de campanha",
  "Hospital de Clínicas de Porto Alegre (HCPA)",
  "Hospital de Pronto Socorro (HPS)",
  "Hospital Materno-Infantil Presidente Vargas (HMIPV)",
  "Hospital Moinhos de Vento",
  "Hospital Santa Ana",
  "Hotel Deville",
  "Hotel Laghetto Stilo Higienópolis",
  "Hotel Serra Park Gramado",

  "I Love Poa",
  "Ideb",
  "Idosos",
  "Igreja Nossa Senhora das Dores",
  "Ilha da Pintada",
  "Ilha dos Marinheiros",
  "Iluminação Pública",
  "Imagem Aérea",
  "Imigrantes",
  "Imposto",
  "Inacio Etges",
  "Inauguração",
  "Inauguração do Hospital Santa Ana",
  "Inauguração Restaurante 360 POA GASTROBAR",
  "Incêndio",
  "Incluir + POA",
  "Inclusão Em Cena",
  "Inclusão Social",
  "Indumentária Gaúcha",
  "Indústria",
  "Infecções Sexualmente Transmissíveis (IST)",
  "Infográfico",
  "Informatização",
  "Infraestrutura e Mobilidade",
  "Infraestrutura e Mobilidade Urbana",
  "Infraestrutura e Urbanismo",
  "Início da operação da primeira faixa reversível semaforizada da Capital",
  "Início da Primavera 2018",
  "Inovação",
  "Inspeção veicular",
  "Instituto Caldeira",
  "Instituto São Francisco",
  "Instituto Ling",
  "Instituto Penal Feminino de Porto Alegre",
  "Integração Metropolitana de Transporte",
  "Interdição",
  "Internet",
  "IPTU",
  "Isatir Antonio Bottin Filho",
  "IST Aids",
  "IST Aids e Hepatites Virais",

  "Janeiro Branco",
  "Jardins do DMAE",
  "Jockey Club",
  "Jogos Abertos",
  "Jogos dos Estudantes Surdos",
  "Jornada Científica do HPS",
  "Josep Piqué",
  "Junta de Serviço Militar",
  "Justiça",
  "Juventude",

  "Kombina",

  "Laboratório do HMIPV",
  "Laboratórios Municipais",
  "Laçador",
  "Lago Guaíba",
  "Lançamento",
  "Lançamento do Lance de Craque 2018",
  "Lançamento do Pacto Pela Inovação - Pacto Alegre",
  "Lançamento do Projeto de Lei para PPP de Iluminação Pública",
  "Lançamento Oficial da 64ª edição da Feira do Livro de Porto Alegre",
  "Lançamento oficial da Expodireto Cotrijal 2025",
  "Largo Glênio Peres",
  "Largo Zumbi dos Palmares",
  "lavagem de vias e pontos",
  "Lazer",
  "Lei",
  "Lei de Diretrizes Orçamentárias (LDO)",
  "Lei Orçamentária Anual (LOA)",
  "Lei Seca",
  "Leishmaniose",
  "Leito Hospitalar",
  "Leonardo Pascoal",
  "LGBT",
  "LGBTQIA+",
  "Licenciamento Ambiental",
  "Licenciamento Urbano",
  "Licitação para Manutenção Elevadores e Escadas Rolantes",
  "Limpeza",
  "Limpeza Urbana",
  "Linha Turismo",
  "Liquida Porto Alegre",
  "Literatura",
  "Live",
  "Livro e Literatura",
  "Livros",
  "Lixo",
  "Lomba do Pinheiro",
  "Loteamento",

  "macacos-prego",
  "Mãe",
  "Maio Amarelo",
  "Maio Vermelho",
  "Manifestação",
  "Manutenção",
  "Mapa",
  "mapa de serviço de trânsito",
  "Maratona",
  "Maratona de Dança",
  "Marcelo Soletti",
  "Marcino Fernandes",
  "Marcos Frota",
  "Maria Carpi",
  "Maria de Fátima Záchia Paludo",
  "Marinha do Brasil",
  "Mascote",
  "Mastectomia em animais",
  "Material Escolar",
  "Mauro Pinheiro",
  "MEC",
  "Medicamentos",
  "Medicina",
  "Medicina Veterinária",
  "Meio Ambiente",
  "Meio Ambiente e Sustentabilidade",
  "Meio Ambiente Sustentabilidade",
  "Meio Ambiente Urbanismo e Sustentabilidade",
  "Meio Ambiente, Urbanismo e Sustentabilidade",
  "Memória",
  "Memorial do Rio Grande do Sul",
  "Menino Deus",
  "Mercado do Bom Fim",
  "Mercado Público",
  "Mercado Público Central",
  "Mês do Idoso",
  "Metas",
  "Mexatchê",
  "Ministério da Saúde",
  "Ministerio Público - RS",
  "Ministro da Saúde Gilberto Occhi",
  "Missão Xangai 2018",
  "Mobiliário Urbano",
  "Mobilidade",
  "Mobilidade Urbana",
  "Moinhos de Vento",
  "Monitoramento",
  "Montagem das Estruturas da 64ª Feira do Livro de Porto Alegre",
  "Monumento à Elis Regina",
  "Monumento a Júlio de Castilhos",
  "Monumento ao Expedicionário",
  "moradias temporárias",
  "Moradores do Alameda Partenon",
  "Morcego",
  "Morro da Apamecor",
  "Morro Ricaldone",
  "Morro Santana",
  "Mortes no trânsito",
  "Mosquito Aedes Aegypti",
  "Mostra Acústicos e Elétricos",
  "Motocicleta",
  "Mulher",
  "multivacinação",
  "Muro da Mauá",
  "Museu de Porto Alegre Joaquim Felizardo",
  "Museu Joaquim Felizardo",
  "Música",
  "Mutirão",
  "Mutirão de cirurgias",
  "Mutirão de Limpeza",

  "Natal",
  "Natal dos Encantos",
  "Navegantes",
  "Nelson Marchezan Júnior",
  "Nivel do Guaíba",
  "Nova Ponte do Guaíba",
  "Novembro Azul",
  "Novo Layout Caminhões Coleta Seletiva",
  "Novo Líder de Governo na Câmara de Vereadores de Porto Alegre",
  "Novo Marco Global",
  "Núcleo de Ações Preventivas (NAP)",
  "Núcleo de Imunizações DVS (NI)",
  "Núcleo Municipal de Segurança do Paciente",
  "Nutrição",
  "Nuvens",

  "OAB-RS",
  "Obra de arte",
  "Obras",
  "Obras da Copa de 2014",
  "Obras de implantação da adutora da Estrada Antonio Borges",
  "Obras e Infraestrutura",
  "Obras Restinga 2018",
  "Observatório de Porto Alegre",
  "óculos",
  "OdontoSesc",
  "Oficina",
  "Oficina ‘Rabiscando Ideias: Da cabeça para o papel’",
  "Oficina de Dança",
  "oftalmologista",
  "Olimpíada Brasileira de Matemática - OBMEP",
  "Ônibus",
  "ônibus elétrico",
  "OP",
  "Op 2017",
  "Operação Bota-Fora",
  "Operação de Segurança",
  "Operação Inverno",
  "Operação Jaguar",
  "Operação Sossego",
  "operários",
  "Orçamento Participativo",
  "Orçamento Participativo 2018",
  "Orla",
  "Orla de Ipanema",
  "Orla do Guaíba",
  "Orla Moacyr Scliar",
  "Orly Portal",
  "Outubro Rosa",

  "Paço dos Açorianos",
  "Paço Municipal de Porto Alegre",
  "Pacto Pela Inovação",
  "Painel",
  "Palácio do Comércio",
  "Palácio Piratini",
  "Palestra",
  "Parcão",
  "Parceria Público-Privada",
  "Parcerias",
  "Parcerias Estratégicas",
  "Parklet",
  "Paróquia de São Jorge",
  "Parque Ararigbóia",
  "Parque Chico Mendes",
  "Parque Farroupilha (Redenção)",
  "Parque Germânia",
  "Parque Harmonia",
  "Parque Marechal Mascarenhas de Moraes",
  "Parque Mascarenhas de Moraes",
  "Parque Marinha do Brasil",
  "Parque Maurício Sirotsky Sobrinho (Harmonia)",
  "Parque Moinhos de Vento (Parcão)",
  "Parque Natural Municipal Morro do Osso",
  "Parque Urbano da Orla Moacyr Scliar",
  "parquímetro",
  "Partenon",
  "Páscoa",
  "Passeio",
  "Patrimônio",
  "Patrimônio Histórico e Cultural do município",
  "Pavimentação",
  "Pedestre",
  "Pedestre Idoso",
  "Permissionários do Serviço de Táxis",
  "Pessoa com Deficiência",
  "Pessoa com mobilidade reduzida",
  "pessoas",
  "Petrópolis",
  "Pgm",
  "PGM",
  "Pier do Barra Shopping Sul",
  "Pinacoteca Aldo Locatelli",
  "Pinacoteca Ruben Berta",
  "Pintura",
  "Pisa",
  "Piscinas Públicas",
  "Placa de veículos",
  "Planejamento",
  "Planejamento e Assuntos Estratégicos",
  "Planejamento e Gestão",
  "Plano de Mobilidade de Porto Alegre (MobiliPOA)",
  "Plano de Superação da Situação de Rua",
  "Plano Municipal de Superação da Situação de Rua",
  "Plataforma Reconstruir Porto Alegre",
  "Plantio",
  "Plantio de Árvores",
  "Plantio Sustentável do DMLU",
  "Plantio Urbano Sustentável",
  "Plano de ação Porto Alegre Forte",
  "Plano Diretor",
  "Plataforma Google for Education",
  "Plaza São Rafael",
  "Plenário Ana Terra - CMPA",
  "Poa Em Cena",
  "POA Em Cena",
  "PoaHub",
  "Poda",
  "Polícia Rodoviária Federal",
  "Polícia Rodoviária Federal (PRF)",
  "Polícia Rodoviária Federal - PRF",
  "Pontal do Estaleiro",
  "Ponte do Guaíba",
  "Pontifícia Universidade Católica do RS (PUCRS)",
  "População de Rua",
  "População em Situação de Rua",
  "População Negra",
  "Porão do Paço",
  "Portal da Transparência",
  "porteiros",
  "Porto Alegre",
  "Porto Alegre-RS",
  "Posse",
  "Posse da  Comissão de Saúde e Segurança da Fasc",
  "Posse da Comissão de Saúde e Segurança do Trabalho da SMRI",
  "Posse da Procuradora Municipal",
  "Posse Novos Procuradores-Gerais do Município",
  "Posse Novos Secretários Municipais",
  "Povo Negro",
  "PPA",
  "Praça da Alfândega",
  "Praça da Matriz",
  "Praça Darcy Azambuja",
  "Praça Doutor Lopes Trovão",
  "Praça Mafalda Veríssimo",
  "Praça Marechal Deodoro (Matriz)",
  "Praça Montevideo",
  "Praça Parobé",
  "Praça Província de Shiga",
  "Praças e Parques",
  "Praia de Belas",
  "Praia do Lami",
  "Prédio público",
  "Prédios e Edificações",
  "prefeita em exercício, Betina Worm",
  "Prefeito",
  "prefeito de Florianópolis, Topázio Neto",
  "Prefeito de Porto Alegre, Sebastião Melo",
  "prefeito Nelson Marchezan Júnior",
  "Prefeitos de Praça",
  "Prefeitura de Porto Alegre",
  "Prefeitura Municipal de Porto Alegre",
  "Prefeitura nos Bairros",
  "Prefeitura Nos Bairros",
  "Premiação",
  "Prêmio MPT na Escola",
  "Presidente",
  "presidente CEEE Equatorial, Riberto Barbarena",
  "Presidente da Câmara de Vereadores",
  "Presidente da Câmara Municipal de Vereadores,  Idenir Cecchim",
  "Presidente da Companhia de Processamentos de Dados do Município de Porto Alegre, Leticia Batistela",
  "presidente da Fundação de Assistência Social e Cidadania (FASC), Cristiano Roratto",
  "Presidente da República Luiz Inácio Lula da Silva",
  "Presidente das Mantenedoras Maristas do Sul",
  "Prevenção",
  "Previdência",
  "Previmpa",
  "Previsão do Tempo",
  "Primeira-dama",
  "Primeira-dama de Porto Alegre, Valéria Leopoldino",
  "Primeira Infância Melhor (PIM)",
  "Primeira Infância Melhor no Contexto Prisional (Pim Prisional)",
  "Primeiros Socorros",
  "Procempa",
  "Procissão",
  "Procissão de Nossa Senhora dos Navegantes",
  "Procon",
  "Procon Móvel",
  "Procon Municipal",
  "Procurador geral do município de Porto Alegre, Roberto Silva da Rocha",
  "Procuradora-geral do município Eunice Nequete",
  "Procuradoria",
  "Procuradoria Geral",
  "Procuradoria Geral do Município",
  "Procuradoria-Geral do Município de Porto Alegre",
  "Produtor Rural",
  "Professora Finalista do Prêmio RBS de Educação 2018",
  "Profissionais de Saúde",
  'programa "Lean nas Emergências"',
  "Programa de Residência Técnico-Superior (PRTS)",
  "Programa de Trabalho Educativo (PTE)",
  "Programa Família Acolhedora",
  "Programa Jovem Aprendiz",
  "Programa Mais Comunidade",
  "Programa Melhor em Casa",
  "Programa Municipal de Rastreamento de Câncer Colorretal",
  "Programa Nacional de Gestão de Custos (PNGC)",
  "Programa Saúde na Escola (PSE)",
  "Programa Teste e Trate",
  "Programação Cultural",
  "Programação de Novembro",
  "Programação do Reveillon",
  "Projeto 100% Digital",
  "Projeto Clássicos na Pinacoteca",
  "Projeto de Lei",
  "Projeto Feira Fora da Feira",
  "Projeto Inclusão em Cena 2018",
  "Projeto Jogo Limpo",
  "Projeto Kilombinho de Verão",
  "Projeto Mais Comunidade",
  "Projeto Pescar",
  "Prometa 2017",
  "Prometas",
  "Promotores da Saúde da População Negra",
  "Pronto Atendimento de Traumatologia e Ortopedia no Hospital Restinga Extremo Sul",
  "Propaganda Eleitoral",
  "Proposta orçamentária 2019",
  "Propriedades Rurais",
  "PUCRS",

  "Quadras de Beach Tennis",
  "Quarto Distrito",
  "Quero- Quero",
  "Quilombos",

  "Radar de Trânsito",
  "Ramiro Rosário",
  "Reciclagem",
  "Recital para Doação de um Piano para o Centro Cultural Multimeios Restinga",
  "Rede Calabria",
  "Rede de abastecimento de água",
  "Rede Municipal de Ensino",
  "Rede Pampa de Comunicação",
  "Rede Pública de Ensino",
  "redes de água",
  "Região Metropolitana",
  "Relações Institucionais",
  "Regularização",
  "Regularização Fundiária",
  "Reintegração de Posse",
  "Relatório das pré-Conferências Municipais dos direitos da Pessoa Idosa",
  "Relatório de Gestão",
  "Remanejo",
  "remoção de lixo",
  "Renda",
  "Representantes da CEF",
  "Reserva Biológica do Lami José Lutzenberger",
  "Resgate",
  "Resíduos Sólidos",
  "Resiliência",
  "Restauração",
  "Restaurante Baumbach",
  "Restaurante Orla 360",
  "Restaurante Popular",
  "Retirada de Passarela",
  "Retrato",
  "Retratos Oficiais",
  "Reunião",
  "Reunião com  a ASCONTEC",
  "Reunião com a Associação Dos Procuradores Do Município De Porto Alegre (APMPA)",
  "Reunião com a BM Par",
  "Reunião com a CRIP Leste",
  "Reunião com a EPTC e Sindicatos",
  "Reunião com o Diretor regional da Caixa Econômica Federal",
  "Reunião com o Presidente da Câmara de Vereadores de Porto Alegre",
  "Reunião com representantes das entidades e das associações de praças e parques",
  "Reunião com Representantes do Banco Mundial",
  "Reunião Plenária do COMUI",
  "Reunião sobre acolhida  ao grupo de venezuelanos",
  "Reunião Sobre Sistemas Informatizados",
  "Reunião-almoço Tá Na Mesa",
  "Reurbanização da Vila Tronco",
  "Revitalização",
  "Robótica",
  "Roçada",
  "Roda de Conversa Inclusiva",
  "rolo compressor",
  "Romaria de Santa Maria",
  "ROMU",
  "roubo",
  "Rua Camoati",
  "Rua Cecília Meireles",
  "Rua Francisco Petuco",
  "Rua José Pedro Boessio",
  "Rua Olavo Bilac",
  "Ruas e avenidas",

  "Sala Aldo Locatelli",
  "Sala Álvaro Moreyra",
  "Sala Cecy Frank",
  "Sala da Fonte",
  "Sala de aula",
  "Sala de monitoramento do Aedes da SES/RS",
  "Sala de Treinamento da SMPG",
  "Sala dos Embaixadores",
  "Sala P. F. Gastal",
  "Salão de Atos da UFRGS",
  "Salão Internacional de Desenho para Imprensa (Sidi)",
  "Salão Nobre",
  "Salão Nobre do Paço Municipal",
  "sanção de Projeto de Lei",
  "Sangue",
  "Santa Casa de Misericórdia de Porto Alegre",
  "Santa Cecília",
  "Santa Maria Goretti",
  "Santander",
  "Santuário de Nossa Senhora do Rosário",
  "Sarampo",
  "Sarau Café com Letras",
  "Saúde",
  "Sáude",
  "Saúde Bucal",
  "Saúde da Criança e Adolescente",
  "Saúde da População Negra",
  "Saúde do Idoso",
  "Saúde do Trabalhador",
  "Saúde Mental",
  "Saúde Nutricional e Amamentação",
  "Saúde Prisional",
  "Sebrae",
  "Secretária de Planejamento e Gestão",
  "Secretária Denise Russo",
  "Secretaria Extraordinária do Trabalho e da Qualificação Profissional (SMTQ)",
  "Secretária Municipal Cultura e Economia Criativa, Liliana Cardoso",
  "Secretaria Municipal da Fazenda (SMF)",
  "Secretaria Municipal de Administração e Patrimônio (SMAP)",
  "Secretaria Municipal de Assistência Social (SMAS)",
  "Secretaria Municipal de Cultura (SMC)",
  "Secretaria Municipal de Cultura e Economia Criativa (SMCEC)",
  "Secretaria Municipal de Desenvolvimento Econômico (SMDE)",
  "Secretaria Municipal de Desenvolvimento Econômico e Turismo (SMDET)",
  "Secretaria Municipal de Desenvolvimento Social (SMDS)",
  "Secretaria Municipal de Desenvolvimento Social e Esporte (SMDSE)",
  "Secretária municipal da Educação (SMED)",
  "Secretaria Municipal de Educação (SMED)",
  "Secretaria Municipal de Esporte, Lazer e Juventude (SMELJ)",
  "Secretaria Municipal de Governança Cidadã e Desenvolvimento Rural (Smgov)",
  "Secretaria Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretaria Municipal de Habitação e Regularização Fundiária (SMHARF)",
  "Secretária municipal de Habitação e Regularização Fundiária, Simone Somensi",
  "Secretaria Municipal de Meio Ambiente, Urbanismo e Sustentabilidade (SMAMUS)",
  "Secretaria Municipal de Mobilidade Urbana (SMMU)",
  "Secretaria Municipal de Obras e Infraestrutura (SMOI)",
  "Secretaria Municipal de Parcerias (SMP)",
  "Secretaria Municipal de Planejamento e Assuntos Estratégicos (SMPAE)",
  "Secretaria Municipal de Planejamento e Gestão (SMPG)",
  "Secretaria Municipal de Relações Institucionais (SMRI)",
  "Secretaria Municipal de Saúde (SMS)",
  "Secretaria Municipal de Segurança (SMSEG)",
  "Secretaria Municipal de Serviços Urbanos (SMSURB)",
  "Secretaria Municipal de Transparência e Controladoria (SMTC)",
  "Secretária Municipal de Transparência e Controladoria (SMTC), Mônica Leal",
  "Secretariado",
  "Secretário Eduardo Cidade",
  "Secretário Municipal da Educação (SMED)",
  "Secretário Municipal da Fazenda (SMF)",
  "Secretário municipal da Fazenda, Rodrigo Fantinel",
  "Secretário Municipal da Saúde (SMS)",
  "Secretário Municipal da Saúde (SMS), Fernando Ritter",
  "Secretário municipal da Segurança, Alexandre Augusto Aragon",
  "Secretário Municipal de Administração e Patrimônio (SMAP)",
  "Secretário municipal de Administração e Patrimônio, André Barbosa",
  "Secretário municipal de Desenvolvimento Social, Leo Voigt",
  "Secretário Municipal de Educação Adriano Naves de Brito",
  "Secretário municipal de Educação, Leonardo Pascoal",
  "secretário municipal de Governança Cidadã e Desenvolvimento Rural (Smgov), Cássio Trogildo.",
  "Secretário Municipal de Governança Local e Coordenação Política (SMGOV)",
  "Secretário municipal de Governança Local e Coordenação Política, Cássio Trogildo",
  "Secretário municipal de Obras e Infraestrutura, André Flores",
  "Secretário municipal de Planejamento e Assuntos Estratégicos, Cezar Schirmer",
  "Secretário municipal do Gabinete de Inovação, Luiz Carlos Pinto da Silva Filho",
  "Secretário municipal do Meio Ambiente, Urbanismo e Sustentabilidade, Germano Bremm",
  "Secretário-adjunto de Planejamento e Gestão",
  "Sede da EPTC",
  "Sede da SMED",
  "Sede da SMPG",
  "Sede do Detran -RS",
  "Sede do Previmpa",
  "Sede do Tribunal de Contas do Estado (TCE)",
  "Seguranç",
  "Segurança",
  "Segurança do Paciente",
  "Segurança Publica",
  "Segurança Pública",
  "Seletiva no Contêiner",
  "Semáforos",
  "Semana Acadêmica da Escola de Engenharia",
  "Semana Cidade Limpa",
  "Semana da Água",
  "Semana da Consciência Negra",
  "Semana de Porto Alegre",
  "Semana do Japão",
  "Semana Farroupilha",
  "Semanas Internacionais",
  "Seminário",
  "Seminário Boas Práticas na Gestão de Trânsito dos Municípios",
  "Seminário Nacional de Trânsito - Mobilidade Sustentável, Educação, e Segurança",
  "Seminário Povos Indígenas e Saúde: Um Corpo São",
  "Senac",
  "Serviço de Atendimento Móvel de Urgência (SAMU)",
  "Serviço Funerário",
  "Serviço Social",
  "Serviços de Roçada e Capina",
  "Serviços Ortopédicos",
  "Serviços Urbanos",
  "Servidor",
  "Sessão de julgamento da 1ª Câmara do TART",
  "Sessão Solene de outorga de Título de Cidadão de Porto Alegre ao Presidente Estadual da Assembleia de Deus Pastor Adalberto Santos Dutra",
  "Sesc",
  "SESI",
  "Sétimo encontro de Medicina Tradicional Kaingang",
  "Shopping Total",
  "Show de Talentos da FASC",
  "Sífilis",
  "Simpósio",
  "Sinalização de trânsito",
  "sinalização semafórica",
  "Sinalização viária",
  "Sindha",
  "Sindicato dos Municipários de Porto Alegre (Simpa)",
  "Sindilojas",
  "síndrome de down",
  "Sine Municipal",
  "Sistema Único de Saúde (SUS)",
  "Situação de rua",
  "Smams",
  "SMAMS",
  "Smamus",
  "Smc",
  "Smc -",
  "SMC - 1ª Invernada Farroupilha Paixão Cortes 2018 Mostra de Dança",
  "SMC - FUMPROARTE comemora 25 anos",
  "Smc - Poa Em Cena",
  "Smde",
  "SMDE - Secretaria Municipal de Desenvolvimento Econômico",
  "Smdes",
  "Smds",
  "Smdse",
  "SMDSE - Desenvolvimento Social e Esporte",
  "Smed",
  "SMED",
  "Smf",
  "SMF",
  "Smgov",
  "Smic",
  "Smim",
  "SMIM - Infraestrutura e Mobilidade Urbana",
  "Smpe",
  "Smpg",
  "Smri",
  "Sms",
  "SMS",
  "Smseg",
  "Smseg - Segurança",
  "SMSEG - Segurança",
  "Smsurb",
  "SMSURB",
  "Smtc",
  "SMTC - Marco Regulatório das Organizações da Sociedade Civil",
  "SMTC - Transparência e Controladoria Geral",
  "Socioambiental",
  "Sociedade Libanesa de Porto Alegre",
  "Sol",
  "Solidariedade",
  "Sport Club Internacional",
  "Subprefeituras",
  "Sustentabilidade",

  "Tabagismo",
  "Tapa Buracos",
  "Talude",
  "Tarifa",
  "Táxi",
  "Táxis Novos",
  "Teatro",
  "Teatro Carlos Carvalho",
  "Teatro de Câmara Túlio Piva",
  "Teatro do CIEE",
  "Teatro do Sesc",
  "Teatro do Sesi",
  "Teatro Renascença",
  "Tecnologia",
  "TelessaúdeRS",
  "Tempo",
  "Temporal",
  "Tenda",
  "Terminais de ônibus",
  "Terminal Parobé",
  "Terminal Triângulo",
  "Termo de Adoção de Verde Complementar",
  "Termo de Cooperação Técnica",
  "Termos de Permissão uso bares da Orla do Guaíba",
  "Terreno",
  "Testagem",
  "Teste do Pezinho",
  "teste rápido sífilis, hiv e hepatite C",
  "Theatro São Pedro",
  "TJ-RS",
  "Todos Contra O Assédio",
  "Top de Marketing ADVB/RS",
  "Totem de atendimento 156",
  "Totem iluminado",
  "Trabalho e Emprego",
  "Trabalho e Qualificação",
  "Trade Commissioner",
  "Tradição",
  "Tradicionalismo",
  "Transexualidade",
  "trânsito",
  "Trânsito e Circulaçâo",
  "Trânsito e Circulação",
  "Transito e Transporte",
  "Transmissão de Cargo",
  "Transparência",
  "Transparência e Controladoria",
  "Transparência e Controladoria Geral",
  "Transporte",
  "Transporte Coletivo",
  "Transporte e Circulaçao",
  "Transporte e Circulação",
  "Transporte fluvial de passageiros",
  "Transporte Metropolitano",
  "Transporte Público",
  "Transtornos no trânsito",
  "Tratamento de água",
  "Treinamento da Cruz Vermelha",
  "Trensurb",
  "Tribunal de Contas do Estado do Rio Grande do Sul (TCE-RS)",
  "Tribunal de Justiça do Estado do Rio Grande do Sul",
  "Tributação",
  "Tributo a Elis Regina",
  "Trilha",
  "Trincheira da Ceará",
  "Tristeza",
  "troféu Prefeito Inovador",
  "Túnel da Conceição",
  "Turismo",

  "Ulbra",
  "Unesco",
  "Unidade de Coleta e Transfusão (UCT) do HPS",
  "Unidade de Pronto Atendimento (UPA)",
  "Unidade de Saúde",
  "Unidade de Saúde 1º de Maio",
  "Unidade de Saúde Animal Victória (Usav)",
  "Unidade de Saúde Diretor Pestana",
  "Unidade de Saúde Fradique Vizeu",
  "Unidade de Saúde Modelo",
  "Unidade de Saúde Ponta Grossa",
  "Unidade de Saúde Santa Marta",
  "Unidade de Saúde São Carlos",
  "Unidade de Saúde Tristeza",
  "Unidade de Vigilância Ambiental (UVA)",
  "Unidade Móvel de Saúde",
  "Unipoa",
  "Uniritter",
  "Unisinos",
  "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)",
  "Universidade Federal do Rio Grande do Sul (UFRGS)",
  "UPA Moacyr Scliar",
  "Urbanismo",
  "Urbanização",
  "Usina do Gasômetro",

  "Vacina",
  "vacina contra a Dengue",
  "Vacinação",
  "Vagas de Emprego",
  "Valtuir Pereira Nunes",
  "Vandalismo",
  "Varejo",
  "veículo",
  "Veículos",
  "Venezuelanos",
  "Vento",
  "Verão",
  "vereador",
  "vereador Cassiá Carpes",
  "Vereador Giovane Byl",
  "Vereadores",
  "Viaduto Conceição",
  "Viaduto da Conceição",
  "Viaduto Otávio Rocha",
  "viagem",
  "Viagem à Brasília",
  "Viagem à Europa",
  "Vice-governador Gabriel Souza",
  "Vice-prefeita, Betina Worm",
  "Vice-prefeita de Porto Alegre, Betina Worm",
  "Vice-prefeito",
  "Vice-prefeito de Porto Alegre, Ricardo Gomes",
  "vice-prefeito Gustavo Paim",
  "vice-prefeito Ricardo Gomes",
  "Videoconferência",
  "Vigidesastres",
  "Vigilância de Alimentos",
  "Vigilância em Saúde",
  "Vigilância Em Saúde",
  "Vigilância Sanitária",
  "VIII Seminário de Saúde e Segurança no Trabalho",
  "Vila dos Ferroviários",
  "Vila dos Sargentos",
  "Vila Ipiranga",
  "Vila Jardim",
  "Vila Monte Cristo",
  "Vila Nova",
  "Vírus T-linfotrópico humano (HTLV)",
  "Visita",
  "Visita de Cortesia",
  "Visita dos Alunos do IFRS da Restinga ao Poa.Hub",
  "Visita domiciliar",
  "visita institucional",
  "Visita Técnica",
  "Vistoria",
  "Vistoria Obras Restaurante Panorâmico",
  "Vítimas",
  "Viva o Centro a Pé",
  "Vôlei",
  "Volta às aulas",
  "Voluntariado",
  "votação",

  "Wambert Gomes Di Lorenzo",
  "WhatsApp",
  "Workshop",
  "Workshop Gestão da Inovação na Administração Pública",

  "Xangai",
  "XI Prêmio EPTC de Educação para o Trânsito",

  "Zizi Possi",
  "Zona Leste",
  "Zona Norte",
  "Zona Rural",
  "Zona Sul",
  "Zona Urbana",
];
